### ISSUE TITLE
Release Pulsar 1.117.0

### ISSUE THREAD

**Issue by DeeDeeG** [pulsar-edit/pulsar#1004]
# Regular Release 1.117.0

- [x] ChangeLog updated (`CHANGELOG.md` and `welcome` package)
- [x] Blurb Text Complete (Comment Below)
- [x] Version Bump PR Created
- [x] Binaries Uploaded to GitHub (Including renamed binaries, and SHASUM file)
- [x] Release Posted! 🎊
- [x] Update Chocolatey Release
- [x] Website Links updated
- [x] Blog Post
- [x] Discord Announcement
- [ ] Reddit Announcement
- [ ] Mastodon Announcement
- [ ] Lemmy Announcement

**Comment by DeeDeeG** [comment]
Cross-linking the PR for the website download links and blog post: https://github.com/pulsar-edit/pulsar-edit.github.io/pull/273

**Comment by confused-Techie** [comment]
Looks like we forgot to close this one. Not sure if we ever did socials announcements, although I suppose at this point it doesn't matter to much.
