### ISSUE TITLE
Flatpak version acting weird (maybe compromised?). I'm getting a warning about it trying to access my wallet on KDE Plasma when other packages (like the AUR version) don't have that issue

### ISSUE THREAD

**Issue by Boux** [pulsar-edit/pulsar#1017]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I get this warning 50% of the time I open Pulsar through flatpak:
![image](https://github.com/pulsar-edit/pulsar/assets/2771413/63edbda2-a603-4a7a-afc8-0b24ee99834d)

I'm currently using KDE Plasma on Arch, everything is up to date

I have tried both the AUR and Flatpak versions of Pulsar, and only the flatpak seems to give me the error, this tells me that the flatpak is compromised in some way.

Here's a video of me opening the AUR version a bunch and not getting the warning (0:00 - 0:36), and then opening the Flatpak version a bunch and getting the warning 50% of the time (0:38 - 1:13):

https://github.com/pulsar-edit/pulsar/assets/2771413/b209fdaa-2f0d-4150-82d9-9a3e79c53bc3

(yes this is KDE Plasma, I'm just using a custom tiling wm to replace kwin)

### Pulsar version

1.117.0

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Base Arch, default kernel, up to date

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. install the flatpak version of Pulsar on Arch with KDE Plasma desktop environment
2. keep opening and closing the app on KDE Plasma until you see the warning (doesn't show up every time the app opens)

**Comment by confused-Techie** [comment]
Thanks a ton for the report.

But to let you know, the flatpak version of Pulsar is not officially maintained by the Pulsar team. Instead any issues with the flatpak should be reported to the community members that maintain it, as the Pulsar team has no part in doing so.

I'd recommend reporting any issues [here](https://github.com/flathub/dev.pulsar_edit.Pulsar) to see what could be done.

In the past I've looked at the build process for this repo, and as it's usually completely automated by flathub bots, I would doubt it's compromised. I'd assume this is most likely a bug.

**Comment by Boux** [comment]
According to https://github.com/flathub/dev.pulsar_edit.Pulsar/issues/49#issuecomment-2143084240, this was an issue in a KDE application kwallet), affecting multiple flatpak apps, not just Pulsar, I will close this, as it looks to be unrelated to Pulsar
