### ISSUE TITLE
The Pulsar icon on Windows is low-quality

### ISSUE THREAD

**Issue by theycallhermax** [pulsar-edit/pulsar#1064]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When installing Pulsar on Windows, the icons are low-quality. I have been a Pulsar user on Linux, specifically Fedora and Arch Linux, and the icons aren't low-quality.

### Pulsar version

1.119.0

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 11 (23H2)

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Install Pulsar
The icon is low-quality.

### Additional Information:

![image](https://github.com/user-attachments/assets/83045962-a0bb-40a0-bc13-2ea97871db41)
![image](https://github.com/user-attachments/assets/43d2a29c-01c7-46ff-b8bf-2f56c9a15956)
![image](https://github.com/user-attachments/assets/9bdff4d9-1892-46fc-a259-c6dd6a3349a9)

**Comment by confused-Techie** [comment]
Thanks for reporting this issue!
We absolutely do need to get this `ico` file updated, but it only includes a rather low quality variant of our logo, leading to Windows trying to upscale it, and obviously not turning out to well.

Will have to look into this to see what we can do, or if there is anyone more familiar on the subject feel free to chime in
