### ISSUE TITLE
Not working on my machine.

### ISSUE THREAD

**Issue by AntiWorkIncel** [pulsar-edit/pulsar#1084]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Pulsar just doesn't open, the icon does nothing. Even calling it from the terminal, no response.
I use VScode and PyCharm, heard about Pulsar yesterday, and it just doesn't work.

### Pulsar version

1.120.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Debian 12

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Download it
2. Try to start it

**Comment by savetheclocktower** [comment]
Thanks for filing an issue!

You may want to [try installing an earlier release](https://github.com/pulsar-edit/pulsar/releases) just to rule out that this is something that was recently introduced. If that doesn't work, you could also try the AppImage distribution or the ordinary `tar.gz` distribution just to rule out issues that would be specific to the Debian release.

In the meantime, I'll see if I can reproduce this in a VM.

**Comment by AntiWorkIncel** [comment]
Sorry, nvm.
It was just some shit I made to save CPU usage that wasn't letting me use some programs, like Pulsar, Joplin and Insomnia.
