### ISSUE TITLE
PHP color coding not respecting null-safe operator

### ISSUE THREAD

**Issue by EliW** [pulsar-edit/pulsar#1100]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I noticed recently that color coding gets messed up whenever I use a null-safe operator in PHP.  Pulsar doesn't seem to actually understand that it is an operator, nor therefore that what follows is a property nor method.

### Pulsar version

1.120.0

### Which OS does this happen on?

🍎 macOS

### OS details

15.0 (24A335)

### Which CPU architecture are you running this on?

Apple M-series

### What steps are needed to reproduce this?

1. Be editing a PHP file
2. Write a line of code showing the use of normal arrow operators, to see the color coding, such as:
   ```php
   $property->addresses()->first()->city;
   ```
3. Replace each of those (or any of those) with nullsafe operators, and see the color coding disappear:
   ```php
   $property?->addresses()?->first()?->city;
   ```

### Additional Information:

Screenshot showing the top line with normal color coding, and each subsequent one with 'greyed out' sections of the line due to this:
<img width="430" alt="Screenshot 2024-09-19 at 4 37 41 PM" src="https://github.com/user-attachments/assets/9b5fc315-c5e3-4a03-8ee5-9b4b3398a8dc">

**Comment by savetheclocktower** [comment]
Yeah, didn't know this was even a thing. I'll get this fixed for 1.122. Thanks for the report!

**Comment by savetheclocktower** [comment]
OK, it'll go out in mid-October. (You're unlucky in that respect; if it's a hardship, you might be able to get by with a CI build of Pulsar until then, depending on your platform.) Thanks again!

**Comment by EliW** [comment]
Not a hardship at all, in fact I've been dealing with it for ... well, a long time.  Just finally had the "hey I should report this" moment.  Thanks for fixing it!
