### ISSUE TITLE
Can Pulsar be updated without losing the packages already installed?

### ISSUE THREAD

**Issue by Raf-sns** [pulsar-edit/pulsar#1128]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

As the title

### What benefits does this feature provide?

As the title

### Any alternatives?

As the title

**Comment by savetheclocktower** [comment]
Yes, definitely. Any community packages you install are stored separately from the application itself.

If you have further questions like this, please post in [GitHub Discussions](https://github.com/orgs/pulsar-edit/discussions) or ask them on [our Discord](https://discord.gg/7aEbB9dGRT).

**Comment by Raf-sns** [comment]
hi, thanks for your reply.
I couldn't find the talk page, so I posted it here...
