### ISSUE TITLE
Pulsar Regular Release 1.122.0 and later break Project Plus package's features

### ISSUE THREAD

**Issue by cmeh** [pulsar-edit/pulsar#1169]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

First of all, a big 'thank you' to all developers and contributors for their continued development of Pulsar after Microsoft has shut down the Atom Editor. Thank you all very much for keeping this wonderful application alive.

**[Project Plus](https://web.pulsar-edit.dev/packages/project-plus)** is an IMHO popular and useful plugin package for managing projects. Unfortunately, Pulsar's Regular Release [1.122.0](https://github.com/pulsar-edit/pulsar/releases/tag/v1.122.0) and all releases beyond seem to partly break its' functionality.

In Pulsar [1.121.0](https://github.com/pulsar-edit/pulsar/releases/tag/v1.121.0) and earlier, Project Plus' Project Finder would be displayed just fine. This GIF animation is from an earlier Atom version, but corresponds to the appearance in Pulsar ≤ 1.121.0:

[https://raw.githubusercontent.com/mehcode/atom-project-plus/master/project-plus.gif](https://raw.githubusercontent.com/mehcode/atom-project-plus/master/project-plus.gif)

In Pulsar [1.122.0](https://github.com/pulsar-edit/pulsar/releases/tag/v1.122.0) and later, however, pressing the corresponding hotkey now triggers the following error message (screenshots are from the current regular release [1.124.0](https://github.com/pulsar-edit/pulsar/releases/tag/v1.124.0)):

![Pulsar 1 124 0 Project Plus](https://github.com/user-attachments/assets/85286c56-7bbf-4074-b6f6-60b765b4e68c)

Here's the corresponding, more detailed error message from the Dev Tools:

![Pulsar 1 124 0 Project Plus Error Log](https://github.com/user-attachments/assets/038cabf9-369c-49ac-bf7e-b7f29dc2b51e)

... and in plain text:

```
project-finder-view.js? [sm]:121 Project Plus: Could not list projects: TypeError: Cannot read property 'then' of undefined
    at session.js:20:31
    at new Promise (<anonymous>)
    at findFromIndexedDB (session.js:14:10)
    at session.js:122:9
    at new Promise (<anonymous>)
    at SessionProvider.all (session.js:120:12)
    at provider-manager.js:33:26
    at Array.map (<anonymous>)
    at provider-manager.js:32:39
    at new Promise (<anonymous>)
    at ProviderManager.invoke (provider-manager.js:31:12)
    at ProviderManager.all (provider-manager.js:42:17)
    at ProjectPlusView.populate (project-finder-view.js:115:21)
    at ProjectPlusView.toggle (project-finder-view.js:73:12)
    at HTMLElement.project-plus:toggle-project-finder (project-plus.js:45:49)
    at CommandRegistry.handleCommandEvent (/opt/Pulsar/resources/app.asar/src/command-registry.js:405:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/Pulsar/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/Pulsar/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/opt/Pulsar/resources/app.asar/src/window-event-handler.js:153:34)
(anonymous) @ project-finder-view.js? [sm]:121
```

### Pulsar version

1.122.0 and later

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Debian GNU/Linux 12.8 Bookworm

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Steps to reproduce the **_intended_ behavior** on Windows, macOS and Linux:
1. Install [Pulsar 1.121.0](https://github.com/pulsar-edit/pulsar/releases/tag/v1.121.0).
2. Install the [Project Plus package](https://web.pulsar-edit.dev/packages/project-plus) within Pulsar.
3. If necessary, add some projects to the `projects.cson` file in Pulsar's user folder.
4. Press CTRL + ALT + P (rsp. for macOS: CTRL + CMD + P) to display Project Plus' Project Finder.

Steps to reproduce the reported **issue** on Windows, macOS and Linux:
1. Install [Pulsar 1.122.0](https://github.com/pulsar-edit/pulsar/releases/tag/v1.122.0) or later.
2. Install the [Project Plus package](https://web.pulsar-edit.dev/packages/project-plus) within Pulsar.
3. If necessary, add some projects to the `projects.cson` file in Pulsar's user folder.
4. Press CTRL + ALT + P (rsp. for macOS: CTRL + CMD + P) to display Project Plus' Project Finder. This will result in the error message documented above (and nothing more).

**Comment by confused-Techie** [comment]
Thanks a ton for contributing!
It seems the error in [`project-plus`](https://web.pulsar-edit.dev/packages/project-plus) is being triggered on this line:

```js
atom.stateStore.dbPromise.then((db) => {
```

I know in `v1.122.0` we did introduce an opt-in by default new StateStore, I'm not totally familiar with all of the changes that occurred in that PR, but pretty sure @mauricioszabo as the author may have some ideas here on why it's failing.

I would've assumed things stayed backwards compatible, but as we do eventually plan to move the state store over, it may be necessary for `project-plus` to be updated to continue working. But hopefully that's not the case

**Comment by confused-Techie** [comment]
Taking a look further, it seems we've compartmentalized the legacy and new database's behind the public class of `StateStore`.

As I don't think `dbPromise` was intended to be a public method it wasn't exposed. But since both databases do have this method, it may be possible that we could just expose them for the sake of restoring functionality here, without any adverse side effects

**Comment by asiloisad** [comment]
project-plus latest version is from 2017. It looks like the author has abandoned it. You can check similar package [project-list](https://web.pulsar-edit.dev/packages/project-list).

**Comment by cmeh** [comment]
Thank you very much, @confused-Techie , for not only analyzing the reported issue with Project Plus, but for even writing a patch and creating a pull request to Pulsar's master branch in virtually no time. That's far beyond everything I had expected or could have hoped for! 👍

@asiloisad Thanks a lot for suggesting [project-list](https://web.pulsar-edit.dev/packages/project-list) as an alternative. That looks really promising. I've already tested it and left you a [minor pull request](https://github.com/bacadra/pulsar-project-list/pull/1) for its' documentation.

Generally speaking, I'm aware that Project Plus was originally written for Atom and is obviously no longer actively maintained by its developer @mehcode since ~2018 (just as a description of the status quo w/o any complaints intended, he has every right to do so - it's free software, so anybody can fork and take over).

However, once a plugin package has reached a state of maturity in its features' implementation - which I think Project Plus had - this status is maybe not per se critical: There simply may be very little to change in your code for a very long time, once your features are working as intended.

Furthermore, Project Plus seems to have been quite popular plugin package for Atom with (at the time of writing) 58.000+ installations. Sure a lot of these installations have vanished with Microsoft's killing of Atom, but there still should be quite a number of Pulsar users like me with an installation.

If you then consider that Pulsar draws one of its main attractiveness from its sheer unlimited capacity to user customization, it can make sense to make a design decision like this one here that helps to preserve a popular plugin packages' functionality with hopefully no unwanted side effects.

Thank you again for all of your work and dedication in this project.
