### ISSUE TITLE
Installing Pulsar breaks other things - Linux

### ISSUE THREAD

**Issue by mal-practice** [pulsar-edit/pulsar#1175]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Installing Pulsar forces removal of coolercontrol. This is the case with 1.23 and 1.24 - this may be me being useless!

### Pulsar version

1.24.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Pop!_os

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Download .deb
2. Install using nala from the terminal

**Comment by savetheclocktower** [comment]
When you say it “forces” removal of coolercontrol: how does that present itself? On first reading I assumed you noticed coolercontrol was missing after you installed Pulsar, but your phrasing makes it sound like it was a choice that you were forced to make. I'm interested in learning more about that.

**Comment by confused-Techie** [comment]
Also something I'm curious about, you mention this occurs with Pulsar `1.123.0` & `1.124.0`, did it not happen with previous versions? Or are these just the versions you can confirm it occurs with?

But would love to hear any of our Linux folks thoughts on this @Spiker985

**Comment by Spiker985** [comment]
Looks like Nala is a frontend for Apt. PopOS! has there own package repos under http://apt.pop-os.org/release, but the current version is based on Ubuntu 22.04 LTS (aka Jammy Jellyfish). Cooler Control is hosted [here](https://gitlab.com/coolercontrol/coolercontrol) which contains information on how to install for Debian. And the dependencies for the package are [here](https://gitlab.com/coolercontrol/coolercontrol/-/blob/main/packaging/debian/control?ref_type=heads#L8-L30).

So if we have any conflicting package versions - that might be why?

@mal-practice Can you see if you can use the appimage of Cooler Control, or Pulsar without affecting the other?

**Comment by Spiker985** [comment]
Neither `apt` nor `pacman` appreciate having multiple versions of the same package installed at once, especially for dependencies

**Comment by savetheclocktower** [comment]
Near as I can tell, the only overlap between [their dependencies](https://gitlab.com/coolercontrol/coolercontrol/-/blob/main/packaging/debian/control?ref_type=heads) and [our dependencies](https://github.com/pulsar-edit/pulsar/blob/master/resources/linux/debian/control.in) is `libgtk-3-0`. `coolercontrol` tolerates any version, but Pulsar specifies `>= 3.9.10`. That doesn't seem to be a problem.

Unless I'm reading this wrong, this might be a more subtle incompatibility between transitive dependencies. Still curious what the original error message was.

**Comment by mal-practice** [comment]
Thanks for coming back so quickly - the screenshot is below - I have declined to continue on this occasion!
![coolercontrol-pulsar](https://github.com/user-attachments/assets/d8bc638c-f87e-43f3-b1fd-ea3b842071c2)

**Comment by savetheclocktower** [comment]
[This dependency](https://packages.debian.org/buster/libappindicator3-1) seems at odds with [this dependency](https://packages.debian.org/buster/libappindicator3-1). I don't know enough about why they're incompatible.

@mal-practice, I think it's fine to follow up with the developers of coolercontrol and/or solaar, but in the meantime you should see if the AppImage verison of Pulsar works for you. The initial installation might feel a bit weird, but [this section of the docs](https://docs.pulsar-edit.dev/getting-started/terminal-commands/#appimage-installation) explains how to make it behave identically to a more traditional installation method.

**Comment by mal-practice** [comment]
Thanks @savetheclocktower  @Spiker985  and others. Will look at the AppImage and see if I can get that going. Thanks again.
