### ISSUE TITLE
Azure Pipelines

### ISSUE THREAD

**Issue by softcode589** [pulsar-edit/pulsar#12]
The Azure Pipelines linked in the README is linking to Atom Community. Also, binaries are missing due to this. Setting up Azure Pipelines would be great.

**Comment by confused-Techie** [comment]
Great point about updating our build environment. Although I believe we have moved past using Azure Pipelines and are using Cirrus-Ci. But let me check with the core team if those remain to be the plans going forward.

**Comment by stech11845** [comment]
> Although I believe we have moved past using Azure Pipelines and are using Cirrus-Ci.

I don't see anything with "cirrus ci"
![image](https://user-images.githubusercontent.com/108250871/183313691-ee9b8994-8ab4-47c4-9401-1476673372e0.png)

**Comment by confused-Techie** [comment]
Since those changes aren't done they are on other branches. Mainly I believe they are on [rebrand-to-pulsar](https://github.com/pulsar-edit/pulsar/tree/rebrand-to-pulsar) and [build-without-scripts](https://github.com/pulsar-edit/pulsar/tree/build-without-scripts). It may be best in the meantime to change those links to Cirrus-Ci, although I'm talking rn with the core team about where we plan to go with the build environment.

**Comment by confused-Techie** [comment]
So we could use something like this:

![Cirrus Ci Build](https://img.shields.io/cirrus/github/pulsar-edit/pulsar/rebrand-to-pulsar)

But thats specifically for the `rebrand-to-pulsar` repo, maybe its best to remove Azure until we are able to merge the passing build to master, then we can add the proper badging. Just an idea though

**Comment by autumnblazey** [comment]
do you think removing the badge for now and adding it back when we have working CI is a good idea?

**Comment by confused-Techie** [comment]
Since this can not be resolved as of yet, I've gone ahead and added it to a new Project to track minor issues discovered across the repo, available as a [project on the org](https://github.com/orgs/pulsar-edit/projects/4)

**Comment by stech11845** [comment]
> Since this can not be resolved as of yet, I've gone ahead and added it to a new Project to track minor issues discovered across the repo, available as a [project on the org](https://github.com/orgs/pulsar-edit/projects/4)

Add this issue to the project? All are drafts.

**Comment by kaosine** [comment]
Yeah I think until runs are stable we're probably even moving to gha. Cirrus has weird limits that we can't seem to tune things down far enough to keep from hitting the limits for open source projects without someone forking over the cash for that. I'd suggest tho using the others as backups and have ready just in case we ever need to leave gh for any reason....

**Comment by stech11845** [comment]
If we move to Cirrus, then we might as well keep Azure Pipelines badge, but with a status saying "moved to cirrus (or whatever moving we do)." Like this:
![](https://img.shields.io/badge/Azure%20Pipelines-moved%20to%20Cirrus-inactive?logo=azurepipelines)

**Comment by autumnblazey** [comment]
hm.. I'm not entirely not sure that is needed?

**Comment by stech11845** [comment]
> hm.. I'm not entirely sure that is needed?

Sorry for delayed response, yeah that's good to just remove that.

**Comment by stechsoft13** [comment]
> Yeah I think until runs are stable we're probably even moving to gha. Cirrus has weird limits that we can't seem to tune things down far enough to keep from hitting the limits for open source projects without someone forking over the cash for that. I'd suggest tho using the others as backups and have ready just in case we ever need to leave gh for any reason....

Opened a vote in an org discussion [here](https://github.com/orgs/pulsar-edit/discussions/4) just to see.

**Comment by Spiker985** [comment]
Opened PR #58 to replace the Atom Community Azure badge with a Cirrus CI badge. For the time being, irrelevant of the discussion or decision go-forward, we should have an accurate badge.

Especially now that we have merged #54.

It also allows for ease of access, and at-a-glance status checking.

**Comment by kaosine** [comment]
@pulsar-edit/core I think we can close this one since it's finished?

**Comment by confused-Techie** [comment]
> @pulsar-edit/core I think we can close this one since it's finished?

Good catch, we now have proper links to our CI environment, and at least for the time being looks like we are sticking with it. So I'll go ahead and close this issue.
