### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by mauricioszabo** [pulsar-edit/pulsar#129]
### Thanks in advance for your bug report!

- [x] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

This test sometimes passes, sometimes fails:

```ConfigFile
  when the file is updated with valid CSON
    it notifies onDidChange observers with the data
      timeout: timed out after 120000 msec waiting for spec promise to resolve
```

It should be a good idea to investigate what's wrong and know if it's a valid concern or just a flaky test

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Any

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Check CI

**Comment by confused-Techie** [comment]
This report is now bundled into a single issue #511
