### ISSUE TITLE
Featured Packages shows Nothing

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#137]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When going into Settings and clicking Install on the sidebar, under the Featured Packages Section shows nothing

### Which OS does this happen on?

🪟 Windows

### OS details

21H1 (Build: 19043.2251)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open Settings
2. Click "Install" on sidebar
3. View section under Featured Packages

### Additional Information:

This issue is present for my Windows Machine on the [Pulsar Binary](https://cirrus-ci.com/build/6002334438785024) (That has the exact one I've got installed on that link).

This issue was also present to another user building from Source from Master and they are running:

Manjaro Linux ; (rolling)/Gnome-42.4

For my Windows System:
* Electron: 12.2.1
* Chrome: 89.04389.128
* Node: 14.16.0
* Pulsar: 1.63.2022111100 x64

**Comment by GuilleW** [comment]
Same on `Manjaro Linux ; (rolling)/Gnome-42.4`

**Comment by preland** [comment]
On Intel Mac, it does something slightly different, where it instead fails and throws an error.

However, I believe my specific case is related to issue #165, but I thought I'd put this here in case it turns out to be different.

**Comment by GuilleW** [comment]
This [AppImage](https://cirrus-ci.com/task/4958671814262784) works for me. So 
Featured Packages shows actually :tada:
