### ISSUE TITLE
Crash on startup on virtualbox/rocky9

### ISSUE THREAD

**Issue by luisbrandao** [pulsar-edit/pulsar#146]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Crash on startup on virtualbox rocky 9

Version used:
pulsar-1.63.2022111616.x86_64.rpm

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

rocky9

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Just run the program in a virtualbox with rocky9

### Additional Information:

techmago@rocky9 ~/Área de trabalho $ /usr/bin/pulsar, linha 194:  3051 Trace/breakpoint trap   (imagem do núcleo gravada)nohup "$PULSAR_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[3051:1116/193018.541178:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

**Comment by luisbrandao** [comment]
The same thing does not happen in the host machine (physical machine with rocky8)

**Comment by Daeraxa** [comment]
On the VM what happens if you start it with `--no-sandbox`?

**Comment by DeeDeeG** [comment]
It's also an issue with upstream Atom. --> https://github.com/atom/atom/issues/23036

I have to run it with one of the workaround flags, I've been using `--in-process-gpu`, but I think `--no-sandbox` may be more stable...? I have heard that either works.

If I understand correctly, it will be an issue on all recent Linux distros (specifically Linux with recent glibc) until the Electron version is updated to Electron 13, which is hard to do without breaking things.

**Comment by Daeraxa** [comment]
In which case we just need to keep this in mind for the Electron 19(?) fork and work.
I definitely got around it with `--no-sandbox` in an OpenSUSE VM.

**Comment by Spiker985** [comment]
I was forced to use `--no-sandbox` for both Atom and Pulsar. Looks like it's a `glibc` error from the comments on that atom issue.

Weird part for me was that it wasn't always that way

**Comment by FibroJedi** [comment]
I had this error on a clean install of Linux Mint (no VM), but I don't get that on whichever release I have on my old computer. I'll try with the above flags. Out of curiosity I also reinstalled Atom onto the new machine (the last stable version) and got the same error.

I'll see if the workarounds mentioned give me a temporary "fix".

**Comment by FibroJedi** [comment]
--no-sandbox does run it without it crashing, so that's good. I do get this when I run it from the command line (Linux Mint):
`cp: cannot stat 'resources/linux/desktopenviroment/cinnamon/pulsar.nemo_action': No such file or directory`

Did I miss something in my install?

**Comment by Daeraxa** [comment]
I'm using Mint but I've definitely not seen that...

**Comment by Spiker985** [comment]
> --no-sandbox does run it without it crashing, so that's good. I do get this when I run it from the command line (Linux Mint): `cp: cannot stat 'resources/linux/desktopenviroment/cinnamon/pulsar.nemo_action': No such file or directory`
> 
> Did I miss something in my install? 

There is a [file](https://github.com/pulsar-edit/pulsar/blob/master/resources/linux/desktopenviroment/cinnamon/pulsar.nemo_action) that exists for that within the repo. It sounds like it isn't getting put where it's supposed to and/or, there's a reference to it in a script, which is using a folder which "technically" doesn't exist on an install (not live build)

**Comment by luisbrandao** [comment]
@Daeraxa --no-sandbox is a viable workaround. thx

**Comment by Spiker985** [comment]
My assumption is that the file is supposed to be exported from the asar during install, to a computer-wide accessible folder for nemo actions

However, it's lack of existence shouldn't be causing errors

We may need to have you make your own issue @FibroJedi 

Placing that file won't fix the `--no-sandbox` requirement, that's a problem with some native libraries not being able to access the gpu

**Comment by FibroJedi** [comment]
> We may need to have you make your own issue @FibroJedi
> 
> Placing that file won't fix the `--no-sandbox` requirement, that's a problem with some native libraries not being able to access the gpu

Okay, I will do. Thanks.

**Comment by confused-Techie** [comment]
Resolved in #262 (I realize there is discussion of another issue, but that was requested to be it's own separate issue. As for the original one that this issue refers to has been fixed)
