### ISSUE TITLE
Cannot install packages on macOS (Intel)

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#165]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

On opening the "Install packages" pane it generates an error under "Featured packages".
The same error can be seen when attempting to install a package.

Indicates error with `git-utils`.

![image](https://user-images.githubusercontent.com/58074586/202931531-4dd11e51-1a5e-4e79-9429-47f93acdc7dc.png)

```
Installing “atom-clock@0.1.18” failed.Hide output…
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/git-utils/build/Release/git.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Applications/Pulsar.app/Contents/Resources/app/ppm/node_modules/git-utils/src/git.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

### Which OS does this happen on?

🍎 macOS

### OS details

macOS 11.5.2 20G95 x86_64

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open "Install Packages"
2. Wait and observer error under "Featured Packages"
3. Search for "clock"
4. Attempt to install "atom-clock" (although same will happen with any package)
5. Observe same error as before.

### Additional Information:

Cirrus binary https://cirrus-ci.com/task/6482747400126464 
Commit [2d37d3d](https://github.com/pulsar-edit/pulsar/commit/2d37d3d780f32d583e677bea6d0f7fcceb07204b)

**Comment by preland** [comment]
I had already brought up this issue in the Discord server, but forgot to make an issue here. Thanks!

If I remember correctly, we were able to figure out that the issue is that the version of Electron that is currently used does not line up with the version of Node being used. I believe this is being worked on currently, although I am not sure how long it will take for the issue to be resolved.

**Comment by mauricioszabo** [comment]
Fixedvia https://github.com/pulsar-edit/pulsar/pull/153. Also, fixes for Silicon too (the problem was happening on all mac builds for different reasons....)

**Comment by goyalyashpal** [comment]
![image](https://user-images.githubusercontent.com/19423063/230990766-2bfedbf2-8d75-4243-9c35-e16c3da31d7b.png)


```
Installing “uber-juno@0.3.0” failed. Hide output…
/usr/bin/bash: /s: No such file or directory
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Please install Python and Visual Studio to continue.
Run pulsar -p install --check after installing to test compiling a native module.
```

Pulsar Version: 1.103.0
OS: Win 10 22h2 (with msys2)

Try installing [Ubser Juno](https://web.pulsar-edit.dev/packages/uber-juno) (after associating Pulsar as "default `atom://` protocol handler" under URI Handling.

Also, This error or `/usr/bin/bash: /s: No such file or directory` is shown in most all places in settings in pulsar.
