### ISSUE TITLE
Windows Icon "Cut in Half" on Taskbar

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#188]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When opening Pulsar on Windows the taskbar icon is "cut in half" 
![image](https://user-images.githubusercontent.com/26921489/205192641-11df3225-73b3-49e6-93d2-6b48a7500ca6.png)

### Which OS does this happen on?

🪟 Windows

### OS details

22H2 OS Build: 19045.2251

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1) Install Pulsar 
2) Launch Pulsar
3) View Taskbar

### Additional Information:

This issue is present until pinning the Application Icon to the taskbar, then it becomes resolved.

Seems this issue is exactly as reported [here](https://github.com/electron-userland/electron-builder/issues/2128).

I've looked through our `./scripts/electron-builder.js` and can't find how we could reproduce those results.

The only thing that may work is changing the windows binaries to include the `.png`. Since really when looking through the Pulsar install folder I can't locate the `.ico` at all. But am easily able to locate the `.png`.

So it's possible that Windows is somehow falling back to that icon? So it may be worth a try, and will attempt if I get the chance. Otherwise someone more familiar with Electron Builder could try and take a look here

**Comment by langstonzac25** [comment]
Same problem, I would defiantly start using it if they fixed that but since I am so into aesthetics that is a game changer for me.

**Comment by confused-Techie** [comment]
> Same problem, I would defiantly start using it if they fixed that but since I am so into aesthetics that is a game changer for me.

Well if you'd like to start using Pulsar, if you pin the app to your taskbar this issue is resolved while pinned.

I'm looking into what we can do to fix it, but that is a workaround at this time.

**Comment by langstonzac25** [comment]
Ok it does have a full icon till I open it. Then it has a second icon in the taskbar with the half icon.  Here is a picture for reference.
![image](https://user-images.githubusercontent.com/101570030/207600288-4eb66811-734b-4515-bbd5-b16cf7afb2e6.png)

**Comment by confused-Techie** [comment]
> Ok it does have a full icon till I open it. Then it has a second icon in the taskbar with the half icon. Here is a picture for reference. ![image](https://user-images.githubusercontent.com/101570030/207600288-4eb66811-734b-4515-bbd5-b16cf7afb2e6.png)

Super interesting, I haven't seen that yet. Although I do group my taskbar icons so that might be it. Thanks for posting this to know it still does happen for that one window instance

**Comment by langstonzac25** [comment]
Actually that is just when I pin it from the start menu. When I open the app then pin it to the taskbar it keeps the icon when opened and closed. So I am content now now there is only the half icon in the title bar in windows but do not care about that as much. See picture.
![image](https://user-images.githubusercontent.com/101570030/207644672-2f218ad5-d833-4b2b-b130-8706b60b8f04.png)

**Comment by confused-Techie** [comment]
@langstonzac25 Glad to here we've found a suitable workaround, but lets hope we can find a proper resolution soon

**Comment by RonnyAL** [comment]
Could the solutions suggested [here](https://github.com/electron-userland/electron-builder/issues/2128) work? I am not in a position to test this myself at the moment, but hopefully this could prove helpful to those who are able to test.

**Comment by confused-Techie** [comment]
> Could the solutions suggested [here](https://github.com/electron-userland/electron-builder/issues/2128) work? I am not in a position to test this myself at the moment, but hopefully this could prove helpful to those who are able to test.

Appreciate the ideas, but yeah that's the same link I've got at the bottom of the issue.

While they have the exact same issue, I've tried and failed to see how the solution is applicable. Since there's seemed to be from a lack of specificity in the icon, which isn't true for ourselves. Our `electron-builder` config points directly to the image, but there are some other possibilities listed which seem less likely but still possible

**Comment by DeeDeeG** [comment]
I had read somewhere that limiting the color bit-depth to 8-bit color fixed it for someone?

Worth a try?

**Comment by langstonzac25** [comment]
I have solved my problem by installing the cirrus CI binaries. You do not need to uninstall your original insall. Just download the new installer run it and it will update your install. Then launch pulsar. It now displays the full icon in the taskbar. I hope this helps.

**Comment by Daeraxa** [comment]
We made a new release a couple of days ago so this should work on the beta version too now.
