### ISSUE TITLE
Help > About > How to update link goes to old Atom site

### ISSUE THREAD

**Issue by ljsinclair** [pulsar-edit/pulsar#193]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

FYI:
I haven't reproduced issue in safe mode because I have atom installed on the system and the `atom --safe` fires that up instead
There's no debugging involved. It's just a URL change.

## My environment

* Windows 10
* Pulsar 1.63.2022112905

## Issue

"How to update" link on the Help > About page links to the old atom site

https://flight-manual.atom.io/getting-started/sections/installing-atom/)

## Suggested fix

Link the page to the Pulsar Download page

https://pulsar-edit.dev/download.html

### Which OS does this happen on?

🪟 Windows

### OS details

10 

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open pulsar editor
2. Click Help > About
3. Click "How to update" link in the middle of the page.

**Comment by Daeraxa** [comment]
This should be fixed if my PR is merged - https://github.com/pulsar-edit/pulsar/pull/172
