### ISSUE TITLE
Tree view not respecting "ignored names"

### ISSUE THREAD

**Issue by mjrodgers** [pulsar-edit/pulsar#195]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Opening any project folder, the tree view shows all files regardless of whether they match entries in the "Ignored Names" section of the preferences (even if the ignored names are left at default).

In particular I have .DS_store items showing up everywhere. I don't have this issue in Atom.

(running Pulsar 1.63.2022120405)

### Which OS does this happen on?

🍎 macOS

### OS details

macOS 12.6.1

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Problem exists immediately with no special configuration

**Comment by SpaceToastKADK** [comment]
Can confirm the same issue in the latest Apple Silicon build as well. (1.102.x)

**Comment by savetheclocktower** [comment]
Odd. Can you confirm that “Hide Ignored Names” is checked in the `tree-view` package's settings?

**Comment by SpaceToastKADK** [comment]
Hide Ignored Names is unchecked by default in the tree-view package in the Mac builds. I'm assuming this is the bug, as the Core Settings pane specifically says it applies to: "...packages, such as the fuzzy finder and tree view."

**Comment by mjrodgers** [comment]
Can confirm this was the problem. This should definitely be checked by default and not unchecked.

**Comment by savetheclocktower** [comment]
You're right that the default should be `true` instead of `false`. That's easy enough to fix.

I'm wondering why it worked in Atom, because their default was `false` for that setting and we haven't changed anything.

Thanks for the report!
