### ISSUE TITLE
Minor but strange > Pulsar icon doesn't display properly on Windows 10

### ISSUE THREAD

**Issue by ljsinclair** [pulsar-edit/pulsar#200]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Pulsar icon in Windows 10 taskbar and application only partially displays when the application is running

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10 pro 22H2 19045.2251

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Install latest version of pulsar-edit
Open the application

### Additional Information:

Screenshot that demonstrates the issue:

![pulsar-edit-partial-icon-win10](https://user-images.githubusercontent.com/48849797/206062536-0334f8df-24b8-468e-b90d-875f018c21fd.jpg)

**Comment by confused-Techie** [comment]
This issue is also the same issue reported in #188

**Comment by ljsinclair** [comment]
DOH! Sorry >.<
