### ISSUE TITLE
`GPU process isn't usable. Goodbye.` issue on start

### ISSUE THREAD

**Issue by Flashwalker** [pulsar-edit/pulsar#205]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

```
$ /usr/bin/pulsar: line 166: 217750 Trace/breakpoint trap   (core dumped) nohup "$PULSAR_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[217750:1209/153159.171522:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
```

It is Electron issue, when Electron-libs don't match your system

`--in-process-gpu` option helps as workaround.  
Also `--disable-gpu-sandbox` or `--no-sandbox` helps too.

```
# works:
$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Downloads/Pulsar-1.63.2022120904.AppImage --in-process-gpu
$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Downloads/Pulsar-1.63.2022120904.AppImage --disable-gpu-sandbox
$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Downloads/Pulsar-1.63.2022120904.AppImage --no-sandbox
# or for .deb installed:
$ pulsar --in-process-gpu
```

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu 22.04

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. use .deb or .appimage package  
2. start app

### Additional Information:

same as  
 https://github.com/agalwood/Motrix/issues/1158  
 https://github.com/picturama/picturama/issues/116
 and many other Electron-based apps.

**Comment by Daeraxa** [comment]
Thanks for logging this but I think we have this in a couple of issues already where it is being tracked.
https://github.com/pulsar-edit/pulsar/issues/174
and 
https://github.com/pulsar-edit/pulsar/issues/199

**Comment by nPHYN1T3** [comment]
First launch (appImage) = FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.  Good times...

--no-sandbox gets it to launch but it locks to whatever GPU it was initially run on.
