### ISSUE TITLE
Error thrown in snippets package

### ISSUE THREAD

**Issue by snowcatridge10** [pulsar-edit/pulsar#211]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [x] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

![pulsarSnippetNotWorking](https://user-images.githubusercontent.com/72707293/206927830-adb3aed5-9289-4038-bcc5-bbdfccf3744c.jpg)

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 11

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

In this environment

**Comment by confused-Techie** [comment]
This is an issue that should be resolved. Do you mind confirming which version of Pulsar you are running? It should have been resolved two days ago in PR #206

**Comment by snowcatridge10** [comment]
My version is 1.63.2022120905

Thanks for responding

**Comment by confused-Techie** [comment]
> 20221209

Of course!

But yeah looks like you have the version right before this change was implemented. 

I'd recommend grabbing our latest CI build from our [website](https://pulsar-edit.dev/download.html#cirrus-ci-binaries) and see if it works now, the problem was fixed in version 1.63.2022121001

**Comment by snowcatridge10** [comment]
Ok thanks so much
