### ISSUE TITLE
Windows installation directory incorrect

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/pulsar#229]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When installed, the exe installer for Pulsar uses `%localappdata%\Programs\pulsar` as it's install directory instead of `%localappdata%\pulsar` like atom did previously

Presumably this is a simply oversight with the electron-builder config, but I wanted it documented before I forgot about it

### Which OS does this happen on?

🪟 Windows

### OS details

11 21H2 22000.1219

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1) Install the self-extracting exe

**Comment by Daeraxa** [comment]
This technically invalidates the documentation as I think we just did a straight swap of `\atom` to `\pulsar`. But if this is planned to be fixed here then the docs can stay.

**Comment by Spiker985** [comment]
I believe the only reason this happened was because we _technically_ didn't do an atom -> pulsar swap. We redid the entire build system because of how difficult the bootstrapping was originally

**Comment by confused-Techie** [comment]
Yeah I don't think this was a choice on our part and is a default from `electron-builder`
