### ISSUE TITLE
Pulsar - Manjaro Launch Failure

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#233]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

This is from an email I've received to the `admin@pulsar-edit.dev` account. And wanted to post this here to widen our troubleshooting availability. I'll also direct the user that has emailed to this issue here.

Below is an exact copy of what they sent:

---

I may be dumb but I couldn't find an issues tracker so I figured I'd email this.  I am an Atom user but since it's being deprecated I was excited to see Pulsar.  I installed pulsar-bin on the AUR and the message I got seems to be in Pulsar and something with a GTK theme file, not anything distro specific.  I have not run across this in Atom so I wanted to report the error it throws in case that's helpful:

/usr/bin/pulsar: line 166: 150299 Trace/breakpoint trap   (core dumped) nohup "$PULSAR_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

(pulsar:150299): Gtk-WARNING **: 01:53:21.473: Theme parsing error: gtk.css:586:25: 'solid' is not a valid color name
[150299:1209/015322.819681:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

I use Cinnamon and in the theme, there's the gtk-3.0 folder which this seems to correspond with the first error:
 background-color: solid;

I changed it from "solid" to "black" and then it omits the color error but I am not skilled enough to decipher the gpu issue?  If it helps, I'm running NVidia driver 525.60.11

/usr/bin/pulsar: line 166: 156633 Trace/breakpoint trap   (core dumped) nohup "$PULSAR_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[156633:1209/020208.201779:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

N/A

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

N/A

**Comment by Daeraxa** [comment]
`GPU process isn't usable. Goodbye.`

Isn't this just a case of needing `--no-sandbox` again?

**Comment by confused-Techie** [comment]
> `GPU process isn't usable. Goodbye.`
> 
> Isn't this just a case of needing `--no-sandbox` again?

Yes it looks like it is.

I've emailed them the fix, as well as further details linking to the original issues. I'm hoping they can get back to me to confirm it works before we close this one just in case

**Comment by jonnyabu1** [comment]
I will confirm the `--no-sandobox` works.  Sorry for not seeing the Github earlier.  My Google-fu wasn't working that night

**Comment by jonnyabu1** [comment]
For completeness sake -- Manjaro - package is from the AUR, pulsar-bin.  NVidia gtx 1080 driver 525.60.11.  Pulsar version 1.63.2022121407 x64

**Comment by confused-Techie** [comment]
@jonnyabu1 Happy to see you here and very glad to see that the issue is resolved!

Thanks so much for taking the time to get in contact us, regardless of how so, the email is there for a reason.

But in that case I'll go ahead and close this issue (since we do have a few others tracking the same issue) and appreciate the further details you've provided just to ensure we can get a proper fix for this one.

Thanks for contributing!
