### ISSUE TITLE
Build the editor with electron-builder or other modern alternative

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/pulsar#24]

**Comment by kaosine** [comment]
This one should be closed too, since we seem to be able to do this now?

**Comment by confused-Techie** [comment]
> This one should be closed too, since we seem to be able to do this now?

Yup sounds good to me. The editor can be reliably built on most OS's with `electron-builder`. While the same isn't true for all packages, that isn't addressed here, so lets get it closed.
