### ISSUE TITLE
Error on build in MacOS with Apple Sillicon

### ISSUE THREAD

**Issue by matpdev** [pulsar-edit/pulsar#242]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

On Run yarn build:apm, i get this error

env: python: No such file or directory
make: *** [Release/oniguruma.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/matpdev/Works/Pessoal/pulsar-my/ppm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 22.2.0
gyp ERR! command "/Users/matpdev/Works/Pessoal/pulsar-my/ppm/bin/node" "/Users/matpdev/Works/Pessoal/pulsar-my/ppm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/matpdev/Works/Pessoal/pulsar-my/ppm/node_modules/oniguruma
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@7.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Which OS does this happen on?

🍎 macOS

### OS details

MacOS X - Ventura 13.1 - M1

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1. yarn install
2. yarn build
3. yarn build:apm

**Comment by soupertonic** [comment]
It seems like `node-gyp` is unable to find a Python installation. Can you provide me the output of `which python`?

**Comment by matpdev** [comment]
python3 --version
Python 3.10.9

**Comment by soupertonic** [comment]
I need the output of `which python`. More specifically, I need to know whether or not it actually links to any Python binary/binaries. I did a clean install of Pulsar and ended up having the same issue as you do. Prior to solving the issue, the output of `which python` was nothing, blank. I think you're having the same issue.

**Comment by soupertonic** [comment]
If you don't care about what tool manages your Python installations then here's the way I solved the issue:
- Install `pyenv` via brew (`brew install pyenv`)
- Confirm installation by running `pyenv`
- Add `eval $(pyenv init --path)` in `.bash_profile` (Mac exclusive quirk, on Linux probably `.bashrc`)
- Run `pyenv install 3.10.0` (or your desired version)
- Run `pyenv global 3.10.0` (or the version you chose)
- Confirm installation by running `which python`

The output of `which python` should look something like this: `/Users/<USER>/.pyenv/shims/python`

**Comment by matpdev** [comment]
Its Works! Thanks!
