### ISSUE TITLE
Bump tree-sitter to modern version, and remove namespaced @atom from tree-sitter and packages that use it

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/pulsar#26]

**Comment by mauricioszabo** [comment]
This was already done with our update to Electron 12, right?

**Comment by confused-Techie** [comment]
> This was already done with our update to Electron 12, right?

I think we still have the same `tree-sitter` package since it's getting it from NPM. Which uses the tree-sitter package

**Comment by mauricioszabo** [comment]
Just checked, tree-sitter is the most recent, non-namespaced version.
