### ISSUE TITLE
No DevTools

### ISSUE THREAD

**Issue by ElectronicsArchiver** [pulsar-edit/pulsar#260]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The devtools won't open in pulsar,
no matter what flags I use or way
I try to open them ( keybinding ,
command palette , gui )

In my existing atom ( latest ) 
installation it still works however.

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Kubuntu 22.04

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Run pulsar with any - all of the following

- `--dev`
- `--safe`
- `--no-sandbox`

**Comment by ElectronicsArchiver** [comment]
I managed to get them to open by running Pulsar directly from it's executable:

```sh
/opt/Pulsar/pulsar --dev --no-sandbox
```

So something might be wrong with the script at

```
/usr/bin/pulsar
```

**Comment by confused-Techie** [comment]
Having to use `--no-sandbox` on just about every linux distro is currently a known issue, it just needs to be added to the script.

**Comment by ElectronicsArchiver** [comment]
@confused-Techie Yeah but it doesn't seem to work when I supply it to the pulsar command directly..
