### ISSUE TITLE
Update Check Failed

### ISSUE THREAD

**Issue by manngo** [pulsar-edit/pulsar#272]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When I try to check for updates via the Pulsar Menu, I get the following dialog:

![image](https://user-images.githubusercontent.com/3796633/209748923-fcfbfef7-d77d-4308-b86a-0a99bee65d0b.png)

I get the same problem if I try to check it via the About screen.

### Which OS does this happen on?

🍎 macOS

### OS details

macOS Ventura 13.1

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

As above: check for updates.

**Comment by confused-Techie** [comment]
Appreciate you contributing and submitting bug reports!

But currently Pulsar does not support automatic updates. And this is a known issue labeled on the [homepage of our Website](https://pulsar-edit.dev/#automatic-updates).

So I'll go ahead and close this one, but again thank you for contributing!

**Comment by manngo** [comment]
Ah. I misunderstood. Thanks
