### ISSUE TITLE
"About" release notes link to non-existent changelog/release notes on github

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#283]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Open the about page (Help > About) or `Application: About` on a non-tagged release (tested on latest Cirrus binary - presumably happens in dev but about package seems to be broken in dev entirely).

Click "Release notes" next to the version number, it will open a browser to a github tagged release that doesn't exist because it is using the timestamp as part of it.

`https://github.com/pulsar-edit/pulsar/releases/tag/v1.100.2022122803`

Seems to be from:

https://github.com/pulsar-edit/pulsar/blob/4e20a34082e730a6148821a50dc3561f6ea3382d/packages/about/lib/update-manager.js#L135-L137

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Linux Mint 21

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

From a Cirrus binary (not a tagged GH release):

- Help > About (or `Application: About`)
- Click "Release notes"
![image](https://user-images.githubusercontent.com/58074586/210157059-94e7c295-fb50-417f-baa8-61449802f52c.png)
- Link opens to page that does not exist because we don't create tags for every single CI binary
- https://github.com/pulsar-edit/pulsar/releases/tag/v1.100.2022122803

### Additional Information:

Atom seemingly had a number of ways of dealing with this due to its release channels such as ignoring entirely on dev etc.

A number of options we could look at:

- We find a way of seeing if this is a dev or CI binary and disable this entirely
- We leave it as it is, CI binaries wouldn't be expected to have this kind of feature
- We cut the version off before the datestamp so we always pull release notes for the actual main version. (v1.100.?)
- We remove the browser based version entirely and rely on internal pulsar changelog only

**Comment by confused-Techie** [comment]
I also had some suggestions which closely mirror those listed here, but I'll add just in case

* Before crafting the link it tries to figure out if it's on an Alpha build by the build number alone (Not a huge fan)
* Make it so all release versions will resolve, which could be possible by maintaining our own webpage for release notes, and that page could look up the PR for a built number automatically, and either link to it, or pull it's contents to display on the page
* Let it be broken for alpha builds. And we just recognize that as the intended functionality
* Remove it altogether

**Comment by Spiker985** [comment]
I assume this is still a problem for Cirrus builds (can confirm static releases are working, presumably due to 47711c8)?

**Comment by confused-Techie** [comment]
Looking at this again, now that we properly maintain a `CHANGELOG.md` file, what if we just direct to the `CHANGELOG.md` on GitHub if the version is super long, or if we can properly detect that it's a rolling release build?

**Comment by Daeraxa** [comment]
One issue with that is that we will start adding stuff into the changelog that might not actually be in that release which I would say is probably *less* desirable than not having it at all.

**Comment by confused-Techie** [comment]
Ah, you do make a really good point here.

So maybe the simplest solution, is to not open anything, and instead emit a notification that it's not supported on rolling releases?

**Comment by Daeraxa** [comment]
Well *in theory* changelog.md gets the unreleased changes added to it as they are made to the application right? Could we not just bundle that during the build?

**Comment by confused-Techie** [comment]
@Daeraxa Very much in theory yes. But still it may potentially show newer items. Unless we just want to open the changelog that's bundled (or start bundling it) and show that. Which I'm pretty sure you actually suggested before, but I'd very much be on board with that. Which honestly, if we have a bundled Changelog, we could start parsing and displaying that in the `welcome` changelog as well, giving us one less thing to keep updated

**Comment by confused-Techie** [comment]
So I know this one is a bit older, and I think I've found what may be the simplest fix we could do here.

While one day in the future bundling the changelog is the most complete solution, what we could do:

Is instead of returning the string `https://github.com/pulsar-edit/${releaseRepo}/releases/tag/${appVersion}` we could just return `https://github.com/pulsar-edit/${releaseRepo}/CHANGELOG.md#${appVersion}`

That way it just uses the anchor tag to link to a given version, this also means that if the version doesn't exist, instead of getting a 404 to a non-existent page, you instead are just linked to the top of the changelog, where you'll be able to see the `[Unreleases]` changelog notes.

**Comment by Daeraxa** [comment]
That makes a lot of sense, so, just in case I'm reading this wrong, would this be a global change for all releases? For the regular release this sounds like it would be the same as what we do with the Chocolatey repo?

I was about to say we could put in some logic to check the last part of the version but then re-read what you put where if there isn't a match for that anchor link then yeah, it will just go to the top of the list. This sounds like a pretty neat solution.

**Comment by confused-Techie** [comment]
@Daeraxa This is exactly what we do in chocolatey.

But yup, this change would effect Regular, Rolling, and Dev versions of Pulsar. But luckily should work for all of them.

Since if you are on the dev version or rolling, ideally the changes you have would be shown at the top of the file.

Of course there's the chance that an older rolling release would still show the top of the file, even if that's inaccurate, but for the vast majority of use cases this seems like a super simple fix, that should work 90% of the time. Plus it's a single line diff, so that's always fun
