### ISSUE TITLE
Pulsar is taking about 2 minutes to launch (portable)

### ISSUE THREAD

**Issue by D-Maxwell** [pulsar-edit/pulsar#287]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Launching the app is extremely long.

### Which OS does this happen on?

🪟 Windows

### OS details

WIN10

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Launch the app.

**Comment by confused-Techie** [comment]
Are you using the portable version? Or is this on the first install of the non-portable version.

Since it is a known issue that the Windows Portable takes quite some time to launch, but at least for me using the non-portable version it takes a comparable time to what Atom took to launch.

What's the version of the Pulsar installer used to do this?

**Comment by Sertonix** [comment]
This works as expected.
The portable version is a self extracting zip archive and therefore needs to do a bunch of stuff before pulsar can actually run.
If you consider this an issue it is an issue with electron-builder.

**Comment by confused-Techie** [comment]
Yeah I missed the note in the title about this being the portable version.

Which like mentioned by @Sertonix it's a self-extracting archive, and the only thing we could really do to reduce it's startup time would be to reduce what has to be extracted. Which we are already aware is an issue and is logged under #143 so to reduce duplicate issues from appearing I'll go ahead and close this one.

As always we do appreciate the contributions, and this is something we want to reduce, but there's only so much we can do without significant refactoring
