### ISSUE TITLE
Fix "command installer" specs

### ISSUE THREAD

**Issue by mauricioszabo** [pulsar-edit/pulsar#303]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Pulsar have a "command installer" that installs both `ppm` and `pulsar` in the PATH.

The problem is that the test (that resides here: https://github.com/pulsar-edit/pulsar/blob/master/spec/command-installer-spec.js) is **insanely** flaky. For example, it starts with:

```js
     apmBinPath = path.join(
       resourcesPath,
       'app',
       'apm',
       'node_modules',
       '.bin',
       'apm'
     );
```

This is not the path anymore that we use. So I commented them for now, and we need a way to actually test the **real command** instead

### Which OS does this happen on?

🍎 macOS

### OS details

Any

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

Run tests on CI

**Comment by confused-Techie** [comment]
This report is now bundled into a single issue #511
