### ISSUE TITLE
Git signing redirecting to atom.github.io

### ISSUE THREAD

**Issue by josharmenta** [pulsar-edit/pulsar#306]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Git signing in redirects to atom.github.io and then redirects again to the Atom unsupported notice. Cannot sign into git from the app, suggest the GitHub feature be fixed or removed.

### Which OS does this happen on?

🍎 macOS

### OS details

Ventura

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

Try to log into GitHub

**Comment by Daeraxa** [comment]
Thanks, we already have this logged here https://github.com/pulsar-edit/github/issues/7 in the github package repo, it is something we are aware of but thanks for logging it.

**Comment by confused-Techie** [comment]
This issue has been resolved in #415
