### ISSUE TITLE
Command Line MacOS Broken

### ISSUE THREAD

**Issue by bendrda** [pulsar-edit/pulsar#311]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Pulsar  : 1.100.0-beta
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0

After install, command line `pulsar-beta` results in an error `zsh: command not found: pulsar-beta`.
Looks like the link installed into `/usr/local/bin` points to `~/Applications/Pulsar.app/Contents/Resources/app/pulsar.sh`, whereas the script is installed to `~/Applications/Pulsar.app/Contents/Resources/pulsar.sh`.

### Which OS does this happen on?

🍎 macOS

### OS details

MacOS 12.6.1

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install Pulsar using dmg.
2. Open Terminal.
3. Run `pulsar-beta`.

**Comment by Daeraxa** [comment]
I think this is fixed in the latest binaries? Try one of the Cirrus ones instead - https://pulsar-edit.dev/download.html#cirrus-ci-binaries

**Comment by confused-Techie** [comment]
Not sure if we have handled this in recent binaries specifically.

But the major thing to note here, the dialog that instructs you that the commands "pulsar-beta" have been installed are incorrect. That dialog hasn't finished receiving rebranding. There is no command "pulsar-beta" the command will simply just be "pulsar".

@bendrda If you could try just running `pulsar` in your CLI and let me know if that works I'd really appreciate it!

**Comment by bendrda** [comment]
It's hard to say, since I did some workarounds on my system to fix the issue. I will say that pulsar-beta _was_ in my /usr/bin/local when I started, and just pointing to the wrong place. I ended up copying the pulsar.sh script down into the .../Pulsar.app/Contents/Resources/App folder to make it work.

**Comment by mauricioszabo** [comment]
This should indeed be fixed in the latest binaries - I personally checked for it.

But, the binary name should indeed be only `pulsar`

**Comment by rodw** [comment]
FYI for anyone else trying to act on @bendrda's workaround above

> I will say that pulsar-beta _was_ in my /usr/bin/local when I started, and just pointing to the wrong place. I ended up copying the pulsar.sh script down into the .../Pulsar.app/Contents/Resources/App folder to make it work.

It took me a moment to figure out where `pulsar.sh` could be found, but in my (macOS) case this comes down to:

```bash
cp /Applications/Pulsar.app/Contents/Resources/pulsar.sh /Applications/Pulsar.app/Contents/Resources/app/.
```

Per the thread above this problem should go away when the the dev changes migrate to a released version, but for the time being this fixed `pulsar-beta` for me when using the latest (currently only) 1.100.0-beta release.
