### ISSUE TITLE
Cog Button to access Settings when Title bar is (hidden | reduced)

### ISSUE THREAD

**Issue by D-Maxwell** [pulsar-edit/pulsar#313]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

I feel like there should be a button-image to access the settings quickly. Its absence is especially felt when the toolbar is as well.
Perhaps it could be located within the footer, as a simple looking cog in the bottom right corner, similarly to the sketch below :
![image](https://user-images.githubusercontent.com/98100481/211075697-82046071-5b8d-4ddf-ae94-fd1f1e43bf44.png)
> Here, I have intentionally reduced the opacity of the icon. It being filled, it looked brighter than the rest of the components in the footer. This may have also been caused by the lack of cleartype antialiasing.

### What benefits does this feature provide?

This would facilitate access to the settings, as it is currently under `File` in the toolbar. That is by no mean a choice to be contested (not by me, not my point), I simply think there should be more ways, and more obvious ones, yet discreet ones.

### Any alternatives?

Regardless of the state of the title bar, a settings button with an icon would look a lot cleaner. Perhaps it could even be toggled in the settings ?

**Comment by confused-Techie** [comment]
This does seem like a good idea tbh, may look at drafting something up when time permits

**Comment by Daeraxa** [comment]
Yeah I find myself going to the package management section most of the time myself to open it as its faster to navigate to. I think a button is a good idea.
