### ISSUE TITLE
editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function (python script)

### ISSUE THREAD

**Issue by LRydin** [pulsar-edit/pulsar#319]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Classic shift-Enter to run single line on python (Hydrogen) throws error.

### Steps to Reproduce

1. create any python file (.py) and attempt to run anything (e.g. `import os`)

**Expected behavior:**

run (equivalent to `hydrogen:run`)

**Actual behavior:**

throws error: editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function

### Versions

**Atom**: 1.100.0-beta x64
**Electron**: 12.2.3
**OS**: Ubuntu 22.10
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.16.3

### Stack Trace

Uncaught TypeError: editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function

```
At /home/leo/.pulsar/packages/Hydrogen/dist/utils.js:177

TypeError: editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function
    at Object.rowRangeForCodeFoldAtBufferRow (/packages/Hydrogen/dist/utils.js:177:36)
    at Object.findCodeBlock (/packages/Hydrogen/dist/code-manager.js:357:31)
    at run (/packages/Hydrogen/dist/main.js:258:35)
    at /packages/Hydrogen/dist/main.js:83:45)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:405:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:153:34)
```

### Commands

```
     -4:59.2.0 hydrogen:run-and-move-down (input.hidden-input)
     -4:59.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:18.7.0 hydrogen:run (span.syntax--keyword.syntax--control)
     -2:18.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -2:16 hydrogen:run-and-move-down (input.hidden-input)
     -2:16 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
Hydrogen 2.16.3 
```

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu 22.10 (Kernel: 5.19.17-051917-generic)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### Description

Classic shift-Enter to run single line on python (Hydrogen) throws error.

### Steps to Reproduce

1. create any python file (.py) and attempt to run anything (e.g. `import os`)

**Expected behavior:**

run (equivalent to `hydrogen:run`)

**Actual behavior:**

throws error: editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function

### Additional Information:

 - Reported also as a comment [here](https://github.com/pulsar-edit/pulsar/issues/197#issuecomment-1369274254).
 - mouse right click -> 'hydrogen' -> 'run' works fine as described in the comment above.
 - I have `atom` with hydrogen and it runs fine (thus python is correctly set up).

**Comment by mauricioszabo** [comment]
Nothing much we can do here - this should be fixed in Hydrogen package.

I'm not even sure what's supposed to be editor.**languageMode**, considering that the text editor never had this as a documented API...

**Comment by mauricioszabo** [comment]
Found the error - this condition is invalid as to get a version (parseFloat should not be used to get semantic versions or any version in general): https://github.com/nteract/hydrogen/blob/621cb9990705a19bc9f7d3d2f0d0819c23ce2295/lib/utils.tsx#L221

Please, ask for Hydrogen authors to fix this condition - we literally have nothing we can do in this situation, sorry...

**Comment by shr00mie** [comment]
> Found the error - this condition is invalid as to get a version (parseFloat should not be used to get semantic versions or any version in general): https://github.com/nteract/hydrogen/blob/621cb9990705a19bc9f7d3d2f0d0819c23ce2295/lib/utils.tsx#L221
> 
> Please, ask for Hydrogen authors to fix this condition - we literally have nothing we can do in this situation, sorry...

if that's the case, then why does it work when using the Packages -> Hydrogen -> Run via the Atom menu options? If it was a Hydrogen issue, wouldn't all attempts to run hydrogen code (run, run and next, run all) throw the same error, regardless of whether the action was initiated by keyboard shortcut or menu options?

**Comment by LRydin** [comment]
@mauricioszabo:
> If that's the case, then why does running code via Hydrogen work when executing via Packages -> Hydrogen -> Run from the Pulsar menu options?

This is exactly why I believe this is Pulsar-related and not Hydrogen related. How can it run with a right-click `hydrogen:run` but not with shift-Enter on the editor? (thanks @shr00mie).

**Comment by LRydin** [comment]
That's fair. I'll move this to Hydrogen then, to see what they make of it. Thanks again @mauricioszabo!

**Comment by mauricioszabo** [comment]
@LRydin I did a PR: https://github.com/nteract/hydrogen/pull/2162
