### ISSUE TITLE
Windows Taskbar only shows half of the icon

### ISSUE THREAD

**Issue by Intubun** [pulsar-edit/pulsar#320]
### Thanks in advance for your bug report!

- [ ] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [x] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [x] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [x] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [x] Have you checked you are on the latest release of Pulsar?

### What happened?

![image](https://user-images.githubusercontent.com/41478036/211204862-f7d6975c-3df6-443a-a45c-0933e51dff43.png)

Well... I dont think its supposed to be that way...

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10 Home

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Open the App and look in the Windows Task Bar

**Comment by Daeraxa** [comment]
Fixed in https://github.com/pulsar-edit/pulsar/commit/a324c9d8a71d842d760e116305a17e55e7383bbc

**Comment by Intubun** [comment]
thx
But I think the Binary on the Website should be updated...

**Comment by Daeraxa** [comment]
The cirrus binary should have that fix in it already as it will have been built as soon as that PR was merged.

**Comment by confused-Techie** [comment]
> thx But I think the Binary on the Website should be updated...

The binaries on the website will only ever grab the most recent builds of Pulsar, this included. We don't need to update anything.

Just make sure you grab our Cirrus CI Binaries when you download [from our website](https://pulsar-edit.dev/download.html#cirrus-ci-binaries).
