### ISSUE TITLE
Get Renovate bot running on this repository with a basic config

### ISSUE THREAD

**Issue by HonkingGoose** [pulsar-edit/pulsar#321]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

You have a Renovate bot configuration file, which is probably a left-over from the old Atom repository:

https://github.com/pulsar-edit/pulsar/blob/5420595b4a940c0356ab1014cb4b0669bed33c0f/.github/renovate.json#L1-L20

I recommend you use Renovate bot to get updates for your dependencies. I help maintain the documentation for Renovate, so obviously I like it best.

I can help you get Renovate bot running on this repository. 😉 

### What benefits does this feature provide?

Quote from the Renovate docs homepage: [^docs-homepage]

> Why use Renovate?
> 
> - Get pull requests to update your dependencies and lock files
> - Reduce noise by scheduling when Renovate creates PRs
> - Renovate finds relevant package files automatically, including in monorepos
> - You can customize the bot's behavior with configuration files
> - Share your configuration with ESLint-like config presets
> - Get replacement PRs to migrate from a deprecated dependency to the community suggested replacement (npm packages only)
> - Open source

One big feature is you can use Renovate's Dependency Dashboard issue [^dashboard-docs] to get an overview of all your dependencies and their pending/oopen updates.

[^docs-homepage]: https://docs.renovatebot.com/
[^dashboard-docs]: https://docs.renovatebot.com/key-concepts/dashboard/

### Any alternatives?

If you don't want to use Renovate, you can check out Dependabot [^dependabot] or Depfu [^depfu].

[^dependabot]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates
[^depfu]: https://depfu.com/

### Other examples:

Here's the Renovate bot in action on the official Renovate repository:

- https://github.com/renovatebot/renovate/issues/2958
- https://github.com/renovatebot/renovate/pull/19730

**Comment by HonkingGoose** [comment]
Dependabot is good as well. The biggest win is using a dependency management bot.

> The one concern I can really see here, and might end up being the case, is currently we have a lot of outdated dependencies, but even worse we have a lot of failing tests, and it can make it extremely difficult to trust tests when performing an upgrade to a dependency.

Updating old dependencies with flaky or broken tests is tricky. How about this then:

- Enable Renovate's Dependency Dashboard (it's on by default)
- Require dashboard approval for **all** updates

You then have a special issue which lists all your dependencies and their updates. You can select a checkbox in the special issue to get an update PR from Renovate for that dependency. Renovate calls this "the Dependency Dashboard Approval workflow". [^approval]

Once you've fixed your flaky/broken tests you can start automating dependency updates more:

- Let Renovate create `patch`/`minor` update pull requests automatically
- Keep requiring Dependency Dashboard approval for `major` updates
- _Optional:_ Allow Renovate to automerge dev dependencies like Prettier or ESLint if all tests pass

Dependabot must run at least once a month (`interval=monthly`) [^interval], and you don't get an dependency dashboard. So that's where Renovate is really different.

I'm happy to create a basic Renovate configuration with the Dependency Dashboard enabled, and the "Dependency Dashboard Approval Workflow".

[^approval]: https://docs.renovatebot.com/key-concepts/dashboard/#dependency-dashboard-approval-workflow
[^interval]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval

**Comment by confused-Techie** [comment]
This sounds really cool, and appreciate you being open to assist in creating a configuration for it.

How about this, since this change will likely affect many of our core contributors and would change the workflow I'll make a poll on our Discord to see what everyone thinks, and if approved, then we can move forward with your plan.

Which thanks for laying it out like you have and helping find ways to work around our limitations, your contributions are appreciated!

**Comment by HonkingGoose** [comment]
Did you manage to run the poll already? I'm curious what you guys voted. 😄

**Comment by HonkingGoose** [comment]
I'm testing Renovate on my fork. You can see the Dependency Dashboard in action here:

- https://github.com/HonkingGoose/pulsar/issues/1

This is the `renovate.json` file I'm using now:

```json5
{
  "extends": ["config:base", ":dependencyDashboardApproval"], // Default configuration + only get updates when requested via Dependency Dashboard
  "includeForks": true // You do not need this option, but I do, because I'm running Renovate on a fork :)
}
```

As you can see on my fork, Renovate has _not_ created any PRs. That's because I need to select the updates I want from the Dependency Dashboard issue.

Let me know what you think! 😉

**Comment by Spiker985** [comment]
Ironically enough, we probably *do* need the includeForks key, because a large portion of our repos are forked from Atom still

We need to contact GitHub (again?) to remove the upstream from quite a few of them

**Comment by confused-Techie** [comment]
Yeah @HonkingGoose this looks fantastic! I love the fact that it's just an issue. Especially love that it's able to find all the dependencies from our core packages as well!

Only downside I can even find is that updating a dependency that's in the core and a core package looks like it'd update both by clicking the checkbox? But at the very least it reports it so you could update one manually if you ever needed. But that seems unlikely.

So with this, and considering the way our vote carried out, might just be time to implement this in a PR.

Appreciate all the effort and following up on this

**Comment by HonkingGoose** [comment]
To get started with Renovate:

1. Read the [Installation instruction in the docs](https://docs.renovatebot.com/getting-started/installing-onboarding/) for a full overview.
2. I recommend installing the GitHub-app for Renovate, that's easiest to start with.
3. Select what repositories you want Renovate to run on: only `pulsar-edit/pulsar`, a few, or all of them 
4. Create a `renovate.json` file on the `pulsar-edit/pulsar` repository, put it in the root of the repository. Put this JSON in the file:
    ```json
    {
      "extends": ["config:base", ":dependencyDashboardApproval"],
      "includeForks": true
    }
    ```
5. When Renovate runs it creates the Dependency Dashboard issue.
6. Pin the Dependency Dashboard issue to your repository, so you can always find it. Read the [GitHub Docs about pinning an issue to your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) to learn how.
7. Now you can get updates from the Dependency Dashboard by selecting the checkbox for the updates.

If you get stuck, ask for help in this issue. 😉

**Comment by HonkingGoose** [comment]
> Only downside I can even find is that updating a dependency that's in the core and a core package looks like it'd update both by clicking the checkbox? But at the very least it reports it so you could update one manually if you ever needed. But that seems unlikely.

Are those _core_ and _core package_ files in different file paths? If yes, we can probably do something like this:

```json
{
  "packageRules": [
    {
      "description": "Group all dependencies from the core directory",
      "matchPaths": ["core/**"],
      "groupName": "Core dependencies"
    },
    {
      "description": "Group all dependencies from the core-packages directory",
      "matchPaths": ["core-packages/**"],
      "groupName": "Core packages dependencies"
    },
  ]
}
```

Here I'm using the `matchPaths` [^docs] config option in a `packageRules` array to configure what happens based on the location of each dependency.

I still recommend starting with the simplest config first to see what happens. You can always tune things later. 😄 

[^docs]: https://docs.renovatebot.com/configuration-options/#matchpaths

**Comment by HonkingGoose** [comment]
Hi @confused-Techie!

Congratulations on getting Renovate bot working! 🥳✨ 

I see Renovate already created some security PRs on this repository. Renovate always creates security PRs, even if you normally only get updates when requested from the Dependency Dashboard.

I hope you enjoy Renovate bot. 😄
