### ISSUE TITLE
Installation via Homebrew

### ISSUE THREAD

**Issue by foolioo** [pulsar-edit/pulsar#322]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Add [Homebrew](https://brew.sh/) formula for installing Pulsar, in the same spirit of [Atom formula](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/atom.rb)

### What benefits does this feature provide?

Streamline the installation process, rather than [manually download files and install them](https://pulsar-edit.dev/download.html#releases)

### Any alternatives?

NA

**Comment by Daeraxa** [comment]
We have a discussion here - https://github.com/pulsar-edit/.github/discussions/77 - about all of the different potential things we want to support but Homebrew is definitely one of the ones we will likely want to support.

**Comment by confused-Techie** [comment]
Are we good to go ahead and close this one, since it's being properly and more thoroughly discussed on our Discussions?

**Comment by Daeraxa** [comment]
Personally I'd say yes as we all know it is there and it is at least one way of putting it all in the same place unless we want to migrate it to an issue in the repo.

**Comment by confused-Techie** [comment]
> Personally I'd say yes as we all know it is there and it is at least one way of putting it all in the same place unless we want to migrate it to an issue in the repo.

Yeah I'm totally onboard with keeping everything organized in that discussion, it really does seem like the proper place to put this kind of information. So awesome, I'll go ahead and close this one, with use knowing it is there.
