### ISSUE TITLE
Linux mint package not working

### ISSUE THREAD

**Issue by vol4ikman** [pulsar-edit/pulsar#323]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

/usr/bin/pulsar: line 166:  6520 Trace/breakpoint trap   (core dumped) nohup "$PULSAR_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[6520:0109/211842.726531:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Linux Mint 21.1 Cinnamon

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Trying to run pulsar on linux mint.
====

System:
  Kernel: 5.15.0-57-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.5
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: TIMI product: RedmiBook 16 v: N/A serial: <superuser required> Chassis:
    type: 10 serial: <superuser required>
  Mobo: TIMI model: TM2003 v: V54E2 serial: <superuser required> UEFI: TIMI v: RMAIC6B0P0606
    date: 09/09/2020
Battery:
  ID-1: BAT0 charge: 40.6 Wh (90.0%) condition: 45.1/47.0 Wh (96.1%) volts: 15.2 min: 15.2
    model: SCUD R14B01W serial: <filter> status: Discharging
CPU:
  Info: quad core model: Intel Core i7-1065G7 bits: 64 type: MT MCP arch: Ice Lake rev: 5 cache:
    L1: 320 KiB L2: 2 MiB L3: 8 MiB
  Speed (MHz): avg: 1681 high: 3065 min/max: 400/3900 cores: 1: 1399 2: 3065 3: 1642 4: 1468
    5: 1232 6: 1336 7: 1264 8: 2043 bogomips: 23961
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Iris Plus Graphics G7 vendor: Xiaomi driver: i915 v: kernel ports: active: eDP-1
    empty: DP-1,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:8a52
  Device-2: NVIDIA GP107M [GeForce MX350] vendor: Xiaomi driver: nvidia v: 515.86.01 pcie:
    speed: 8 GT/s lanes: 4 bus-ID: 01:00.0 chip-ID: 10de:1c94
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 102
  Monitor-1: eDP-1-1 mapped: eDP-1 model: Chi Mei Innolux res: 1920x1080 dpi: 137
    diag: 407mm (16")
  OpenGL: renderer: NVIDIA GeForce MX350/PCIe/SSE2 v: 4.6.0 NVIDIA 515.86.01 direct render: Yes
Audio:
  Device-1: Intel Ice Lake-LP Smart Sound Audio vendor: Xiaomi driver: sof-audio-pci-intel-icl
    bus-ID: 00:1f.3 chip-ID: 8086:34c8
  Sound Server-1: ALSA v: k5.15.0-57-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ice Lake-LP PCH CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3
    chip-ID: 8086:34f0
  IF: wlp0s20f3 state: up mac: <filter>
Bluetooth:
  Device-1: Intel AX201 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 3-10:2 chip-ID: 8087:0026
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 3.0 lmp-v: 5.2
    sub-v: 237e
Drives:
  Local Storage: total: 476.94 GiB used: 43.06 GiB (9.0%)
  ID-1: /dev/sda vendor: Samsung model: MZNLH512HALU-00000 size: 476.94 GiB speed: 6.0 Gb/s
    serial: <filter>
Partition:
  ID-1: / size: 467.89 GiB used: 43.06 GiB (9.2%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 5.2 MiB (1.0%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: 49.0 C mobo: N/A gpu: nvidia temp: 46 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: apt: 2353
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  No active apt repos in: /etc/apt/sources.list.d/numix-ppa-jammy.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com vera main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 297 Uptime: 13m Memory: 15.43 GiB used: 2.32 GiB (15.0%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11 Client: Cinnamon v: 5.6.5 inxi: 3.3.13

===

The error:
`/usr/bin/pulsar: line 166:  6520 Trace/breakpoint trap   (core dumped) nohup "$PULSAR_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[6520:0109/211842.726531:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
`

**Comment by Daeraxa** [comment]
Is using the beta or the Cirrus binaries? This should be fixed in the latter.

**Comment by confused-Techie** [comment]
@Daeraxa is correct, this issue is fixed in our Alpha binaries, and is no longer an issue, it'll come to an update soon.
