### ISSUE TITLE
dpkg: creating hard link './opt/Pulsar/resources/pulsar.png': Invalid cross-device link

### ISSUE THREAD

**Issue by victort** [pulsar-edit/pulsar#324]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

downloaded `.deb` from https://pulsar-edit.dev/download.html#releases, tried to install it, but it's trying to make a **hard link** where it should probably be trying to make a **symlink** instead, and failing (probably because of filesystem layout being across multiple devices.)

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Debian 11/12 (Bookworm/sid)

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

```
# dpkg -i Linux.pulsar_1.100.0-beta_amd64.deb
(Reading database ... 540527 files and directories currently installed.)
Preparing to unpack Linux.pulsar_1.100.0-beta_amd64.deb ...
Unpacking pulsar (1.100.0-beta) ...
dpkg: error processing archive Linux.pulsar_1.100.0-beta_amd64.deb (--install):
 error creating hard link './opt/Pulsar/resources/pulsar.png': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
...
Errors were encountered while processing:
 Linux.pulsar_1.100.0-beta_amd64.deb
```

**Comment by mauricioszabo** [comment]
Can you please post your fstab here, or at least where everything is mounted?

I'm also on Linux, also using deb, and I'm not seeing this error.

One other thing, the install process is automated via electron-build, so this may be harder than it seems to fix...

**Comment by Spiker985** [comment]
Is this still occurring?

**Comment by confused-Techie** [comment]
Since we haven't heard back for a request of additional information for five months, I'm gonna go ahead and close this one out.
