### ISSUE TITLE
Pulsar crashes on NVIDIA

### ISSUE THREAD

**Issue by the-penguin-revo** [pulsar-edit/pulsar#328]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### Where is the URL that this occurs?

Downloaded from  https://pulsar-edit.dev/download.html#releases.

### What's your issue?

When I attempt to start Pulsar Text Editor, it crashes. It only crashes when I'm using the Nvidia GPU.

Here is the terminal  crash data:

`/usr/bin/pulsar:`` line 166: 15964 Trace/breakpoint trap   (core dumped) nohup "$PULSAR_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[15964:0111/000241.089331:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.`

I've attached my GPU information and other relevant screenshots.

![Screenshot from 2023-01-11 00-20-06](https://user-images.githubusercontent.com/52248011/211733008-294a722c-e585-461f-9763-00baf6d223bb.png)
![Screenshot from 2023-01-11 00-20-25](https://user-images.githubusercontent.com/52248011/211733009-5c89183c-6e45-4900-9e5c-a5449954704b.png)
![Screenshot from 2023-01-11 00-28-59](https://user-images.githubusercontent.com/52248011/211733998-57b8e94c-b813-4d87-9dbe-2190b445c5ba.png)

### Which OS/Browser/Version does this happen on?

OS Version: Pop OS 22.04

![Screenshot from 2023-01-11 00-24-02](https://user-images.githubusercontent.com/52248011/211733054-f3bb2a19-e7f3-447e-8560-5b6e3a40501b.png)

### Steps to Reproduce/Additional Details:

Crashes on startup.

**Comment by confused-Techie** [comment]
I appreciate the bug report, and the contribution. 

But this issue is resolved on our Alpha builds (Available just lower on the downloads page where it says `Cirrus CI`.)

These fixes will be available in our soon coming next beta release.

But at this point since we have closed many of these issues, maybe we should just leave this one up until our release to avoid the future duplicates.

So if you'd like you can wait until the next release and continue running your current version of Pulsar, ensuring to start the application from the CLI with `pulsar --no-sandbox`.
Or you can download the latest alpha build from our downloads page and have this issue resolved automatically.

Thanks again for the contribution!

**Comment by the-penguin-revo** [comment]
> I appreciate the bug report, and the contribution.
> 
> But this issue is resolved on our Alpha builds (Available just lower on the downloads page where it says `Cirrus CI`.)
> 
> These fixes will be available in our soon coming next beta release.
> 
> But at this point since we have closed many of these issues, maybe we should just leave this one up until our release to avoid the future duplicates.
> 
> So if you'd like you can wait until the next release and continue running your current version of Pulsar, ensuring to start the application from the CLI with `pulsar --no-sandbox`. Or you can download the latest alpha build from our downloads page and have this issue resolved automatically.
> 
> Thanks again for the contribution!

Thank you I installed the Alpha and it works perfectly. Thank you
