### ISSUE TITLE
Ctrl+P is not working

### ISSUE THREAD

**Issue by waveletboy** [pulsar-edit/pulsar#329]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

ctrl+p the fuzzy finder is always stuck as indexing project (0).

Version:
=========
C:\Users\xxx\AppData\Local\Programs\pulsar>
Pulsar  : 1.100.2023011007
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0

Console output:
================
C:\Users\xxx\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js
(anonymous)	@	C:\Users\msa20\AppDa…asar\src\task.js:78
(anonymous)	@	C:\Users\msa20\AppDa…sar\src\task.js:156
simpleDispatch	@	VM198 C:\Users\msa20…\dist\emitter.js:64
emit	@	VM198 C:\Users\msa20…dist\emitter.js:257
(anonymous)	@	C:\Users\msa20\AppDa…asar\src\task.js:98
emit	@	events.js:315
emit	@	internal/child_process.js:903
processTicksAndRejections	@	internal/process/task_queues.js:81

### Pulsar version

1.100.2023011007

### Which OS does this happen on?

🪟 Windows

### OS details

22H2 (OS Build 22621.1105)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Start Pulsar
2. Load files into project
3. press ctrl+p to open file

Actual result:
Cannot open any file because it is stuck in indexing project.
![Screenshot 2023-01-15 204745](https://user-images.githubusercontent.com/8904471/212588015-8285ad77-2597-4084-bc04-d2f01b115f4c.png)

**Comment by matt-horwood-mayden** [comment]
I had the same issue on my mac with 1.100, try the new 1.101 version. Testing on mac and nwo works.

**Comment by confused-Techie** [comment]
> I had the same issue on my mac with 1.100, try the new 1.101 version. Testing on mac and nwo works.

I was hoping the same would be true for Windows on the latest release. But unfortunately that's not the case.

Pulsar 1.101.0-beta on Windows 10 22H2 still presents this same issue.

Still showing only a stack trace with no proper error message:

```
C:\Users\<user>\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js

(anonymous) @ C:\Users\<user>\AppData\Local\Programs\pulsar\resources\app.asar\src\task.js:78
(anonymous) @ C:\Users\<user>\AppData\Local\Programs\pulsar\resources\app.asar\src\task.js:156
simpleDispatch @ VM198 C:\Users\<user>\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:64
emit @ VM198 C:\Users\<user>\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:257
(anonymous) @ C:\Users\<user>\AppData\Local\Programs\pulsar\resources\app.asar\src\task.js:98
emit @ events.js:315
emit @ internal/child_process.js:903
processTicksAndRejections @ internal/process/task_queues.js:81
```

**Comment by mauricioszabo** [comment]
Testing on Wine, I'm seeing the following error:

```
internal/fs/utils.js:307 Uncaught Error: EINVAL: invalid argument, lstat 'Z:\'
```

The smallest offending code is:

```js
const fs = require('fs-plus')
fs.realpathSync('Z:\\Users')
```

Basically it doesn't like to do a `fstat` on `Z:\`. I'm not sure what happens on Windows itself...

**Comment by automagisch** [comment]
Did anyone find a solution on this issue? I am running into the same error but I have no way to seem to fix it. Along with this issue, my packages won't show up in settings too now. 

In my case, I am having a new folder with the same name as the previous one, it got deleted and readded, and there was a git repository initialized in it. Could it be some caching bug?

**Comment by confused-Techie** [comment]
So I was looking into this last night, and something really interesting, is that locally run dev Pulsar this works!

As in if you download the repo and use:

```bash
> yarn install
> yarn build
> yarn start
```

Then CTRL + P actually properly indexes, so there is something a bit funky going on here that we have to take a look at. But that ideally means this isn't something truly broken, just something a little off. Which as far as I can tell it'd be within the `Tasks` API or within `fuzzy-finder`

**Comment by mauricioszabo** [comment]
I think this was fixed some time ago, when we found out that Windows builds where not generating the right binaries, right?

**Comment by confused-Techie** [comment]
@mauricioszabo You were totally right! Looks like I was doing testing with the chocolatey 1.103.0 build by mistake, CTRL + P does in fact work now on 1.106.0!

![image](https://github.com/pulsar-edit/pulsar/assets/26921489/a5de2d2a-285d-45c2-809f-70a01829a232)

I'll go ahead and close this one
