### ISSUE TITLE
Application: Open License command doesn't work

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#339]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Running command `Application: Open License` (or Help > View License or Help > About Pulsar > License which both use the same command) simply opens a blank "LICENSE.md" file in the editor.

The command itself is looking for a LICENSE.md file in the resource path:

https://github.com/pulsar-edit/pulsar/blob/c95cc8ac6b455c94c3b33cc2f3c40ddcd4274315/src/main-process/atom-application.js#L702-L705

But this does not appear to be present (on Windows at least but need to check for Linux etc.).

Checking the resource path in the dev tools (on a default Windows install) is `C:\Users\<username>\AppData\Local\Programs\Pulsar\resources` which only has:

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23/01/2023     09:42                app
d-----        23/01/2023     09:43                app.asar.unpacked
-a----        19/01/2023     03:27      504557524 app.asar
-a----        19/01/2023     03:27         107520 elevate.exe
-a----        19/01/2023     03:27          26971 pulsar.ico
-a----        19/01/2023     03:27         139808 pulsar.png
-a----        19/01/2023     03:27           5330 pulsar.sh
```

I'm guessing Atom would build their binaries with a copy of the repo LICENCE.md in the resource path but our current build method doesn't do it.

I had seen this behaviour before on Linux but put it down to running the dev build rather than a prebuilt binary.

### Pulsar version

1.101.2023011903

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Use any action to execute `Application: Open License` and note that it creates an empty "LICENSE.md" buffer instead of opening the licence file.

**Comment by Spiker985** [comment]
Should be just as simple as adding the file to our `electron-builder` config as an include
