### ISSUE TITLE
Uncaught errors still show Atom instead of Pulsar

### ISSUE THREAD

**Issue by wesley5040** [pulsar-edit/pulsar#347]
### Thanks in advance for your bug report!

- [ ] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [ ] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [ ] Have you checked you are on the latest release of Pulsar?

### What happened?

Uncaught error message still shows all Atom branding, and possibly linked to the Atom repo (sorry I didn't think to check, and I've since closed it, if I get a new one I'll update this issue).  The thing that caused the error is [#134](https://github.com/pulsar-edit/pulsar/issues/134).

![error message image](https://user-images.githubusercontent.com/18060360/214753158-5ec5a8c5-99fb-4515-98b4-2f700fcee09d.jpeg)

### Pulsar version

1.100.0-beta

### Which OS does this happen on?

🍎 macOS

### OS details

macOS 13

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Do something that will produce an uncaught error (for we it was a "Cannot decorate a destroyed marker").

**Comment by mdibella-dev** [comment]
This bug belongs to https://github.com/pulsar-edit/notifications

**Comment by wesley5040** [comment]
Turns out the button just does nothing.

**Comment by mdibella-dev** [comment]
> Turns out the button just does nothing.

A fix for this issue is still under review.

**Comment by confused-Techie** [comment]
The fix for this issue has now been merged into the `notifications` repo. All that is left is to go ahead and bundle (or bump) the version used in Pulsar and we can close this out.
