### ISSUE TITLE
Tabs package: right-clicking on a tab does not add a `right-clicked` class

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/pulsar#349]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

[This pull request](https://github.com/atom/tabs/pull/531) made it so that right-clicking on a tab no longer adds a `right-clicked` class. The author notes that they regarded this behavior to be “unused,” but the [Zentabs](https://github.com/ArnaudRinquin/atom-zentabs) package relies on this behavior for its “Pin tab” and “Unpin tab” commands. It uses `.right-clicked` to identify which tab was right-clicked and trace it back to its associated editor pane.

I'm treating this as a bug because Pulsar allows a package to add commands to a tab's context menu, which means that those commands need some way to figure out which tab they were invoked from. There's no other obvious way that I can see, and if Pulsar restores the `.right-clicked` behavior, it will fix Zentabs (and other packages, probably) without their needing to push out an update.

I will be happy to contribute this fix myself if need be, but I'm opening this issue because I've not yet set up my local environment to do so.

### Pulsar version

1.101.0-beta

### Which OS does this happen on?

🍎 macOS

### OS details

11.7.2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open the inspector and inspect a tab element.
2. Right-click on that tab.
3. Observe that no classes are added to the `li` element that represents the tab.

**Comment by abirhasan132** [comment]
#349

**Comment by abirhasan132** [comment]
#349
