### ISSUE TITLE
Git Discard changes doesnt work

### ISSUE THREAD

**Issue by mhzawadi** [pulsar-edit/pulsar#350]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I wan to discard changes to my Git repo

### Pulsar version

1.101.0-beta

### Which OS does this happen on?

🍎 macOS

### OS details

13.2 (22D49)

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1. open a git repo
2. edit a bunch of files
3. right click to discard them

### Additional Information:

```
root-controller.js:805 Uncaught (in promise) Error
    at new GitError (git-shell-out-strategy.js:36)
    at git-shell-out-strategy.js:341
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93)
GitError @ git-shell-out-strategy.js:34
(anonymous) @ git-shell-out-strategy.js:341
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
discardWorkDirChangesForPaths @ root-controller.js:805
discardChanges @ staging-view.js:447
(anonymous) @ staging-view.js:320
handleCommandEvent @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/command-registry.js:405
dispatch @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/command-registry.js:292
dispatchContextMenuCommand @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/atom-environment.js:1607
outerCallback @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/application-delegate.js:332
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
root-controller.js:805 Uncaught (in promise) Error
    at new GitError (git-shell-out-strategy.js:36)
    at git-shell-out-strategy.js:341
    at processTicksAndRejections (internal/process/task_queues.js:93)
GitError @ git-shell-out-strategy.js:34
(anonymous) @ git-shell-out-strategy.js:341
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
discardWorkDirChangesForPaths @ root-controller.js:805
discardChanges @ staging-view.js:447
(anonymous) @ staging-view.js:320
handleCommandEvent @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/command-registry.js:405
dispatch @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/command-registry.js:292
dispatchContextMenuCommand @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/atom-environment.js:1607
outerCallback @ /Applications/Pulsar.app/Contents/Resources/app.asar/src/application-delegate.js:332
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
```

**Comment by mhzawadi** [comment]
This looks to be fixed, good work all

**Comment by confused-Techie** [comment]
> This looks to be fixed, good work all

Thanks for keeping us updated! Glad to see it's working now!
