### ISSUE TITLE
Could not get code signature for running application

### ISSUE THREAD

**Issue by SilentGlasses** [pulsar-edit/pulsar#360]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Was checking for updates to ensure I was getting the latest packages and these or any other changes to the editor and got the error in the title.

```
Could not get code signature for running application
```

I was getting some errors in the `Settings` -> `Install` tab when looking for packages which led to me doing the above. 

Not sure what happened but the `Install` errors went away after a while but this error persists.

I have ensured that I ran the `xattr -cr /Applications/Pulsar.app/` command after install and prior to launching the app.

### Pulsar version

1.101.0-betax64

### Which OS does this happen on?

🍎 macOS

### OS details

macOS Monterey, 12.6.3

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Launch App
2. Click `About Pulsar`

### Additional Information:

![Screen Shot 14](https://user-images.githubusercontent.com/22822565/215352285-9c5e6a26-eac0-424d-9ad0-c661ed02d0bc.png)

**Comment by SilentGlasses** [comment]
Under `Show more` it shows this:

* Electron: `12.2.3`
* Chrome: `89.0.4389.128`
* Node: `v14.16.0`

**Comment by confused-Techie** [comment]
This is a bizarre error, since obviously it's not signed. I almost wonder if the checking for updates process was started somehow and errored out on that step.

Although ideally we will be signed on MacOS soon enough with #346

**Comment by CatPerson136** [comment]
I will take a look at this soon.

**Comment by CatPerson136** [comment]
> ### Thanks in advance for your bug report!
> 
>     * [x]  Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
> 
>     * [x]  Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
> 
>     * [x]  Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
> 
>     * [x]  Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
> 
>     * [x]  Have you checked you are on the latest release of Pulsar?
> 
> 
> ### What happened?
> 
> Was checking for updates to ensure I was getting the latest packages and these or any other changes to the editor and got the error in the title.
> 
> ```
> Could not get code signature for running application
> ```
> 
> I was getting some errors in the `Settings` -> `Install` tab when looking for packages which led to me doing the above.
> 
> Not sure what happened but the `Install` errors went away after a while but this error persists.
> 
> I have ensured that I ran the `xattr -cr /Applications/Pulsar.app/` command after install and prior to launching the app.
> ### Pulsar version
> 
> 1.101.0-betax64
> ### Which OS does this happen on?
> 
> apple macOS
> ### OS details
> 
> macOS Monterey, 12.6.3
> ### Which CPU architecture are you running this on?
> 
> 64-bit(x86_64)
> ### What steps are needed to reproduce this?
> 
>     1. Launch App
> 
>     2. Click `About Pulsar`
> 
> 
> ### Additional Information:
> 
> ![Screen Shot 14](https://user-images.githubusercontent.com/22822565/215352285-9c5e6a26-eac0-424d-9ad0-c661ed02d0bc.png)

I will take a look at this, seems to be weird.### ###

**Comment by Daeraxa** [comment]
There are loads of prior example of this due to electron updater and squirrel.mac. Honestly I don't think there is much to look into until 1) we get the binaries signed and 2) we have some description of auto-update idea in mind

**Comment by SilentGlasses** [comment]
Thanks all for peeking into this issue.  I"ll wait for things to take their course.  This is not a deal breaker nor a blocker for me.

Thanks for the beautiful work to keep this editor alive.   I've been an Atom user for years, was looking for a replacement editor, and just found Pulsar.  My search is over.

**Comment by SilentGlasses** [comment]
I guess I did not dig enough in the settings prior to opening this. It does state that this feature *is not* working. I'll close this out as it's a known item.
![Screen Shot 19](https://user-images.githubusercontent.com/22822565/215558369-0d910bb3-e8d7-46e3-b080-1be5c306224d.png)

**Comment by SilentGlasses** [comment]
Also, opening a file by clicking on it from the project bar doe not take you to that tab, it just stays on the current one.

**Comment by Daeraxa** [comment]
I knew making that change to that setting would have a benefit one day :P.

Yeah, automatic updates are one of those things we would like but we have a few steps to go first, including how we even want to handle releases/release schedules.
