### ISSUE TITLE
Tabs not functioning as expected

### ISSUE THREAD

**Issue by SilentGlasses** [pulsar-edit/pulsar#363]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

In Atom, if you clicked on files and did not make changes, clicking on a new file just replaced the tab of the last file.  Current Pulsar just keeps opening new tabs for each file that is clicked. Also, opening a file by clicking on it from the project bar does not take you to that tab, it just stays on the current one.

### What benefits does this feature provide?

Less clicking to maintain tabs if you are only looking files over and not needing to keep them open when you go to another file. I use that when building new pages that need to link to information on other pages so I can see the contents and then move to another page without having to then go back and close multiple tabs.

### Any alternatives?

No alternatives that I can think of that don't involve manual clicking.

### Other examples:

Atom does/did this well as seen in this gif:

![Atom_Tabs_Demo](https://user-images.githubusercontent.com/22822565/215556639-df0aa921-a0fc-46d4-96e1-d16b21bbdd9f.gif)

**Comment by SilentGlasses** [comment]
I'm thinking the `Allow Pending Pane Items` should do it based on what's explained in `Settings` -> `Core Settings` but it does not.

![Screen Shot 18](https://user-images.githubusercontent.com/22822565/215557679-98c4e5eb-a7b3-45cb-bddf-413091b9a527.png)

**Comment by SilentGlasses** [comment]
Also, opening a file by clicking on it from the project bar doe not take you to that tab, it just stays on the current one.

**Comment by Daeraxa** [comment]
I don't see this on the latest commit on Linux. If I single click a file it opens a tab with the title in italics to show it is pending. If I click another file then that tab changes to the new one. If I double click one then it changes to normal text in the title and the active light thing turns on.

**Comment by confused-Techie** [comment]
Echoing what @Daeraxa has said, this isn't an intentional change and is rather a bug. Which then we would need to know what version of Pulsar this is, and what Operating System you are on, otherwise without those it's near impossible to troubleshoot.

**Comment by SilentGlasses** [comment]
Awesome, thanks for the response and explanation...

I am on macOS:

```
OS: macOS 12.6.3 21G419 x86_64 
Kernel: 21.6.0 
Shell: zsh 5.8.1 
CPU: Intel i7-9750H (12) @ 2.60GHz 
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M 
Memory: 18298MiB / 32768MiB
```

Pulsare ver: 1.101.0-beta

I have tried safemode and the other research steps.

**Comment by SilentGlasses** [comment]
I have re-installed it from scratch already as well.

**Comment by confused-Techie** [comment]
I'd also recommend if possible, open the Dev Pane when opening some files and see if it's logging any errors at all

**Comment by wesley5040** [comment]
> @SilentGlasses Thanks a ton for the information! Since I don't have access to a Mac I'll see if we can get anyone to test this out and try to collect any further info

Seems to work as expected for me, including disabling the setting turning it off (doesn't do preview) and back on (does do preview again).  macOS 10.15.5 (1.101.0-beta) and macOS 13.? (1.100.0-beta)

**Comment by confused-Techie** [comment]
Wonder if this is really down to that specific version of MacOS? I wouldn't think so, but it's not unheard of for us to have some version of Chromium on Operating Systems that has a bug or slight change from a version to another. But especially considering this works on Atom of that version I wouldn't imagine it's that. This one seems a bit bizarre.

Do you possibly have any additional packages installed that attempt to manage tabs?

**Comment by DeeDeeG** [comment]
Hmm. I just tried this and it's working normally for me, as folks have described above.

(Single click opens the file into the tab bar, but it will go away if I click another file, double-click "pins" the file's tab to the tab bar.)

I'm testing this on macOS 10.15.7, same results with the Beta (1.101.0-beta) and the most recent Cirrus binary (1.101.2023012900).

---

I wonder if it still happens if you back up/rename your `~/.pulsar` data/config folder to something else (and potentially also backup/rename `~/Library/Application\ Support/Pulsar`) and start fresh?

That second dir is a more browsery/Chrome-y user data/config folder -- pretty much looks like how Chrome stores its stuff, which makes sense as Electron includes Chromium. I notice it stores the project history, maybe that project history ata is corrupted, and it's interfering with stuff... ?

**Comment by Meadowsys** [comment]
works fine for me! admittedly have not used pulsar extensively though (other than opening various versions to test), so the installation is likely still clean. Testing this using macOS Ventura 13.2 (public beta), on Apple Silicon, using the signed binary produced from the macos signing PR.

**Comment by SilentGlasses** [comment]
Sorry for the delay, been busy. Will give this a try tomorrow and get back to you.

**Comment by SilentGlasses** [comment]
Sorry for the delay, it's working now.  Thanks to everyone that jumped in to help me.
