### ISSUE TITLE
Application icon visual error on macOS

### ISSUE THREAD

**Issue by Jesse-Cooper** [pulsar-edit/pulsar#364]
### Thanks in advance for your bug report!

- [x] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I've seen that in a previous issue the icon was fixed to remove this visual error, however it still remains on macOS (intel) where I believe I've narrowed it down to [this](https://github.com/pulsar-edit/pulsar/blob/master/resources/app-icons/beta.png) file. It is a 1028x1028 image which I believe all macOS applications use. 

Here is how it looks on the computer:

<img width="80" alt="Screenshot 2023-01-31 at 10 50 33 am" src="https://user-images.githubusercontent.com/82210929/215622986-cb3f2ce8-d2c9-4950-8ef0-eee527d6307f.png">

### Pulsar version

1.101.0-beta

### Which OS does this happen on?

🍎 macOS

### OS details

13.2 (22D49)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install Pulsar
2. It is the application icon

**Comment by Meadowsys** [comment]
Can confirm. I did bring this up in the discord server before, someone (can't remember who) said it was because the icon was cropped out of a larger image, and that it was only temporary until the artist provides the individual icons. Can't remember if it was supposed to be fixed, though

**Comment by Jesse-Cooper** [comment]
Note, there may be other icon files with the same visual issue. The file linked is the image I believe is causing this specific error.

**Comment by Daeraxa** [comment]
Yeah I thought this one had been solved but maybe that was just Linux icons. We still haven't decided if we want to use a single unified icon or if we want to make a macOS squircle one.

**Comment by Meadowsys** [comment]
As a macos user I would be leaning towards the latter heheh >.>

**Comment by Digitalone1** [comment]
The icon in the open post is the PNG icon that has an issue and it was showing the same way on Arch in the previous release (just because the AUR packager fixed the wrong path in the installation script, otherwise it was not shown as it happened on other distros).

Linux icons were fixed, but I though you fixed also the icons for other platform.

**Comment by Digitalone1** [comment]
This is the icon with the visual issue:

https://github.com/pulsar-edit/pulsar/blob/master/resources/app-icons/beta.png

Which at the moment is only used on mac.

https://github.com/pulsar-edit/pulsar/blob/master/script/electron-builder.js#L178

Windows uses the ico format and Linux has their own because of the special way electron-builder has to construct icon paths on Linux. 

The only thing to do is to clean that PNG one. Maybe replacing with the following:

https://github.com/pulsar-edit/pulsar/blob/master/resources/pulsar.png

**Comment by mdibella-dev** [comment]
Based on the cleaned PNG file, I took the liberty of creating a customized app icon using the Apple Human Interface Guidelines (HIG) template file. 

![icon-template](https://user-images.githubusercontent.com/77158987/216831706-5b0fbc0b-2a7c-4883-a46f-b214f75fb8a4.jpg)

Attached is the ICNS file (zipped):

[pulsar.icns.zip](https://github.com/pulsar-edit/pulsar/files/10611543/pulsar.icns.zip)

**Comment by mdibella-dev** [comment]
Created a new file, based on the symbol graphic @confused-Techie provided.

![Template---Icon---App](https://user-images.githubusercontent.com/77158987/216938287-f6fc7d77-c86a-46e6-891f-59a7033cafda.jpg)

[beta.icns.zip](https://github.com/pulsar-edit/pulsar/files/10661702/beta.icns.zip)

**Comment by SilentGlasses** [comment]
Nice work with the icons @mdibella-dev ..

Ps, if anyone wants to use it on their current install...

* Unzip the file
* Double-click the `beta.icns` to open it in Preview
* From the left sidebar, right-click on the one you want then select `Export As`
* Browse to Applications and locate the Pulsar app
* Right-click on the app and click `Get Info`
* Drag and drop the exported png file on the small Pulsar icon in the top left of the window
![Screen_Shot_62](https://user-images.githubusercontent.com/22822565/217676671-9b9cd332-982a-4547-b563-6a7d6dfd9e6a.png)
.

**Comment by Meadowsys** [comment]
> Ps, if anyone wants to use it on their current install...

#372's CI binaries also have the icon, is another option

**Comment by mdibella-dev** [comment]
> > Ps, if anyone wants to use it on their current install...
> 
> #372's CI binaries also have the icon, is another option

Thanks for the hint. Looks great in my opinion.

![Ohne Titel-2](https://user-images.githubusercontent.com/77158987/217754437-4478b621-faa5-4e4a-a412-187fe6bfbbce.jpg)
![Ohne Titel-1](https://user-images.githubusercontent.com/77158987/217754441-89eb9c98-cc9f-4cc3-9fd1-903d3ab06be0.jpg)

**Comment by aphive** [comment]
> > Ps, if anyone wants to use it on their current install...
> 
> #372's CI binaries also have the icon, is another option

True, not everyone knows how to use the binaries tho ...  Lot's of n00bs still running around :)

**Comment by Meadowsys** [comment]
Hrm, maybe I should adapt my downloader thingie (that I made for atom-community back when we were still active there) to Pulsar's infra. ~~but this is getting a little off topic :p~~

**Comment by mdibella-dev** [comment]
In my opinion, the issue has been resolved with the merge and can thus be closed.

**Comment by Meadowsys** [comment]
I think so too!
