### ISSUE TITLE
Problem with autocomplete on javascript files - DOM

### ISSUE THREAD

**Issue by kurotom** [pulsar-edit/pulsar#379]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I am transitioning from Atom to Pulsar, in JavaScript files the autocompletion does not work, for example, I do not get suggestions when I enter `window` or any other line to handle the *DOM*. Please help.

It does work in the JavaScript language itself, but doesn't show support for the DOM.

I downloaded Pulsar from official page, installed it using `dnf`, OS installation is fresh.

### Pulsar version

Pulsar  : 1.101.0-beta

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 36

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Create or open a JavaScript (.js) file.
2. Write some line, for example, *window*
3. It does not show any suggestions for DOM.

### Additional Information:

Pulsar  : 1.101.0-beta
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0

**Comment by Daeraxa** [comment]
I can't see any difference in behaviour between Pulsar and Atom 1.60.0. Was this provided by a package you had installed?

**Comment by confused-Techie** [comment]
Yeah @Daeraxa correct me if I'm wrong, but `language-javascript` doesn't provide any completions for DOM elements like `window` or `document`.

And I can't locate any of our other non-core packages that do provide this

**Comment by kurotom** [comment]
No problem, below is the list of installed packages.

```
Built-in Atom Packages (92)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.66.0
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.9
├── autocomplete-plus@2.42.4
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.1
├── bookmarks@0.46.0
├── bracket-matcher@0.92.0
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.220.1
├── fuzzy-finder@1.14.3
├── github@0.36.13
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.1
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2
├── notifications@0.72.1
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.11
├── snippets@1.6.1
├── spell-check@0.77.1
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.4
├── tabs@0.110.2
├── timecop@0.36.2
├── tree-view@0.229.1
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.8
├── wrap-guide@0.41.0
├── language-c@0.60.20
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0
├── language-css@0.45.4
├── language-gfm@0.90.8
├── language-git@0.19.1
├── language-go@0.47.3
├── language-html@0.53.1
├── language-hyperlink@0.17.1
├── language-java@0.32.1
├── language-javascript@0.134.2
├── language-json@1.0.5
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.48.1
├── language-property-list@0.9.1
├── language-python@0.53.6
├── language-ruby@0.73.0
├── language-ruby-on-rails@0.25.3
├── language-rust-bundled@0.1.1
├── language-sass@0.62.2
├── language-shellscript@0.28.2
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.4
├── language-xml@0.35.3
└── language-yaml@0.32.0

Community Packages (14) /home/USER/.pulsar/packages
├── atom-live-server@2.3.0
├── atom-ternjs@0.20.0
├── autocomplete-java@1.2.7
├── autocomplete-python@1.17.1
├── autocomplete-sql@0.5.0
├── busy-signal@2.0.1
├── hyperclick@0.1.5
├── intentions@2.1.1
├── linter@3.4.0
├── linter-javac@1.10.0
├── linter-python@3.1.2
├── linter-ui-default@3.4.1
├── minimap@4.40.1
└── react@0.18.0
```

**Comment by Spiker985** [comment]
It's non-core, but I believe generic-lsp comes with a default handler for
javascript/typescript which should provide auto complete for such elements

No grammar by itself will ever really provide those as they're largely
dynamic

**Comment by savetheclocktower** [comment]
Never used it myself, but I'm assuming it was [atom-ternjs](https://web.pulsar-edit.dev/packages/atom-ternjs) that provided those autocompletions. Did you migrate your config file from Atom? If not, it might just need some settings changed.

**Comment by kurotom** [comment]
I didn't migrate anything, I did a clean install of Pulse ide

**Comment by savetheclocktower** [comment]
<img width="315" alt="Screen Shot 2023-02-12 at 3 45 07 PM" src="https://user-images.githubusercontent.com/3450/218344422-cccdfbf3-1547-459c-af5f-373eb3dfd824.png">

Looks like it's unchecked by default. Go to the list of packages in settings, find `atom-ternjs`, click on <kbd>Settings</kbd>, then check that box.

**Comment by kurotom** [comment]
Yes, I already have this option activated and it still doesn't work.

**Comment by savetheclocktower** [comment]
Just tried it out on my Pulsar. All I had to do was check that box and it started offering suggestions for `window`, `document`, etc.

Are you getting other completion suggestions? Like, for snippets and keywords and whatnot?

**Comment by kurotom** [comment]
It shows me suggestion and autocomplete correctly JavaScript when creating classes, the constructor, manipulating strings, creating array, function, etc.
But it doesn't show me elements related to handling the DOM.

**Comment by kurotom** [comment]
Some images, it is seen that it works with JavaScript:
https://imgur.com/dqzhc6E
https://imgur.com/zw3sXzD
https://imgur.com/SDfp9Ll

**Comment by savetheclocktower** [comment]
Then I'm out of ideas. You can check the developer tools (View -> Developer -> Toggle Developer Tools) to see if there are any tern-related errors in the console. You can restart Pulsar to see if that helps. If not, I'd rename your `~/.pulsar` directory temporarily and restart to get a fresh config, then install _only_ `atom-ternjs` and see if you can get that working. If so, that'd at least be step in the right direction.

If nothing works, maybe [the folks on Discord](https://discord.gg/7aEbB9dGRT) will have some ideas that I haven't thought of.

**Comment by kurotom** [comment]
I tried that and it didn't fix the problem.
I searched a lot and couldn't solve this problem, thanks anyway.

**Comment by mauricioszabo** [comment]
Did you configure TernJS? I just made a clean install of TernJS on Pulsar, then ran the command TernJS: Open Configuration, checked "browser", and I have autocomplete of DOM elements...

![Tern](https://user-images.githubusercontent.com/138037/219922820-0348cbdc-5e4a-4277-aab6-cc17c94b5b7a.gif)

**Comment by kurotom** [comment]
Thank you very much @mauricioszabo and everyone, solved, now it works fine in Pulsar.
