### ISSUE TITLE
Version inconsistencies in downloads and tags

### ISSUE THREAD

**Issue by cat-master21** [pulsar-edit/pulsar#391]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://github.com/pulsar-edit/pulsar/releases/tag/v1.102.0

### What's your issue?

It seems that the version of Pulsar is slightly confusing as the git tag claims it is "v1.102.0" while the output artifacts and pulsar itself say "1.102.0". This problematic for external manifest checkers (like flatpak-external-data-checker) so I think it is best to remove the "v" at the beginning of the tag names

**Comment by Spiker985** [comment]
Much like Atom before us, the tag will always be prefixed with `v`, and in the past the release name would also follow suite.

In this instance, the download artifact names are actually incorrect as they would normally be `Pulsar-1.102.2023021605.AppImage` for example - however, for this release they were renamed to also account for what platform they corresponded to.

The GitHub release process is very manual as of right now, and is actually not our primary source of updates (but it will be the most static).

Is there are particular platform that you're referring to when you state "This is problematic for external manifest checkers"?

**Comment by Spiker985** [comment]
@cat-master21 If you would like to contribute, I just made a discussion https://github.com/pulsar-edit/.github/discussions/134 for this exact thing, if you would like to chime in there.

**Comment by Spiker985** [comment]
Redirect to discussion pulsar-edit/.github#134
