### ISSUE TITLE
Pulsar 1.101.0-beta can't update

### ISSUE THREAD

**Issue by CyberSkull** [pulsar-edit/pulsar#392]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When I have Pulsar 1.101.0-beta check for updates I get the following error message: "Update check failed. The server sent an invalid response. Try again later."

Pulsar  : 1.101.0-beta
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0
macOS: 13.2.1, M2

### Pulsar version

1.101.0-beta 

### Which OS does this happen on?

🍎 macOS

### OS details

13.2.1, M2

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1. Open Pulsar.
2. `Pulsar > Check for Update` or `Pulsar > About > Check now`.

### Additional Information:

<img width="1570" alt="Screenshot 2023-02-16 at 11 22 35 PM" src="https://user-images.githubusercontent.com/201815/219577191-32fe234d-a295-4c58-ab67-7dfe5151a5ad.png">

**Comment by confused-Techie** [comment]
Unfortunately Pulsar does not yet support automatic updates.

So no matter what settings are enabled it will not be able to automatically update at this time. This is something we are working to fix, but for the time being you're best bet is to [manually download](https://pulsar-edit.dev/download.html) the latest release when you'd like to update. 

You can read more about this on our [website](https://pulsar-edit.dev/#automatic-updates). 

And once automatic updates are available the setting to enable automatic updates should drop this text: 

![image](https://user-images.githubusercontent.com/26921489/219592995-1da10a84-0df4-43eb-a6b8-d66d5cda56a1.png)

**Comment by CyberSkull** [comment]
The menu and button should be greyed out until the updater is implemented.
