### ISSUE TITLE
Invalid config.cson results in "running" but has actually crashed on startup

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/pulsar#409]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Filling out of the behalf of `Sinful712#2679` in the Discord. This is for posterity sake, the issue has already been resolved, but I would like to look into mitigating the cause.

With an invalidate config.cson, Pulsar shows as running within Task Manager, but no window ever loads.

```cson
"*":
  #Valid cson node
  "atom-path-intellisense":
    "manual-suggest": false
  #Invalid cson node, missing colon
  "one-dark-ui"
    hideDockButtons: true
```
Simply by missing a colon, the editor failed to load. This required the user to rename their `~/.pulsar` folder (as `--safe` didn't work) in order to validate if it was their settings, or something else.

### Pulsar version

1.102.2023022623

### Which OS does this happen on?

🪟 Windows

### OS details

11

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Edit config.cson
2. Add node with invalid scope (unsure if it's simply missing a colon while having secondary information underneath, or something else)
3. Attempt to launch Pulsar
4. Pulsar process should start, but no window ever loads

### Additional Information:

Pulsar running without Window
![image](https://user-images.githubusercontent.com/7829451/222270321-62fa3827-1716-4907-8573-c163588a5f66.png)

**Comment by Spiker985** [comment]
My current running theory is that there's an unhandled exception, which results in never getting to making an `atom-window.js` instance

**Comment by Meadowsys** [comment]
ooh, I've actually experienced this myself in the past on macOS 13, when I commented out a configuration option to test something and the window just didn't show up at all. Removing that line instead of commenting it out fixed the issue

**Comment by Daeraxa** [comment]
You can probably remove the platform tags as this is global. Running from source does give you more of a clue than the binary.

```
$ yarn start                                                                                                 
yarn run v1.22.19
warning ../../package.json: No license field
$ electron --no-sandbox --enable-logging . -f
App threw an error during load
[stdin]:5:3: error: unexpected newline
  core
  ^
unexpected newline
[stdin]:5:3: error: unexpected newline
  core
  ^
[1375452:0302/001114.825919:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```
(I removed the colon after `core`)

**Comment by Meadowsys** [comment]
yeah, I believe its global too, something to do with parsing the cson ><

**Comment by Spiker985** [comment]
Now the big question, why isn't that error handled? 🤔

**Comment by Daeraxa** [comment]
It looks like it fails here:
https://github.com/pulsar-edit/pulsar/blob/7d933c561f6f43def1dbb0408df9575e265f6e7d/src/main-process/start.js#L137

which is called at:

https://github.com/pulsar-edit/pulsar/blob/7d933c561f6f43def1dbb0408df9575e265f6e7d/src/main-process/main.js#L66

You get a different error if you try to use json rather than cson (which is also valid):
```
yarn start                                                                                                    
yarn run v1.22.19
warning ../../package.json: No license field
$ electron --no-sandbox --enable-logging . -f
App threw an error during load
SyntaxError: Unexpected token { in JSON at position 104
    at JSON.parse (<anonymous>)
    at parseObject (/home/dae/pulsar/node_modules/season/lib/cson.js:54:19)
    at parseContentsSync (/home/dae/pulsar/node_modules/season/lib/cson.js:68:16)
    at Object.readFileSync (/home/dae/pulsar/node_modules/season/lib/cson.js:180:14)
    at getConfig (/home/dae/pulsar/src/main-process/start.js:148:33)
    at start (/home/dae/pulsar/src/main-process/start.js:57:18)
    at Object.<anonymous> (/home/dae/pulsar/src/main-process/main.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
Unexpected token { in JSON at position 104
SyntaxError: Unexpected token { in JSON at position 104
    at JSON.parse (<anonymous>)
    at parseObject (/home/dae/pulsar/node_modules/season/lib/cson.js:54:19)
    at parseContentsSync (/home/dae/pulsar/node_modules/season/lib/cson.js:68:16)
    at Object.readFileSync (/home/dae/pulsar/node_modules/season/lib/cson.js:180:14)
    at getConfig (/home/dae/pulsar/src/main-process/start.js:148:33)
    at start (/home/dae/pulsar/src/main-process/start.js:57:18)
    at Object.<anonymous> (/home/dae/pulsar/src/main-process/main.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
[1386738:0302/005336.638520:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by confused-Techie** [comment]
What's interesting is there is actually error handling for an invalid CSON file wherever it continually watches for updates.

I remember seeing this on an htmltim video. He created invalid CSON, and a notification popped up telling him it was invalid and couldn't be loaded.

I almost wonder, could we defer ever loading the file itself and let whatever that function is do it all? That way we don't have to create duplicate error handling, since it looks like during initial load there is no error handling from the bit that was posted above

**Comment by DeeDeeG** [comment]
How about something like a try/catch:

```diff
    if (configFilePath) { 
-     const configFileData = CSON.readFileSync(configFilePath); 
+     const configFileData = try { CSON.readFileSync(configFilePath) } catch (e) { throw(e) }; 
      config.resetUserSettings(configFileData); 
    } 
```
