### ISSUE TITLE
Where is the M1 Version of Pulsar Beta 102?

### ISSUE THREAD

**Issue by manngo** [pulsar-edit/pulsar#413]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://github.com/pulsar-edit/pulsar/releases

### What's your issue?

I was about to download the latest version of Pulsar, but there doesn’t appear to be an M1 (Silicon) version of the Mac version.

### Which OS/Browser/Version does this happen on?

Doesn’t matter

### Steps to Reproduce/Additional Details:

Look here: https://github.com/pulsar-edit/pulsar/releases

**Comment by savetheclocktower** [comment]
Not sure why it's not listed on that page, but you can find it here: https://pulsar-edit.dev/download.html#regular-releases

**Comment by confused-Techie** [comment]
It should be, I'm seeing it.

Look for the `Silicon.Mac.1.102.0.X` builds.

You might have to click `Show all 16 assets`

![image](https://user-images.githubusercontent.com/26921489/222655635-1c9e8498-aff0-4b65-89db-edb5fb6cf2db.png)

**Comment by manngo** [comment]
D’Oh!

Yes, it’s there - I didn’t notice that link.

Thanks

**Comment by confused-Techie** [comment]
@manngo glad to hear it wasn't some strange error with GitHub, thanks for letting me know!

**Comment by DeeDeeG** [comment]
Yeah, I looked at it for this issue and had to scratch my head for a moment until I saw the `Show all 16 assets` like I now see @confused-Techie mentioned above.

**Comment by Meadowsys** [comment]
Personally, I find the naming of `Silicon....` to be a little strange.. there was this discussion for the naming though, so hopefully resolved soon ~~(tm)~~: https://github.com/orgs/pulsar-edit/discussions/134
