### ISSUE TITLE
Missing commas from package install count

### ISSUE THREAD

**Issue by machitgarha** [pulsar-edit/pulsar#441]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The package install count was normalized using commas, but it got disappeared. I think this happened in the latest release.

E.g., it was showing as `1,234,567`, but now is `1234567`.

![image](https://user-images.githubusercontent.com/14151550/227453765-cb510379-edb7-421f-a257-d843cc861416.png)

### Pulsar version

1.103.0

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 37 WS

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open Settings.
2. Open Packages section.
3. View the install count of one of the installed packages.

**Comment by confused-Techie** [comment]
Is anyone on an older release able to confirm if this changed per release? Or is it due to a change in the backend? Since I don't think any values are normalized when sent through the backend, or ever have, so just wanna make sure

**Comment by Daeraxa** [comment]
I don't see any commas in 1.101.0-beta nor 1.102.0.

**Comment by confused-Techie** [comment]
Awesome thanks @Daeraxa so really then we'd need to add normalization to this. Which I feel is probably more suited to be added to `settings-view` rather than the ppm or something like that

**Comment by Daeraxa** [comment]
Its something we should take locale into consideration at some point too because it should be `.` for many countries, not `,`.

**Comment by confused-Techie** [comment]
Very good point. I know there are some API's in JS like [`toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) exists. So ideally we could rely on that, and I'm hoping/assuming the Electron Chromium would be able to know about the users locale, so that way we don't have to even think about it

**Comment by machitgarha** [comment]
> I don't see any commas in 1.101.0-beta nor 1.102.0.

Oh right. Sorry, I made a mistake. Something in my mind told me this was a feature in Atom and, eventually, Pulsar.

BTW, thanks for taking this into account.

**Comment by Daeraxa** [comment]
I think Atom did show it but we have a completely different backend now, the old backend probably delivered that info but it was closed source so it was re-created from scratch.

**Comment by icecream17** [comment]
going to mention the `Intl` feat specfically. `Intl.NumberFormat().format(7825952822)` automatically adds commas for me... don't know for other languages or details of how it works actually.

**Comment by Meadowsys** [comment]
oh yeah, I think so (I haven't forgotten about it by the way ><)

**Comment by Spiker985** [comment]
> oh yeah, I think so (I haven't forgotten about it by the way ><)

I was just on a roll of addressing old PRs and Issues this morning when I should've been asleep. All's good👌
