### ISSUE TITLE
Scrollbars are not native on Linux

### ISSUE THREAD

**Issue by machitgarha** [pulsar-edit/pulsar#442]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Not sure if it's a bug, but scrollbars on Linux look like this:

![image](https://user-images.githubusercontent.com/14151550/227471399-1455c46e-93ff-4ff2-834c-1a2804751bdf.png)

Instead, it should look like this (Atom 1.60.0):

![image](https://user-images.githubusercontent.com/14151550/227472148-f8612a5e-4927-4601-873b-d4d165a865b8.png)

### Pulsar version

1.103.0

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 37 WS

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open a scrollable area.

**Comment by m1ga** [comment]
KDE, Fedora 37

![Screenshot_20230324_110319](https://user-images.githubusercontent.com/4334997/227491543-d856be08-e9b1-4e6e-ae72-65f99a29ba18.png)

no issue with the scrollbar.

**Comment by machitgarha** [comment]
@m1ga, oops. It seems the problem is with my UI theme (i.e. Glacier Darkula). But the same theme works completely OK in Atom 1.60.0. :thinking:

**Comment by machitgarha** [comment]
Found the problem. I don't know Less CSS much, but the problem are these `/deep/`s inside selectors: https://github.com/pit00/glacier-darkula-ui/blob/master/styles/atom.less#L31

Removing those fixed the issue.

**Comment by confused-Techie** [comment]
@machitgarha Glad you were able to determine what was causing the issue, glad to see it's working for you now!
