### ISSUE TITLE
Finish Decaffing all core packages

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#444]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Like the title says, we want to continue to decaf all core packages, and any help here is gladly appreciated!

For a quick reminder here's the basic workflow we would want to see during a decaf PR.
1) Get a branch made on this repo, of `<package>-decaf` (may need to contact the admins here, which can be done via issues or on Discord). This branch will **only** contain the machine decaf files. That's all, nothing deleted or modified from the machine decaf code.
2) Then fork this branch specifically, and make your manual decaf changes as needed. To help make the code look nice, and match modern JavaScript standards.
3) Once done create a PR of your changes to the `<package>-decaf` branch.
4) If the review goes well then your changes can be merged directly to the `master` branch and we are good to go!

Again some quick important notes:
* The `<package>-decaf` branch can **only** contain machine decaf code. Nothing else, no other changes
* Your manual decaf work should be properly limited in scope, a decaf PR is not the time for additional refactoring or features, it'll be easier to review and merge, if it's scope stays to decaf work, additional PRs for other changes can always be made after or before hand.
* Lastly, make sure to only decaf either the `specs` or `lib/src` files in a package at a single time. These should not be decaffed together

With all of that said, below will be a list of core packages on this repo that still need to be decaffed.

* [x] `autocomplete-css` Source
* [x] `autocomplete-css` Specs
* [x] `autocomplete-atom-api` Source
* [x] `autocomplete-atom-api` Specs
* [x] `autoflow` Source
* [x] `autoflow` Specs
* [x] `deprecation-cop` Source
* [x] `deprecation-cop` Specs
* [ ] `tree-view` Source
* [x] `tree-view` Specs
* [x] `language-c` Specs
* [x] `language-clojure` Specs
* [x] `language-coffee-script` Specs
* [x] `language-csharp` Specs
* [x] `language-css` Specs 
* [x] `language-gfm` Specs
* [x] `language-git` Specs
* [x] `language-go` Specs
* [x] `language-html` Specs
* [x] `language-hyperlink` Specs
* [x] `language-java` Specs
* [x] `language-javascript` Specs
* [x] `language-json` Specs
* [x] `language-less` Specs
* [x] `language-make` Specs
* [x] `language-mustache` Specs
* [x] `language-objective-c` Specs
* [x] `language-perl` Specs
* [x] `language-php` Specs
* [x] `language-python` Specs
* [x] `language-ruby` Specs
* [x] `language-ruby-on-rails` Specs
* [x] `language-sass` Specs
* [x] `language-shellscript` Specs
* [x] `language-sql` Specs
* [x] `language-text` Specs
* [x] `language-todo` Specs
* [x] `language-toml` Specs
* [x] `language-xml` Specs
* [x] `language-yaml` Specs
* [x] `settings-view` Source
* [x] `settings-view` Specs
* [ ] `status-bar` Source
* [x] `status-bar` Specs
* [X] `wrap-guide` Source
* [x] `wrap-guide` Specs

### What benefits does this feature provide?

Code that everyone is happy to work with, and comfortable with.

### Any alternatives?

Leave the code as CoffeeScript, and have to half learn it every time it needs changes.

### Other examples:

Would highly recommend looking at #443 for a newer example of this
Additional examples of this workflow and the changes we would want to see on decaf work can be seen here:
* #357 
* #352

**Comment by itsajay1029** [comment]
Can you assign this to me ? I'd love to work on it @confused-Techie

**Comment by confused-Techie** [comment]
@itsajay1029 We don't have to assign it, but if you'd like I'd be more than happy to do so, then just let me know what machine decaf branches you'd like for me to create to get you started!

**Comment by itsajay1029** [comment]
language-javascript specs

**Comment by itsajay1029** [comment]
@confused-Techie Please guide me on the issue ?

**Comment by confused-Techie** [comment]
@itsajay1029 Sorry for lag, got a bit distracted.

But I've created the `pulsar-machine-decaf` branch on the repo, which I'll go ahead and try to add all the items listed above to it, so that if anyone wants to begin decaf work, the changes needed will already be there.

Which that includes `language-javascript` so you should be good to go!

**Comment by itsajay1029** [comment]
Can you ellaborate a littleon `decaf work` so that I can well understand what I need to do @confused-Techie ?

**Comment by confused-Techie** [comment]
Sure @itsajay1029!

So essentially the machine decaf code that we get from automated tools to decaf CoffeeScript have a few issues. Mainly they use non-standard methods of translating the safety logic that CoffeeScript contains to JavaScript, and they generally produce code that no human would ever write, because it's not very readable, or otherwise just a tad ugly.

So the manual process of decaf work comes to making this automated code just look a little bit nicer.

For example you can see in #443 I was doing the manual decaf work on `tabs` package's specs. You can look at that PR to see some of the specific changes I made.

For example:

```javascript
module.exports = 
(WrapGuideElement = class WrapGuideElement {
```

Was produced by machine decaf and I changed this to be:

```javascript
module.exports = class WrapGuideElement {
```

You can see how the second is what a person would actually type out and is loads easier to read. So essentially, part of it is light refactor work from perfectly valid code just to make it more readable.

Although if you'd like some more strict direction, you can take a look at one of our earlier docs instructing people how to do decaf work (Which everything prior to this link is essentially out of date now, but the part I'm linking still is valid) which gives a short check list of things we know that the machine decaf will be bad at. That doc is available [here](https://github.com/pulsar-edit/.github/blob/main/project-birth/CONTRIBUTING-DURING-START.md#confirming-the-quality-of-decaffeination).

But otherwise if you've got any specific questions I'd be more than happy to help

**Comment by confused-Techie** [comment]
If anyone else plans on working on this issue, feel free to ask for a specific package to have it's decaf branch created. I've deleted `pulsar-machine-decaf` as at this point it's quite out of date, and had never received any activity since I created it as requested above.

**Comment by icecream17** [comment]
note that for the status-bar package, it is already decaffed here: https://github.com/aminya/status-bar

the same might be said for many packages and atom-community

**Comment by confused-Techie** [comment]
We are almost there!
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/48f8401f-0aa1-48c2-85f5-8263c02e5bc6)

**Comment by confused-Techie** [comment]
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/27c3518c-92b4-40db-ae47-b18d4779f6f1)

1.5% to go!

All that's left now to be decaffed:

* `status-bar` source
* `tree-view` source

**Comment by confused-Techie** [comment]
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/95edbcf9-9c50-447b-b676-5e7b9a8efd35)

For anyone curious, here's where we started with our Decaf effort.

This is a snapshot taken from the wayback machine from 18th August 2022.

**Comment by confused-Techie** [comment]
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/0f34390d-b6d5-47f9-bb2c-c504482dff45)

And with that, after so many decaf PRs, it looks like we are finally done.

The whole editor, and all currently bundled packages have been decaffed. Big woot, we are now at `0.7%` CoffeeScript code in the repository, which is fantastic! And hopefully makes the editor a whole lot easier for new contributors, as you don't have to learn a whole different language.
