### ISSUE TITLE
Installation Via Scoop

### ISSUE THREAD

**Issue by 0xvividmirage** [pulsar-edit/pulsar#447]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Scoop  is basically Homebrew (Mac package manager) for Windows. Can we support installing Pulsar-Edit via this method?

Here is a link to Scoop:
[https://scoop.sh](https://scoop.sh/)

Thank you.

 

### What benefits does this feature provide?

Convenient package management akin to what you would expect from Homebrew.

### Any alternatives?

I can only think of Chocolatey for Windows which I find to be worse because it requires admin access for the user to install packages the last time I checked.

**Comment by Daeraxa** [comment]
We have a master list of things here - https://github.com/orgs/pulsar-edit/discussions/77

Chocolately is still the priority at this point for the first officially supported Windows package manager.

**Comment by confused-Techie** [comment]
@Daeraxa, do we feel alright closing this issue, and adding the relevant request to that discussion, to try and keep unnecessary issues out of this repo?

**Comment by Daeraxa** [comment]
I would say so yes, it is what we did with AUR etc. We do have Scoop in the list but not emphasised as a priority.

**Comment by confused-Techie** [comment]
Closing this in favor of the discussion. Thanks for letting us know users are looking for this @0xvividmirage!
