### ISSUE TITLE
crashes and does not open in MacOS M1 Ventura 13.3

### ISSUE THREAD

**Issue by neeraj-er** [pulsar-edit/pulsar#455]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Post installation, it does not open and keep crashing. Seems something need to be updated against lastest macos release of ventura 13.3

### Pulsar version

latest macos silicon chip

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

MacOS Ventura 13.3

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

Download for M1 
install it
open it ,there issue start of crashing.

### Additional Information:

Nothing

**Comment by Meadowsys** [comment]
ooh! This is actually a known issue, we submitted a PR earlier today: #454. Feel free to test it to see if the issue is fixed (I posted links in [this comment](https://github.com/pulsar-edit/pulsar/pull/454#issuecomment-1493459203))

**Comment by confused-Techie** [comment]
Exactly as @Meadowsys said.
The best thing that can be done to fix this is test their build from their linked PR.

**Comment by confused-Techie** [comment]
As there is a known fix for this issue, that is now available in both the regular release, and rolling release, and we haven't heard any update from the original issuer in 2 weeks, I'll go ahead and close this one.

Thanks a ton for contributing @neeraj-er!
