### ISSUE TITLE
Build 1.103.2023040505 does not work for Intel macOS 13.3

### ISSUE THREAD

**Issue by etienne-miralytik** [pulsar-edit/pulsar#467]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I'v updated to 1.103.2023040505 and now Pulsar opens like this:
<img width="795" alt="Bildschirmfoto 2023-04-06 um 11 31 58" src="https://user-images.githubusercontent.com/106660044/230336255-b02f70b7-4155-4846-a797-49a92757138d.png">

Same story with safe mode.

Menu bar also looks very empty and I have very few options there, of which only the "Toggle Dev Tools" works.
<img width="205" alt="Bildschirmfoto 2023-04-06 um 11 32 52" src="https://user-images.githubusercontent.com/106660044/230336521-d02f9d32-d326-42a5-96f2-b661927144b4.png">

### Pulsar version

1.103.2023040505

### Which OS does this happen on?

🍎 macOS

### OS details

macOS 13.3 (22E252)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Start Pulsar

**Comment by Meadowsys** [comment]
Ah, yes, this would be mostly my fault ><

I believe we've identified the problem and fix on PR #464. You could stick to the latest regular release until that PR gets merged, then the problem should be resolved.

**Comment by etienne-miralytik** [comment]
I've tried build 1.103.2023040600 from #464 and can confirm that this fixes the startup.

However I noticed that the "Pulsar" Menu changed, just that you know.

before:
<img width="229" alt="Bildschirmfoto 2023-04-06 um 14 29 39" src="https://user-images.githubusercontent.com/106660044/230379007-21e8efda-ef86-4a75-a298-a01614ca937e.png">

after:
<img width="189" alt="Bildschirmfoto 2023-04-06 um 14 33 23" src="https://user-images.githubusercontent.com/106660044/230379791-5eb69ccb-f541-4e48-884b-77bfdff078d6.png">

**Comment by mauricioszabo** [comment]
Newer CI scripts are checking if _the binary itself_ runs: see https://cirrus-ci.com/github/pulsar-edit/pulsar/build-and-test. On this Cirrus run, we can see that Silicon Mac is failing, so we protect ourselves against this kind of failure in the future.

As for the fix, I believe https://github.com/pulsar-edit/pulsar/pull/454 fixes this right?

**Comment by etienne-miralytik** [comment]
I actually tried the build from #454 and that had some pretty long start up time and I even got a message about this (application is taking very long, wait or close).
So that PR alone does not fixes it properly for me.

**Comment by Meadowsys** [comment]
i18n has been reverted for now, and we will try to figure out all the issues on a seperate branch, so this issue should be resolved

**Comment by etienne-miralytik** [comment]
I can confirm build 1.103.2023040620 fixes the issue as expected.

Note that https://download.pulsar-edit.dev/?os=intel_mac&type=mac_dmg still points to the broken build 1.103.2023040505.
