### ISSUE TITLE
inbuilt deprecated calls in "about" `HTMLDocument.registerElement` and "hyperclick" `Object.<anonymous>` ?

### ISSUE THREAD

**Issue by goyalyashpal** [pulsar-edit/pulsar#486]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

There are "2 deprecations" or 2 calls to deprecated methods in pulsar (by default?)

`about` (1 deprecation)

Use `customElements.define` instead of `document.registerElement` see https://javascript.info/custom-elements

```
HTMLDocument.registerElement (file:///D:/ProgramFiles/Pulsar/resources/app.asar/static/index.js:99:12)
Object.<anonymous> (%USERPROFILE%\.pulsar\packages\ink\lib\console\view.js:127:45)
Object.<anonymous> (%USERPROFILE%\.pulsar\packages\ink\lib\console\view.js:131:3)
Module._compile (D:\ProgramFiles\Pulsar\resources\app.asar\src\native-compile-cache.js:120:30)
Object..js (D:\ProgramFiles\Pulsar\resources\app.asar\src\compile-cache.js:252:23)
Module.load (internal/modules/cjs/loader.js:935:32)
```

----
<tt>[hyperclick]</tt> (1 deprecation) 

[hyperclick]: https://github.com/facebookarchive/hyperclick

Use `require("electron").shell` instead of `require("shell")`

```
Object.<anonymous> (D:\ProgramFiles\Pulsar\resources\app.asar\exports\shell.js:4:6)
Object.<anonymous> (D:\ProgramFiles\Pulsar\resources\app.asar\exports\shell.js:9:3)
Module._compile (D:\ProgramFiles\Pulsar\resources\app.asar\src\native-compile-cache.js:120:30)
Object..js (D:\ProgramFiles\Pulsar\resources\app.asar\src\compile-cache.js:252:23)
Module.load (internal/modules/cjs/loader.js:935:32)
Module._load (internal/modules/cjs/loader.js:776:14)
```

### Pulsar version

1.103.0

### Which OS does this happen on?

🪟 Windows

### OS details

Win 10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Launch Pulsar
2. See the status bar

**Comment by savetheclocktower** [comment]
In general, deprecations are not things that a user need to report or care about. They are things that may no longer work in the future.
