### ISSUE TITLE
Mirror to CodeBerg

### ISSUE THREAD

**Issue by foxxy432** [pulsar-edit/pulsar#500]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

We should mirror our repos to Codeberg because:

Codeberg is libre, free, open-source, privacy-friendly, non-profit
GitHub is privacy-invasive, proprietary
People on Codeberg like me can contribute to the project
GitHub can take down your repos

FAQ

Q: - GitHub Actions -- this is a huge time saver for me
- Forcing all contributors to modify their current setup and move to another hosting -- we may just lose contributors in the end

A: As I said, we only just mirror. The repo will be available and contributable on both sites.

Q: - Transferring issues -- is this possible? Issues here represent a technical knowledge base we can't live without
- Transferring wiki and all edit history -- possible?

A: Yes, it is possible.
a. Example for issues:

Migration to independent platform for provision of source code andersju/webbkoll#35
https://codeberg.org/dataskydd.net/webbkoll/issues/35
[UI/UX] Simplification of the user interface for non-technical people andersju/webbkoll#33
https://codeberg.org/dataskydd.net/webbkoll/issues/33

Framed answers? - Locations zyachel/quetre#7
https://codeberg.org/zyachel/quetre/issues/7

b. Example for commits:

https://codeberg.org/dataskydd.net/webbkoll/commit/6ddfbc6c71ab92f754252dd4904cf49fb19672a6
andersju/webbkoll@6ddfbc6

c. Example for wiki:

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Home/_history?page=2
https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Home?action=_revision

Q: Despite having mirror/s, the project will still continue to be operated from GitHub for development, so having yet another mirror doesn't solve anything.

A: You can create issues, contribute, view the repos on there without going to GitHub! Example:

https://github.com/libredirect/libredirect
https://codeberg.org/LibRedirect/libredirect
https://github.com/zyachel/quetre
https://codeberg.org/zyachel/quetre

Q: How does Codeberg mirror comments from GitHub?

A: It uses Access Token.

Q: My repos are very bandwidth-intensive projects, and I have my doubts as to whether the owner(s) of Codeberg would be prepared for such a massive bandwidth rate increase. I've also had individual projects be disabled on small sites before due to taking too much bandwidth.

A: Oh.. I think you should directly ask https://docs.codeberg.org/contact/ about if they are ready for massive bandwidth rate increase.

### What benefits does this feature provide?

Codeberg is libre, free, open-source, privacy-friendly, non-profit
GitHub is privacy-invasive, proprietary
People on Codeberg like me can contribute to the project
GitHub can take down your repos

### Any alternatives?

We should mirror our repos to Codeberg because:

Codeberg is libre, free, open-source, privacy-friendly, non-profit
GitHub is privacy-invasive, proprietary
People on Codeberg like me can contribute to the project
GitHub can take down your repos

FAQ

Q: - GitHub Actions -- this is a huge time saver for me
- Forcing all contributors to modify their current setup and move to another hosting -- we may just lose contributors in the end

A: As I said, we only just mirror. The repo will be available and contributable on both sites.

Q: - Transferring issues -- is this possible? Issues here represent a technical knowledge base we can't live without
- Transferring wiki and all edit history -- possible?

A: Yes, it is possible.
a. Example for issues:

Migration to independent platform for provision of source code andersju/webbkoll#35
https://codeberg.org/dataskydd.net/webbkoll/issues/35
[UI/UX] Simplification of the user interface for non-technical people andersju/webbkoll#33
https://codeberg.org/dataskydd.net/webbkoll/issues/33

Framed answers? - Locations zyachel/quetre#7
https://codeberg.org/zyachel/quetre/issues/7

b. Example for commits:

https://codeberg.org/dataskydd.net/webbkoll/commit/6ddfbc6c71ab92f754252dd4904cf49fb19672a6
andersju/webbkoll@6ddfbc6

c. Example for wiki:

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Home/_history?page=2
https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Home?action=_revision

Q: Despite having mirror/s, the project will still continue to be operated from GitHub for development, so having yet another mirror doesn't solve anything.

A: You can create issues, contribute, view the repos on there without going to GitHub! Example:

https://github.com/libredirect/libredirect
https://codeberg.org/LibRedirect/libredirect
https://github.com/zyachel/quetre
https://codeberg.org/zyachel/quetre

Q: How does Codeberg mirror comments from GitHub?

A: It uses Access Token.

Q: My repos are very bandwidth-intensive projects, and I have my doubts as to whether the owner(s) of Codeberg would be prepared for such a massive bandwidth rate increase. I've also had individual projects be disabled on small sites before due to taking too much bandwidth.

A: Oh.. I think you should directly ask https://docs.codeberg.org/contact/ about if they are ready for massive bandwidth rate increase.

**Comment by foxxy432** [comment]
Ohh this is issue 500!

**Comment by Daeraxa** [comment]
We have no current plans to move to Codeberg, see: https://github.com/pulsar-edit/.github/blob/main/FAQ.md#why-dont-you-move-from-github-to-another-platform-like-gitlab-or-codeberg

We had one small "experiment" with Codeberg mirroring which caused us a few problems and we voted to not continue.

They also don't allow automatic mirrors, at least according to their docs, and we wouldn't want the overhead of maintaining it separately.

https://docs.codeberg.org/getting-started/faq/#why-am-i-not-allowed-to-set-up-an-automatic-mirror%3F

**Comment by Sertonix** [comment]
I like the idea of a codeberg mirror (or moving to coeberg) too but as mention above not planned (yet).
You could make an inofficial mirror thought and push changes to github with pull requests.
Maybe the mirror then could be mentioned somewhere in the pulsar project.

If the build scripts in the `.github` directories would be translated to woodpecker ci and work that could make moving to another platform easier. No guarentee thought that it will be accepted.
Woodpecker CI can also be used with github so it could be used to make the repositories more portable before moving anything.

**Comment by confused-Techie** [comment]
While I do appreciate you creating this issue and contributing @foxxy432, and do hear the concerns of both you and those that have thumbs up this post, as mentioned before we have not only tried this but addressed this exact concern before.

Like @Daeraxa linked, in our FAQ we address our stance on migrating to CodeBerg directly, by saying that at this time we don't think it is realistic.

Additionally, one of our members has tried to setup a mirror of the GitHub repo to Codeberg, and it was far less than ideal, causing numerous issues for members of the team, and our users.

So at this time the Pulsar team is not inclined to entertain any official mirror of CodeBerg. If any users would like to, they are more than free to host unofficial mirrors, or explore what other possibilities there are in allowing them to contribute. Since we would love to have everyone possible contribute, but as we are a very small team, having to keep eyes on GitHub, CodeBerg, Reddit, and Mastodon, to simply stay up to date with user concerns is just to much. 

I don't mean to shoot down any ideas, and do appreciate you voicing your concerns, but at this time our team is just to small to add more things we have to manage like this, and due to previous attempts it has not left a good taste in anyone's mouth.

With that said I'm going to go ahead and close this one. Feel free to communicate any other ideas on how we can take your valuable contributions besides having to add a new platform to the mix, thanks a ton for contributing

**Comment by foxxy432** [comment]
So sad

**Comment by Daeraxa** [comment]
> So sad

What is? That we don't want to have to deal with a ton of pain for ideological reasons when we have an awful lot of stuff going on... we simply don't have the resources to start dealing with something like that when we have huge changes for Pulsar itself, a massive documentation and website refactor and a bunch of other things.
I really like Codeberg, I've even made some small contributions to it and Forgejo and if I was going to launch my own project I would be doing it there but for you to come back to this conversation where we tried to explain our position on the subject to just respond "So sad" is so unbelievably rude and dismissive.

So thanks for wasting our time and efforts kindly explaining this to you (doubly so as you ticked "Have you checked for existing feature requests?" yet didn't even bother searching for "Codeberg" - https://github.com/pulsar-edit/pulsar/issues?q=is%3Aissue+sort%3Aupdated-desc+codeberg+) so I can only assume this to have been a lie.

Going to have to post my favourite link that one of our team posted about before.
[Open Source is not about you](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9).
