### ISSUE TITLE
Could not connect to indexedDB

### ISSUE THREAD

**Issue by mauricioszabo** [pulsar-edit/pulsar#531]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Pulsar package that provides the described functionality: <https://atom.io/packages>

### Description

A notification shows that Pulsar could not connect to IndexedDB

### Steps to Reproduce

1. Open a version of Pulsar
2. Open a _different version_ of Pulsar

**Expected behavior:**

Not have this notification

### Versions

**Pulsar**: 1.104.0-dev x64
**Electron**: 12.2.3
**OS**: Ubuntu 20.04.6
**Thrown From**: Pulsar Core

### Stack Trace

Could not connect to indexedDB

```
At undefined

Error: Could not connect to indexedDB
    at IDBOpenDBRequest.dbOpenRequest.onerror (/home/mauricio/projects/pulsar_repos/pulsar/src/state-store.js:31:20)
```

## Fix

There's no "easy fix" - basically, the way Pulsar keeps track of states is with IndexedDB, which is a horrible, _horrible_. Two Electron apps with the same name _will conflict_ and it's hard to make backups, it's hard to inspect, etc.

There is a solution that I can pitch, that is, to move all IndexedDB storage to SQLite3. I made some experiments with SQLite3, and it seems that this could work - now we only need to decide if we want to follow up with this experiment

**Comment by savetheclocktower** [comment]
I'm very much in favor of continuing the sqlite experiment. It would make it much less painful to run two versions of Pulsar side-by-side.

**Comment by mramendi** [comment]
Just h is this issue after updating to 1.112 from 1.105, it delays pulsar starting

**Comment by confused-Techie** [comment]
@mramendi This should only happen when two instances of Pulsar are running at the same time.
So it's very likely the update process didn't properly close the old version or accidentally started two. If only one instance is running does this issue still occur for you?

**Comment by mramendi** [comment]
Tried again, issue did not reproduce. So yes, probably something related to the update, where I hit another bug #544 and had to uninstall and reinstall.

**Comment by SvenMoenig** [comment]
I had apparently the same error once after upgrading to the 1.119.0:

### Versions

**Pulsar**: 1.119.0 x64
**Electron**: 12.2.3
**OS**: Debian GNU/Linux
**Thrown From**: Pulsar Core


### Stack Trace

Could not connect to indexedDB

```
At undefined

Error: Could not connect to indexedDB
    at IDBOpenDBRequest.dbOpenRequest.onerror (/app.asar/src/state-store.js:31:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-easy-jsdoc 4.12.5 
atom-file-icons 0.7.1 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-typescript 14.4.0 
atomic-management 0.4.2 
busy-signal 2.0.1 
declarations 1.1.3 
django-templates 0.5.0 
django-wrap-i18n 0.6.0 
file-icons 2.1.47 
git-blame 1.8.0 
gitlab-manager 0.2.2 
ide-bash 1.0.11 
ide-typescript 0.9.5 
intentions 2.1.1 
javascript-drag-import 0.1.13 
language-ansi-styles 0.1.0 
language-apache 1.8.0 
language-dot 1.7.0 
language-ini 1.25.0 
language-pip 2.0.1 
language-svg 0.9.2 
language-systemd 0.1.1 
language-tex 0.4.0 
linter 3.4.0 
linter-ui-default 3.4.1 
markdown-pdf 2.3.3 
pdfjs-viewer 1.3.0 
pp-markdown 0.0.2 
preview-plus 1.2.7 
pulsar-find-references 0.0.20 
pulsar-ide-python 1.11.1 
pulsar-ide-typescript-alpha 0.1.2 
Quick-JavaScript 2.2.0 
redmine 0.2.2 
svg-preview 0.14.0 
svn 0.0.14 
```

### Additional Information

**Comment by ambientSilk** [comment]
I have this problem after my first install of pulsar on mac. Can't seem to fix it.

**Comment by mauricioszabo** [comment]
@ambientSilk open Pulsar, go to settings, and try unchecking the option `Use Legacy Session Store`:

![Image](https://github.com/user-attachments/assets/66f2e2f9-7d4a-42d7-9562-3e4b9538bf03)

Then restart Pulsar. That should fix the issue, if it doesn't, please ping me :)

**Comment by kudlav** [comment]
### Steps to Reproduce

1. Start fresh new Pulsar

### Versions

**Pulsar**: 1.127.2025042902 x64
**Electron**: 12.2.3
**OS**: Mac OS X 10.15.7
**Thrown From**: Pulsar Core

### Stack Trace

Could not connect to indexedDB

```
At undefined

Error: Could not connect to indexedDB
    at IDBOpenDBRequest.dbOpenRequest.onerror (/app.asar/src/state-store/indexed-db.js:31:20)
```

**Comment by mauricioszabo** [comment]
@kudlav try to follow the steps I mentioned in the previous comment. IndexedDB should be considered legacy at this point, we're just keeping it for compatibility with Atom.
