### ISSUE TITLE
RPM upgrade process loses /usr/bin binary

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#544]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

See: https://github.com/orgs/pulsar-edit/discussions/178

On upgrading the .rpm binary the `pulsar` binary in `/usr/bin` is lost meaning it can no longer be run from the command line. The .desktop is unaffected as it runs from `/opt/pulsar`.

See the steps below, shows that the binary itself does work normally as on *install* it works, just not on *upgrade*.

I have attempted to fix this in https://github.com/pulsar-edit/pulsar/pull/543 but so far this is failing. I suspect it is because the script can't be found when added to the fpm options? This is only a guess as I noticed (I unfortunately no longer have the logs) that during the actual build process the `post-install` script is actually in a `tmp/` dir.

It doesn't appear this issue is affecting the .deb.

Could possibly be related to the fpm option to remove the buildid? Not sure.

### Pulsar version

1.150.0

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 36

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

- Download and install Pulsar `1.105.0` e.g (`dnf install Linux.pulsar-1.105.0.x86_64`)
- Run `which pulsar` - should return `/usr/bin/pulsar`

- Download and install Pulsar `1.105.2023051902` (`dnf install pulsar-1.105.2023052013.x86_64.rpm`)
	- `dnf` output will show that Pulsar has been upgraded.
- Run `which pulsar` - should return `which: no pulsar in ...`

- Remove pulsar with `dnf remove pulsar`
- Reinstall `1.105.2023051902` (`dnf install pulsar-1.105.2023052013.x86_64.rpm`)
- Run `which pulsar` - should return `/usr/bin/pulsar`

**Comment by KarlLevik** [comment]
This still seems to be an issue.

I have just upgraded for the first time. I upgraded from 1.106.0 to 1.107.1.

As root I did `dnf install /path/to/file/Linux.pulsar-1.107.1.x86_64.rpm`, and now `pulsar` is no longer in my PATH. (This is on Fedora 38.)

**Comment by Daeraxa** [comment]
Yeah this is definitely still a problem, I need to have a look at this again, I did try to seek some advice from somebody who knows RPMs far better than I but I wasn't able to get a solution to this (other than package it "properly" and not via electron-builder...). If anyone is an expert then PRs would be gladly accepted.

**Comment by mramendi** [comment]
This is still a problem. I had 1.105 installed on Fedora, downloaded 1.113, upgraded with dnf, no binary. Removed then installed again (all still with dnf), binary preset and starts

**Comment by mramendi** [comment]
This is STILL a problem. I downloaded 1.114, upgraded from 1.113 on Fedora. no binary. Uninstalled, reinstalled, binary works fine.

**Comment by mramendi** [comment]
Still a problem when upgrading from 1.114 to to 1.116 on Fedora.
