### ISSUE TITLE
[experimental tree-sitter]: Variable Scopes within JSDoc Comment

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#559]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Given the following example:

```js
/**
  * @param {object} featureObj - Description of object.
  */
```

In previous versions of Tree-Sitter the `featureObj` within this JSDoc comment would receive the following scopes:

  * source.js
  * comment.block
  * variable.other.jsdoc

But in newer version of Tree-Sitter it receives:
 
  * source.js
  * comment.block.documentation.js.jsdoc

Which while correct, losing the highlighting of variables within JSDoc comments makes them much harder to read at a glance, taking away some of the utility they provide. It'd be fantastic if we could reapply some type of variable scope to these items, or really an appropriate scope to prevent them from only being styled as comments. Anything that makes them standout.

### Pulsar version

1.105.2023052001

### Which OS does this happen on?

🪟 Windows

### OS details

22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Write any JSDoc comment within a JavaScript file, after enabling the experimental Tree-Sitter.

The above works totally fine as example code, but if you'd like a more complete JSDoc example:

```js
/**
 * @async
 * @function insertNewPackageVersion
 * @desc Adds a new package version to the db.
 * @param {object} packJSON - A full `package.json` file for the wanted version.
 * @param {string|null} oldName - If provided, the old name to be replaced for the renaming of the package.
 * @returns {object} A server status object.
 */
```

A comparison to what we see vs what we might expect:

## Newest Tree-Sitter

![image](https://github.com/pulsar-edit/pulsar/assets/26921489/b930196c-faf0-4424-8aa6-fe5faf490720)

## Old Tree-Sitter 

![image](https://github.com/pulsar-edit/pulsar/assets/26921489/eb735241-179d-4c76-9eda-ee6b42af303f)

**Comment by savetheclocktower** [comment]
This has been added to #555.

**Comment by confused-Techie** [comment]
> This has been added to #555.

Fantastic! Thanks!
