### ISSUE TITLE
[autocomplete-css]: Autocompletions no longer appearing in recent update

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#587]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

A new bug, seen in 1.105.2023061120 seems to have broken `autocomplete-css` autocompletions, but remains to be seen if this affects other autocompletions.

Issue details (as well as video) are over on #541

### Pulsar version

1.105.2023061120

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 11 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Create File with `.css`
2. Type in data that should warrant autocompletions, such as the following

```css
p {
  pad 
}
```

3. See that zero autocompletions are offered

**Comment by CrossV4** [comment]
did you ixed that ?
If yes could you please explain ?

**Comment by m1ga** [comment]
@CrossV4 it is still an open issue but there is a PR https://github.com/pulsar-edit/pulsar/pull/601 you could test

**Comment by CrossV4** [comment]
@m1ga i could not made it :(

**Comment by CrossV4** [comment]
never mind. I downgraded it to 105.0

**Comment by confused-Techie** [comment]
@CrossV4 If you have trouble building Pulsar manually, you can instead install [one of the binaries](https://cirrus-ci.com/build/4902146261385216) automatically made for each PR. If you'd like to test this there
