### ISSUE TITLE
Layout is unusual

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/pulsar#612]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The layout became unusual

![image](https://github.com/pulsar-edit/pulsar/assets/68846168/bc28bf11-f099-45c3-8d40-a2c89be37ddb)

### Pulsar version

1.106.2023062806

### Which OS does this happen on?

🪟 Windows

### OS details

11

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. download pulsar 1.106.2023062806 from https://cirrus-ci.com/task/4827212772278272
2. double click to install
3. run pulsar after installation

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this! 

But the binary you linked to isn't a production binary, rolling release or regular release.

That's a binary produced by a currently open PR that has not yet been reviewed over on #611 

If possible, would you mind reporting this behavior on that PR so it can be addressed there and closing this issue out?

Also just to double check, this binary wasn't retrieved via the pulsar website at all correct?

But very much do appreciate you reporting this issue! It's fantastic to find these problems before code ever makes it into Pulsar officially

**Comment by confused-Techie** [comment]
Resolved by d682c8ea219088f72e25bca19e23bc8e5c4d9473

**Comment by zhaolinlau** [comment]
> Resolved by [d682c8e](https://github.com/pulsar-edit/pulsar/commit/d682c8ea219088f72e25bca19e23bc8e5c4d9473)

Here have not been resolved

![image](https://github.com/pulsar-edit/pulsar/assets/68846168/d916d69d-74f2-4140-9127-a45575afec1a)

**Comment by confused-Techie** [comment]
> > Resolved by [d682c8e](https://github.com/pulsar-edit/pulsar/commit/d682c8ea219088f72e25bca19e23bc8e5c4d9473)
> 
> Here have not been resolved
> 
> ![image](https://github.com/pulsar-edit/pulsar/assets/68846168/d916d69d-74f2-4140-9127-a45575afec1a)
> 

Thanks for pointing this out! Ill take a look at it, this afternoon

**Comment by confused-Techie** [comment]
@zhaolinlau ae22f32ea30b16ff689f07548e4aac154fcfc9bf should resolve this, as well as any other possible issues.

Used some regex to search through every core package, and found there were quite a few items initially missed. Feel free to give it a try and see if you can find anything else not quite right

**Comment by zhaolinlau** [comment]
> @zhaolinlau [ae22f32](https://github.com/pulsar-edit/pulsar/commit/ae22f32ea30b16ff689f07548e4aac154fcfc9bf) should resolve this, as well as any other possible issues.
> 
> Used some regex to search through every core package, and found there were quite a few items initially missed. Feel free to give it a try and see if you can find anything else not quite right

Thank you for fixing those!
