### ISSUE TITLE
Tree view's toggle button cannot be hovered

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/pulsar#613]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Tree view's toggle button cannot be hovered if the tree view is not being viewed.

https://github.com/pulsar-edit/pulsar/assets/68846168/84e61302-0e3e-4bd3-9c96-9f5c99b32758

### Pulsar version

1.106.0

### Which OS does this happen on?

🪟 Windows

### OS details

11

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. run pulsar
2. close the tree view
3. hover the tree view's toggle button

**Comment by confused-Techie** [comment]
Interesting, this works as expected on Windows 10 22H2, with Pulsar 1.106.0

Could you maybe take a look at your `tree-view` settings or send them here so I can try to recreate this?

**Comment by zhaolinlau** [comment]
> Interesting, this works as expected, for me, on Windows 10 22H2, with Pulsar 1.106.0
> 
> Could you maybe take a look at your `tree-view` settings or send them here so I can try to recreate this?

No problem now lol not sure why
