### ISSUE TITLE
Issue with terminal package installation

### ISSUE THREAD

**Issue by ayoubachak** [pulsar-edit/pulsar#619]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I'm having an issue with the installation of some packages, I just installed pulsar ( Fresh normal .exe installation ), I tried to install 2 terminal packages which are : platformio-ide-terminal and terminal-plus.
I'm not sure if the problem is with the packages or the ide because I tried installing color-picker and it installed with no problems.
I'm getting this error with both terminal packages :

Installing “platformio-ide-terminal@2.10.1” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0 install C:\Users\ayoub\AppData\Local\Temp\apm-install-dir-202362-12544-173sp1k.mzv4i\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\ayoub\AppData\Local\Temp\apm-install-dir-202362-12544-173sp1k.mzv4i\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "F:\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\Pulsar\\resources\\app\\ppm\\bin\\node.exe" "C:\\Program Files\\Pulsar\\resources\\app\\ppm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ayoub\AppData\Local\Temp\apm-install-dir-202362-12544-173sp1k.mzv4i\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ayoub\AppData\Local\Temp\apm-install-dir-202362-12544-173sp1k.mzv4i\package.json'
npm WARN apm-install-dir-202362-12544-173sp1k.mzv4i No description
npm WARN apm-install-dir-202362-12544-173sp1k.mzv4i No repository field.
npm WARN apm-install-dir-202362-12544-173sp1k.mzv4i No README data
npm WARN apm-install-dir-202362-12544-173sp1k.mzv4i No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ayoub\.pulsar\.apm\_logs\2023-07-02T15_27_18_619Z-debug.log

Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Please install Python and Visual Studio to continue.
Run pulsar -p install --check after installing to test compiling a native module.

### Pulsar version

1.106.2023063007

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Installing the terminal packages from the install section in the settings.

### Additional Information:

![image](https://github.com/pulsar-edit/pulsar/assets/81979949/2abecd24-6f2e-4782-900e-313825b176fc)

Running the command ``` pulsar -p install --check``` shows no output and does nothing for my case.

**Comment by confused-Techie** [comment]
So two things here, but these are all issues we know about, feel free to refer to #586 and #411 as well as probably quite a few others.

1. Some community packages require native modules. This means they have C#/C++/C code that needs to be compiled into something compatible for the operating system they are installed on. To do this, your system needs a C Toolkit installed. This means you need to have some external dependencies installed, but like you've seen, not every community package has native modules.
  - Visual Studio 2019: I can see on the logs you have 2022 installed, unfortunately we are still on an older version of `node-gyp` so 2019 is the newest version that'll work. Plus of course you need the C++ tools installed.
  - Python  3.10: Anything newer than this (including Python 3.11) will not work. 3.11 has breaking changes, against semver rules, meaning it must be 3.10.

2. Secondly, many of the terminal packages have been unmaintained for quite some time, especially since we started updated Pulsar. The only terminal package I'm aware of that works is [`x-terminal-reloaded`](https://web.pulsar-edit.dev/packages/x-terminal-reloaded), which is currently a featured package, as well as is maintained by one of the core Pulsar devs, so sees much more active support.

So if you're able to make the above changes, things should be smooth sailing from here

**Comment by ayoubachak** [comment]
Thank you very much for the information provided!
