### ISSUE TITLE
Ruby's `blocky` package with new "Modern Tree-Sitter Implementation"

### ISSUE THREAD

**Issue by AlexWayfer** [pulsar-edit/pulsar#625]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Hello.

Thank you for your work.

I've enabled "Modern Tree-Sitter Implementation" after v106 update.

At the first sight, Ruby code highlighting became better (#236).

But now I've noticed that [the Ruby's `blocky` package](https://github.com/samu/blocky) is broken with this "Modern Tree-Sitter Implementation".

Should you tune the sitter or a package be updated?

### Pulsar version

106

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Arch, GNOME

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Enable "Use Modern Tree-Sitter Implementation".
2. Install `blocky` package.
3. Open Ruby code. 

### Additional Information:

I've checked required checkboxes about safe-mode, debugging, FAQ… but I haven't done these. I don't think it'd help. But I've checked for existing issues.

**Comment by savetheclocktower** [comment]
It looks like it [assumes an implementation detail](https://github.com/samu/blocky/blob/master/lib/compile-blockmap-with-tree-sitter.coffee#L36) from the old tree-sitter implementation, but I bet I can fix this with an alias. Thanks for the report!

**Comment by savetheclocktower** [comment]
OK, added this to #555. I'll make sure that PR gets landed before the next major release — or you can watch that PR and grab a rolling release a couple hours after the PR lands.

Thanks for the report!
