### ISSUE TITLE
GitHub Package CSS is broken on Pulsar v1.107.0

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#638]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The newest release of Pulsar v1.107.0 has resulted in the CSS style of the bundled GitHub package being broken.

When `less-cache` was updated to the newest version of `less` there were breaking changes in how mathematical expressions had to be written within a Less Style Sheet.

Pulsar does it's best to automatically fix this in all community packages if `Core: Transform Deprecated Style Sheet Math Expressions` is enabled. But, this functionality is always disabled for packages that come with Pulsar. Of which, the vast majority of this now live within this repo. 

All bundled packages that live in this repo have been updated to work fine on this newest update. But a single package, that still has not been moved over, the `github` package, did not see the fixes needed to work on this new version of Less.

Meaning, it's style sheets are now no longer compatible with Pulsar.

We are actively working to fix this issue, and it should be resolved by a soon to come hotfix.

### Pulsar version

v1.107.0

### Which OS does this happen on?

❓ Other(Please specify in the OS details field below)

### OS details

ALL

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

1. Launch Pulsar v1.107.0
2. Open the GitHub package pane
3. Realize it's broken styling

**Comment by DeeDeeG** [comment]
https://github.com/pulsar-edit/pulsar/pull/639 should fix this, which is included in the pending v1.107.1 hotfix we are building in CI as I type.

**Comment by confused-Techie** [comment]
Now that the hotfix has been released, we can go ahead and close this out
