### ISSUE TITLE
I would like to seek your help. During the process of installing the extension, he gave me feedback on an exception and I would like to know how to solve it

### ISSUE THREAD

**Issue by xingkongwuhen** [pulsar-edit/pulsar#643]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When I was installing plugins, there were many times when I couldn't load them, and he reported an error:

Searching for 'go plus' failed. Hide output

Connect ETIMEOUT 216.239.36.21:443

### Pulsar version

1.107.0，1.106.0

### Which OS does this happen on?

🪟 Windows

### OS details

win11

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Click on settings, then install, enter go for search, and most of the time, an error will be reported

**Comment by confused-Techie** [comment]
As this issue is now about 2 months old, and my original request for more information has never been answered, I'm going to go ahead and close this one.
