### ISSUE TITLE
Unable to run stylelint

### ISSUE THREAD

**Issue by AlexWayfer** [pulsar-edit/pulsar#645]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

```
ENOENT, static/index.json not found in /opt/Pulsar/resources/app.asar
```

![image](https://github.com/pulsar-edit/pulsar/assets/6510020/f58f3818-c215-49a7-9e4a-165dc60bf5e4)

Package: https://web.pulsar-edit.dev/packages/linter-stylelint

### Pulsar version

107.1

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Arch, GNOME

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install [`linter-stylelint`](https://web.pulsar-edit.dev/packages/linter-stylelint)
2. Enable it

### Additional Information:

I've not tried in safe or debugging modes.

Is it package-related issue or you can deal with it?

Sorry, there are no discussion, so I'm creating an issue.

**Comment by confused-Techie** [comment]
So I haven't dug to far into this package's code, but if I had to guess it seems this is an issue with the package itself.

The error is emitted [here](https://github.com/AtomLinter/linter-stylelint/blob/master/lib/helpers.js#L254) which seems to stem from a catch handler failing to account for the failure occurring.

Additionally, this seems to match an [error being reported on the repo](https://github.com/AtomLinter/linter-stylelint/issues/610) itself that began in Atom.

So I'm willing to bet this is something wrong within the package itself, but would be more than happy to discover otherwise.

**Comment by savetheclocktower** [comment]
There's a PR in that repo that claims to fix that issue.

In theory, one should be able to run

```sh
ppm install jsit/linter-stylelint -b stylelint-14
```

to install the version of the extension from that PR, but `ppm` isn't able to find that branch, even though it exists. @confused-Techie, do we know why `ppm` is doing the wrong thing there?

**Comment by confused-Techie** [comment]
@savetheclocktower I'm not to familiar with the behavior of PPM installing from a repo. @mauricioszabo was the one who originally authored the behavior and hopefully could provide some insight.

But let me find the PR claiming a fix

**Comment by confused-Techie** [comment]
Alternatively, seems the user providing that fix, has a fork of the package themselves, that's nearly 200 commits ahead of the published package.

[Here is the fork](https://github.com/alexrudd2/linter-stylelint) I may honestly recommend installation of this to test out, and if it truly works properly, we can add a broken badge status to the published package and recommend installation of this fork.

**Comment by AlexWayfer** [comment]
> Additionally, this seems to match an [error being reported on the repo](https://github.com/AtomLinter/linter-stylelint/issues/610) itself that began in Atom.

Yeah, I completely forgot about this, and my bad I've not checked package's issues, sorry.



> [Here is the fork](https://github.com/alexrudd2/linter-stylelint) I may honestly recommend installation of this to test out, and if it truly works properly

It's a good find, thanks.



> we can add a broken badge status to the published package and recommend installation of this fork.

Interesting idea. Probably we also should contact with the author of the fork, maybe they want to publish their version of the package for Pulsar.

**Comment by confused-Techie** [comment]
@AlexWayfer Fantastic idea on wanting to reach out to that author first, and already commented on your issue you've created.

So lets wait to hear back, but I have high hopes that either way this fork can resolve these issues for us, so fingers crossed

**Comment by AlexWayfer** [comment]
> ```shell
> ppm install jsit/linter-stylelint -b stylelint-14
> ```

```
> pulsar -p install jsit/linter-stylelint -b stylelint-14
Cloning https://github.com/jsit/linter-stylelint.git ✓
Can't find the branch, tag, or commit referenced by stylelint-14
```

---



> [Here is the fork](https://github.com/alexrudd2/linter-stylelint) I may honestly recommend installation of this to test out, and if it truly works properly, we can add a broken badge status to the published package and recommend installation of this fork.

Unfortunately, it doesn't: https://github.com/alexrudd2/linter-stylelint/issues/162

---

A little off-topic: how do you use `ppm`? I have installed Pulsar on Arch Linux from AUR and have no such command, I have to use `pulsar -p`.

**Comment by confused-Techie** [comment]
So @AlexWayfer while we made a best effort to attempt to contact the owner of the fork, seems they are unresponsive, and I'll prioritize adding a broken badge to this package, so we can close this issue. Thanks for attempting to contact the maintainer.

**Comment by AlexWayfer** [comment]
> I'll prioritize adding a broken badge to this package, so we can close this issue

As you wish, you can close (I don't know if the badge is required before closing).

**Comment by confused-Techie** [comment]
> > I'll prioritize adding a broken badge to this package, so we can close this issue
> 
> As you wish, you can close (I don't know if the badge is required before closing).

Thanks for understanding. I'll leave it open until the badge is added, as it's a good reminder for me to do so

**Comment by Spiker985** [comment]
@confused-Techie Reminder on broken badge, just in case

**Comment by confused-Techie** [comment]
Thank you @Spiker985

**Comment by alexrudd2** [comment]
I'm the author of the "fork," although I use that term loosely.  All I ever did was run dependabot, since I don't actually understand the code.

That said, it now runs for me (albeit with old `stylelint==13.13.1`) on Atom.

**Comment by confused-Techie** [comment]
> I'm the author of the "fork," although I use that term loosely. All I ever did was run dependabot, since I don't actually understand the code.
> 
> That said, it now runs for me (albeit with old `stylelint==13.13.1`) on Atom. EDIT: and Pulsar

Glad to see you chiming in. If you ever wanted I'd be more than happy to help you out with publishing this package to Pulsar, or if you'd rather with write permissions I'd be happy to publish myself, so that the community can enjoy having a `stylelint` package that functions properly

**Comment by alexrudd2** [comment]
Sure, invited you as a collaborator!
