### ISSUE TITLE
File type icon is not set

### ISSUE THREAD

**Issue by vanontom** [pulsar-edit/pulsar#662]
### Thanks in advance for your bug report!

- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When setting Pulsar as the default app for a specific file type (for example: text document, ".txt"), **Pulsar does not properly set the file type icon**. The icon set seems to be a generic default ("white paper" icon), which I assume is unintended. It should probably instead **set the file type icon to Pulsar's main app icon** (like Atom), or even better a fancy icon for the specific file type (see screenshot for example). Note: I am using Pulsar in [portable mode](https://pulsar-edit.dev/docs/launch-manual/sections/getting-started/#portable-mode) (settings in ".pulsar" folder including "electronUserData", next to the main "pulsar" folder).

### Pulsar version

1.107.2023072600 (portable)

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 11 (22H2, 22621.1992)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Right click a file (for example "note.txt").
2. Select "Open with", "Choose another app", "Pulsar" and "Always".
3. See that icon for all files of that type changes to generic icon (nothing indicating file type or app).

### Additional Information:

Screenshots:
Pulsar (result as documented)
![Pulsar](https://github.com/pulsar-edit/pulsar/assets/6421376/845d573c-e5b7-48fe-80ad-e8856701742d)
Notepads (result from other app, for example)
![Notepads](https://github.com/pulsar-edit/pulsar/assets/6421376/111d612e-b16f-412b-b800-b1947033b394)

**Comment by zhaolinlau** [comment]
same problem here

**Comment by Spiker985** [comment]
I believe this problem is specific to the portable version. A machine or user install sets the file icon to Pulsar's icon, when associating it with particular file types.

And that is presumably because Windows doesn't know where the icon file is

**Comment by EusebiuOprinoiu** [comment]
No, it's not specific to the portable version.
The issue is present in the normal installer as well. I tested both the user and system install methods.

**Comment by zhaolinlau** [comment]
any update regarding this issue?

**Comment by confused-Techie** [comment]
> any update regarding this issue?

Nothing yet. Although if you're available to help, it'd be great to determine if this is an issue that effects only windows 11, or if it also effects windows 10.

But beyond that, research into what's changed between the two versions would be needed to be done, so we can find out what changes have to be made when modifying the registry to make this happen.

**Comment by zhaolinlau** [comment]
> > any update regarding this issue?
> 
> Nothing yet. Although if you're available to help, it'd be great to determine if this is an issue that effects only windows 11, or if it also effects windows 10.
> 
> But beyond that, research into what's changed between the two versions would be needed to be done, so we can find out what changes have to be made when modifying the registry to make this happen.

well, i am willing to help but i dont have the ability since im just a noob student XD

**Comment by Spiker985** [comment]
Something that is interesting is that I had general release 1.107 on my Windows 11 laptop for work, and upgraded it to 1.108 and in both instances, I still have my icon

I would expect that the portable version wouldn't have an icon, as it's not registered inside the Windows registry - but you mentioned it isn't portable specific

**Comment by confused-Techie** [comment]
> Something that is interesting is that I had general release 1.107 on my Windows 11 laptop for work, and upgraded it to 1.108 and in both instances, I still have my icon
> 
> I would expect that the portable version wouldn't have an icon, as it's not registered inside the Windows registry - but you mentioned it isn't portable specific

Interesting, suppose we need to investigate the code directly that handles this to determine where the icon is actually coming from. Since what you're saying does sound about right, logically that it can't retrieve the icon if not already present in the registry.

I'll try taking a look at it sometime today.

**Comment by confused-Techie** [comment]
Alright, so looking at this, I am noticing something interesting.

The icon within this code path is defined as:

```javascript
const fileIconPath = `"${Path.join(
  process.execPath,
  '..',
  'resources',
  'cli',
  'file.ico'
)}"`;
```

Which sounds all well and good, but to be honest, looking at my current user install of Pulsar, this path does not exist for me.

Within the `resources` folder of my installation, I only have the following:

![image](https://github.com/pulsar-edit/pulsar/assets/26921489/731589ed-8f99-47b7-b457-6879455a350b)

Meaning, if I were to set  the icon, it'd be set to nothing, so there might be something more to this.

The other aspect to consider, is the logic of `process.execPath` seems to be much less precise than how we generally find the installation path of Pulsar, so it's possible that it may not always be correct.

So at least for me, it seems as if on my installation the path would never be set properly.

**Comment by confused-Techie** [comment]
Alright, so I've been able to get to the bottom of this one.

If you first, within Pulsar's settings enable `Register as file handler` then an entry is created in the Windows Registry, adding Pulsar as a program that can open a specific file, but it sets it with this non-existent icon. From here if you then tell windows you want to open a particular file with this program, this bad icon is used. Giving you the blank file icon that @vanontom is seeing.

Otherwise, if you never enable this setting in Pulsar, and just tell windows to open the file with a specific program, Windows will just use whatever icon is used for the program. And that's why it works for Spiker just fine, since they only used the windows menu.

So we should be able to resolve this, by fixing the icon that's set to the registry from above.

**Comment by vanontom** [comment]
Thank you for taking a look at this, @confused-Techie. And then actually figuring out what's going on. You must have one of those high quality brains (and helpful), congrats. I've checked my settings, under System, `Register as file handler` was indeed checked (I guess by myself at some point). Anyway, thankful that this visual nuisance will disappear soon enough. :)

**Comment by confused-Techie** [comment]
@vanontom FYI the windows rolling release version should be updated with this fix, so feel free to download it if you'd like!

Keep in mind for this full fix to take effect you'll likely need to disable `Register as file handler` then reenable it.

Hopefully windows is able to update the icon automatically, if not you may need to change the default program to something else, then change it back.
