### ISSUE TITLE
add an option to only (or first) display project (directory) in window title

### ISSUE THREAD

**Issue by allefeld** [pulsar-edit/pulsar#670]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

When searching for Pulsar in the task bar, especially if several instances are running, the current way the title bar text is chosen is not the most useful. Confusingly it changes with the currently selected file or other pane, e.g. "Settings" when the settings pane is focused.

I propose that, if a "project" (directory) is open, the name of this directory should be the only, or at least the first thing in the title. Additionally, if the name is long, it should be sensibly abbreviated, so it is possible to quickly figure out the right instance.

### What benefits does this feature provide?

Easier identification of the relevant instance of Pulsar in the task bar.

### Any alternatives?

This should be a customizable option.

**Comment by savetheclocktower** [comment]
I think this is a fine idea.

As a temporary workaround, [custom-file-title](https://web.pulsar-edit.dev/packages/custom-window-title) should let you accomplish this. I haven't tried this lately, but I know I've used it in the past.
