### ISSUE TITLE
Installing packages fails

### ISSUE THREAD

**Issue by stefaniecg** [pulsar-edit/pulsar#672]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

i cannot install any package nor update the app, see figures attached, it fails

```
Request for package information failed: getaddrinfo ENOTFOUND pulsar-edit.com

Installing “platformio-ide-terminal@2.10.1” failed.Hide output…
Request for package information failed: getaddrinfo ENOTFOUND pulsar-edit.com (ENOTFOUND)
```

To extend more information about the problem, i cannot even update pulsar. 
See image attached:

Figure 1 - description of file information  
![error](https://cvws.icloud-content.com/B/AZbGYJ-LWFA-90esOeYlZlANAq9bAWr9rtfNb1ds1QYRsUOYpQXXbT_h/update.png?o=Ap9Vsgx8JpNo9aTKgrrgm5Np5McM05L2jk80Borh6l4t&v=1&x=3&a=CAog4eI9qwfLe1UDxVBiWiBCPgGCEVfCfzNlg0fVLuLoHlMSaxCIjOPOnzEYiOm-0J8xIgEAUgQNAq9bWgTXbT_haiWMKBHBw3H7zzqR08WKg3zF7NETA8i8iX_DO0LIlCho7E0VpwbxciV3uipX2IoB9GoyT5qBU19bszrPC_wct9GLcVHMtFHKmhfxTf0s&e=1692117480&fl=&r=50325059-9955-480f-92f4-8072f259c91b-1&k=A_YfWtuD8OE5urhXaRD8UA&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=luXb7gp1fVRFZ0KDxL1wZfHB7E8&cd=i)

### Pulsar version

1.101.0-beta arm64

### Which OS does this happen on?

🍎 macOS

### OS details

13.4.1 (22F82)

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1 . Go to Settings/install
2. try to install any package, it just gives an error
`Request for package information failed: getaddrinfo ENOTFOUND pulsar-edit.com (ENOTFOUND)`

### Additional Information:

Images attached:

![updates](https://cvws.icloud-content.com/B/ASGUbsn1YooFjx5sB-an8IckcPcAATis3wsirqWCvei_NVpYP_-cHi5g/updates.png?o=Ahcfh0vQGVYZRescMV0rDGiT6enYl72zYIiN3QoBISHp&v=1&x=3&a=CAog-2I01gTJvDmZfNn-phiYXCVAeKaEFM8hGmsyMbie_lkSaxCgruDOnzEYoIu80J8xIgEAUgQkcPcAWgScHi5gaiW6MfjFwO28ElwElA5x97GJL4DqEtxwXY91Qn9AtxQiGaEz_zUlciV-3dix02dZCWpTKMWCvPh2tT9gIzKoaxuxD4puatZ6hl26rmoZ&e=1692117435&fl=&r=fbf1f367-8fd4-4dde-85bb-5aea7132a6ee-1&k=o6awcPiMderBcyOhuS2UFg&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=MEcM4u9zbQ0R3M_eEIaAr9dSWdg&cd=i)

![packages](https://cvws.icloud-content.com/B/AbV3LVKeZlSaQwZ_6Nz8JWpmkw3jAd0gLPmN_qX9FmbdhMUOYk2X4Ykz/packages.png?o=AlM1MvmifVF79SHbjvd-40BlBYFyzcZvwu8bgn-akekR&v=1&x=3&a=CAogW_IHpX61se-hpXXXP2RUBApWX2NHbf3Vttri7zv8_ysSaxC0y-bOnzEYtKjC0J8xIgEAUgRmkw3jWgSX4YkzaiXriDTXj0LHFmEDxcE4mjhjjj5ViW5BuDoxP7-lYyqz2Ux-j_oSciWwL7eBGZJ9f9QNOy26-dd7XRZxanMSh7DmsQYrKVIsRHFcWoAg&e=1692117537&fl=&r=43804e27-e5d3-4552-8972-c8eae28a853a-1&k=tCltR2-ZsP0Kqq91adyawg&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=udO-Gsb2vq2IxDuAemR3Z_Aw0eM&cd=i)

![packages2](https://cvws.icloud-content.com/B/AWuOG3PSPaVaT8MvQSCA4sZCgWmtAcCxxcs0cyGdlBb1bhRw-gPATsui/packages2.png?o=Aniq1LZQlT3n80WxrHNGyvVQb2plOhck3yKTJFCnZ3X5&v=1&x=3&a=CAog4olofwoIlLQPDvlgrPMLH6a8y-S_BfmywlFKA6q1TDASaxD18ejOnzEY9c7E0J8xIgEAUgRCgWmtWgTATsuiaiXlvZAChkV0uxC9_-IJu8MVrt8k4QSeFvNblp-qMx39ONjKilBHciXbauQH8tB2JKc4ROXWyoOhnzW-g0trBI0aBmIxNeUtVgb_bNf-&e=1692117575&fl=&r=76b85ff8-18d7-4c6a-9b7b-21f2ea8e8f5b-1&k=ZGsmY1hZ4HfILKzFy_yH9w&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=WdUEgSS1iFDs3WVA6m2p2E7XwhY&cd=i)

**Comment by Spiker985** [comment]
Uh, pulsar-edit.com is not the correct domain, pulsar-edit.dev is the proper domain - which is why you are receiving those errors.

You'll need to manually download the most recent update from https://pulsar-edit.dev/download.html

Note: we try to update on the 15th of every month, with a blog post of upcoming features on the 1st

**Comment by Spiker985** [comment]
To provide a bit more context, in the early days of releases we hadn't yet decided on pulsar-edit.dev or pulsar-edit.com. We relinquished the .com in favour of the .dev domain, and removed mentions of it.

**Comment by savetheclocktower** [comment]
@stefaniecg  I noticed you're on version `1.101.0-beta`. That probably explains why it's not looking at the right domain. Install a newer version [from the homepage](https://pulsar-edit.dev/) and everything will be fixed.

**Comment by stefaniecg** [comment]
Unfortunatly, package instalation is still failing in Regular version 1.107.1 arm64

Error:

```
Installing “platformio-ide-terminal@2.10.1” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0 install /private/var/folders/19/v_49911x3z14_bqrzrplg6tr0000gn/T/apm-install-dir-2023715-13881-zlrg51.gif9/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

  CXX(target) Release/obj.target/pty/src/unix/pty.o

prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=darwin)
(node:13888) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:60:
In file included from /Users/stefaniecg/.pulsar/.node-gyp/Library/Caches/node-gyp/12.2.3/include/node/node.h:67:
In file included from /Users/stefaniecg/.pulsar/.node-gyp/Library/Caches/node-gyp/12.2.3/include/node/v8.h:30:
/Users/stefaniecg/.pulsar/.node-gyp/Library/Caches/node-gyp/12.2.3/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/remove_cv.h:22:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Pulsar_107.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 22.5.0
gyp ERR! command "/Applications/Pulsar_107.app/Contents/Resources/app/ppm/bin/node" "/Applications/Pulsar_107.app/Contents/Resources/app/ppm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/19/v_49911x3z14_bqrzrplg6tr0000gn/T/apm-install-dir-2023715-13881-zlrg51.gif9/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/19/v_49911x3z14_bqrzrplg6tr0000gn/T/apm-install-dir-2023715-13881-zlrg51.gif9/package.json'
npm WARN apm-install-dir-2023715-13881-zlrg51.gif9 No description
npm WARN apm-install-dir-2023715-13881-zlrg51.gif9 No repository field.
npm WARN apm-install-dir-2023715-13881-zlrg51.gif9 No README data
npm WARN apm-install-dir-2023715-13881-zlrg51.gif9 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefaniecg/.pulsar/.apm/_logs/2023-08-15T18_00_23_607Z-debug.log
```
![image](https://cvws.icloud-content.com/B/AUbDb5Nj_zFGfICDgy64IZ-zhw8xAceXkmK7N0_BqE-1dvq1b-rS4MZ_/107.png?o=Ajs4viqwXnCKZaNR_j6eSrnj_VBFGOyUnqJ_CXzyC5Ru&v=1&x=3&a=CAogeSthKGOcmhDCzu28hao0Mq5vLs2NY5Le-nSCNKY5uJcSaxCMgIDTnzEYjN3b1J8xIgEAUgSzhw8xWgTS4MZ_aiWY0iPIKBmlh_ZJSEVKdfuz3q4invY3TjBlcnXV6X49anjYp_pCciXTVGmnDLEzNVQqPGsLEYdRYbVWA1lG6gAjxFPiqT8WD1ZRCjIq&e=1692126342&fl=&r=b71a05e4-27d1-4fc1-b584-352e920b4e26-1&k=qPt_oN_TMP26SxdJp_m-1g&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=CdHLxNzt4oX9ZHxqYgwBEjo1SDE&cd=i)

**Comment by Spiker985** [comment]
https://github.com/Spiker985/x-terminal-reloaded/issues/12

**Comment by stefaniecg** [comment]
@savetheclocktower @Spiker985 

Well... updating pulsar app is also not working, see image.

Also, i think it has to do with *previous versions files making a problem*. 
**How can I fully uninstall pulsar before installing a new version?**
other than just errasing the app icon in the apps folder (working in a MacOS)

before i was trying to install *platformio-ide-terminal* package, but after you mentioned it i installed Xterminal correctly.
But now i get an error of XTerminal of Incompatible Packages, i have rebuild the packages and close+reopen the app, but it still failing.

I think i need to clean up from old instalations. 
How can i do this?

Thank you for your help

```
x-terminal-reloaded 14.2.1
node-pty-prebuilt-multiarch@0.10.0 – dlopen(/Users/stefaniecg/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node, 0x0001): tried: '/Users/stefaniecg/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/stefaniecg/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node' (no such file), '/Users/stefaniecg/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

![updatingrolling](https://cvws.icloud-content.com/B/AZmKSW30M5VPw9dMxkjvoqQGvA8lAV6itQ2phla9gbIGeMs52FS5oKk8/updating_rolling.png?o=Agmaf2_0LJHNylz4kaPDoCPjqcv3HNUQa12QqdtkAouJ&v=1&x=3&a=CAogghKbvFFQdn0dZGB1jXsPtDTYcU7ol3O1QMoRqBlI3FkSaxCgy4TlnzEYoKjg5p8xIgEAUgQGvA8lWgS5oKk8aiW5RMsAumOrn2XEXH-QB8z_3b-93qdy244QYNwgxqxkqLP_-fOrciVOJUb1UeMN4YVm5fg55ptsq4nv7CXODD43wsyVrXRz4AuYONkP&e=1692164166&fl=&r=0204e648-f7e6-49a0-a8be-573bf56ff479-1&k=6kFp5V705cpMQnV4BQv6UA&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=5RKVq52PGMu3IHg_SSOSmxxmIQQ&cd=i)

**Comment by confused-Techie** [comment]
@stefaniecg Unfortunately at this time auto updates aren't supported. But the next release, coming out within a few hours, does include a new package called `pulsar-updater` to help alleviate this problem.

As for cleaning up the install, `electron-builder` the program that builds our binaries should do this fully for you. At least for anything that matters here.

Otherwise, generally on any OS to fully remove Pulsar you'd want to delete the application, and go ahead and remove the `USER/.pulsar` directory. Keep in mind this will delete all community packages and settings installed.

**Comment by Spiker985** [comment]
Also, you're using an M1 Mac, which did not have a prebuilt node-pty instance originally. However, it definitely should've tried to build node-pty from scratch :thinking: 

I'm currently working on some new versioning, but it's not conclusive currently.

**Comment by savetheclocktower** [comment]
@stefaniecg Apologies for glancing too quickly earlier.

I'd recommend trying to update the app first (by deleting, then downloading a new version) and seeing if that fixes your problem. All of your packages and settings will be preserved because they live in `~/.pulsar`.

Then I'd suggest backing up your `~/.pulsar` directory before deleting it, and perhaps even trying to remove one package at a time to see if something specific is causing your problem.

**Comment by stefaniecg** [comment]
@confused-Techie , thank you for the clarification. 
Then i'll wait for the 'few hours' for the next release to have the updater avalable. 
I guess you are releasing all this in the _rolling version_, right?

@savetheclocktower , hi thank you for your help
I have both the old app version, called it _Pulsar_OLD.app_, then downloaded the regular release, called it _Pulsar_reg.app_, then downladed the real release, left it as _Pulsar.app_. 
So maybe this is also causing the problem, is it?
I think i'll try erasing all, including the (./user/.pulsar) folder, and reinstall all again. 
Is that the best?

**Comment by confused-Techie** [comment]
@stefaniecg So this will actually be included in the newest Regular release, `v1.108.0`.
It should already be present in the rolling release you are using. You won't use this menu to update, Pulsar will just tell you when a new version is available via a notification. Or you can search `pulsar-updater check for update` in the command palette to trigger one manually.

**Comment by savetheclocktower** [comment]
@stefaniecg Please just make sure to back up your `.pulsar` folder — if I recall correctly, I had you apply a hotfix to a package that wasn't working a while back, and I'd hate for you to lose that.

I'm not clear on exactly what is failing to work for you at this point, so I'm unable to tell you the best steps to fix it.

**Comment by stefaniecg** [comment]
@savetheclocktower, yes you have a good memory, i had complety forgot about that. I'll be sure to back up the `/.pulsar` folder before installing the new pulsar version. I hope i can find the tutorial you sent me to do the changes. 

@confused-Techie, please let me know when the newest release is out `v1.108.0` so i can install this one. 
At the moment, it is still the previous version available .xx7 at the downloads. 

Thank you for your help guys, i'll wait for the 108 regular release

**Comment by confused-Techie** [comment]
> @savetheclocktower, yes you have a good memory, i had complety forgot about that. I'll be sure to back up the `/.pulsar` folder before installing the new pulsar version. I hope i can find the tutorial you sent me to do the changes.
> 
> @confused-Techie, please let me know when the newest release is out `v1.108.0` so i can install this one. At the moment, it is still the previous version available .xx7 at the downloads.
> 
> Thank you for your help guys, i'll wait for the 108 regular release

Yeah the website might take a bit to be updated, but check our GitHub releases for this repo. 1.108.0 was released some hours ago last night.

**Comment by confused-Techie** [comment]
> 😕  update still does not work 
> but i can install packages
> 
> ![error](https://cvws.icloud-content.com/B/AedUYnWkWv_3AVOk5IOPsFOjtTPZAc2ILax8NH8o6bqopUVtXtFuGjdx/update.png?o=AkaMSxKeFo2hic5ojEzQzN2a83k64MsBuIRcLJSzLr_q&v=1&x=3&a=CAogFC9PyRRamCorL6J-0bKA98rdy9ouU0NUNMqnaPeqjDUSaxDInbKcoDEYyPqNnqAxIgEAUgSjtTPZWgRuGjdxaiU9iSCxWCNfbVjoO32O6uP9tEmzLOvRR7VesFNC-sDOEPhR1UP5ciVOxsYHnVA6SjdUFpTkFAve42hs1SG_GwCC4Qq0i9gpwTCAy1i7&e=1692280257&fl=&r=32e883ef-8c34-4b46-a00c-9effac5968ee-1&k=X3kPLjP-JhCj740fhVt5nA&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=xpLbR6nvBTVRj5nKiCrd6cuaWi4&cd=i)
> 

Like I said above, this menu will still not work. The `pulsar-updater` package will notify you via a notification when an update to Pulsar is available. We do not expect this menu to work. And really, this menu will likely be removed rather soon

**Comment by stefaniecg** [comment]
ok, got it 🙂👍🏽
