### ISSUE TITLE
Expose command to toggle soft wrap

### ISSUE THREAD

**Issue by allefeld** [pulsar-edit/pulsar#690]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

In Atom it was possible to toggle softwrap with a keypress, I believe it was F10. Please expose a command which toggles soft-wrap (either globally or for the current editor), so that I can bind it to a key.

### What benefits does this feature provide?

I use Pulsar for both code and text. When I write code, I sometimes (at least temporarily) exceed the preferred line length, and then soft wrapping is inconvenient. When I write text, I always use one line per paragraph, and soft wrapping is essential. Sometimes both occur in the same document, e.g. with RMarkdown or Quarto. That means I switch soft wrapping on and off quite frequently, and always having to go to the settings is tedious.

### Any alternatives?

None that I know of.

### Other examples:

VS Code has this functionality as `editor.action.toggleWordWrap`, bound to Alt+Z.

**Comment by Spiker985** [comment]
The command `editor:toggle-soft-wrap` will do exactly what you want. You can add that your `keymap` file as the command name, and then validate it with the Keybinding Resolver (ctrl + period)

**Comment by allefeld** [comment]
Thanks! I asked because I couldn't find the command using the command palette.
