### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#720]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

It look similar to https://github.com/pulsar-edit/pulsar/issues/191

```
C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-editor-component.js:2584 Uncaught Error: Requested measurement of a line component that is not currently rendered
    at C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-editor-component.js:2567:23
    at Map.forEach (<anonymous>)
    at TextEditorComponent.measureHorizontalPositions (C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-editor-component.js:2558:39)
    at TextEditorComponent.measureContentDuringUpdateSync (C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-editor-component.js:425:10)
    at TextEditorComponent.updateSync (C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-editor-component.js:293:33)
    at TextEditorComponent.pixelPositionForScreenPosition (C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-editor-component.js:206:12)
    at HTMLElement.pixelPositionForScreenPosition (C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-editor-element.js:258:32)
    at C:\Users\asiloisad\.pulsar\packages\linter-ui-default\dist\index.js:1:45124
    at C:\Users\asiloisad\.pulsar\packages\linter-ui-default\dist\index.js:1:45300
    at C:\Users\asiloisad\.pulsar\packages\linter-ui-default\dist\index.js:1:2522
```

* After first occur of error, then every text editor scroll raise new error.
* I have not tested it in safe mode.

### Pulsar version

1.108.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

I do not know how to reproduce it. This often happens when I move the document view to the bottom (Ctrl+End), but this is not the rule.

### Additional Information:

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/4eaf86f0-968c-4068-800a-b8c9934a1594)

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this! While it isn't great to see another bug within `text-editor-component` (as it's one of the more legacy and mysterious files of the codebase), fingers crossed fixing this could get us closer to finally resolving the half screen editor error that has existed since I'm pretty sure the inception of Atom.

**Comment by asiloisad** [comment]
I'm pretty sure this issue is connected to half screen editor error, because the temporary fix was the same (ctrl-a ctrl-x ctrl-v), reopen file or window restart.

**Comment by savetheclocktower** [comment]
@asiloisad, do you know if this has happened again since we fixed #191 in Pulsar 1.111?

**Comment by asiloisad** [comment]
I haven't caught it in a long time, but I'm not sure if #191 solved it or if it was something else. I'm closing this thread for now 👍

**Comment by asiloisad** [comment]
It's long time that issue live with me, because It was hard to trace source of it. I currently maintain the hydrogen-next package and through one small glitch I finally managed to find the source of the problem and propose a solution https://github.com/pulsar-edit/pulsar/pull/1490.

The source of the problem is the pixelPositionForScreenPosition method, which in some circumstances leads to a cascade of errors, then the only thing left to do is close the editor and reopen it.
