### ISSUE TITLE
Python - match-case support

### ISSUE THREAD

**Issue by ditpowuh** [pulsar-edit/pulsar#730]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Match-case statements have yet to be implemented into the in-built 'language-python' package.

### Pulsar version

Any version (v1.109.0 was used to test)

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open/create Python file
2. Type a match-case statement

### Additional Information:

Screenshot:
![image](https://github.com/pulsar-edit/pulsar/assets/25289202/bbcfbe27-8d64-4f67-acf1-f854cc3a1083)

**Comment by Daeraxa** [comment]
This should work if you use the new tree-sitter grammar as I suspect you are still using the old one. You can turn it on via `Settings > Core > Use Modern Tree-Sitter Implementation`.

Legacy:
![image](https://github.com/pulsar-edit/pulsar/assets/58074586/d7bc83f3-e65d-47b1-8ec1-348968e8cc05)

Modern:
![image](https://github.com/pulsar-edit/pulsar/assets/58074586/86672492-efc5-4707-8f98-67c01a49e195)

**Comment by ditpowuh** [comment]
Oh, sorry. I did not realise. Thank you so much.
