### ISSUE TITLE
Rename `Flow JavaScript` to `JavaScript`

### ISSUE THREAD

**Issue by m1ga** [pulsar-edit/pulsar#739]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Currently the language for a JS file is called `Flow JavaScript` and works fine. But since this is the default language for JS why not just name it `JavaScript` or `JavaScript (Flow)` if the name has to be in there. For new users who want to select a custom language (e.g. when using an unsaved empty tab) you see:

![Screenshot_20230923_105025](https://github.com/pulsar-edit/pulsar/assets/4334997/06d24bc1-3d59-43bc-a72b-5ea916192e89)

and some people select the Rails version because it starts with JavaScript and they think Flow JavaScript is something else.

https://github.com/pulsar-edit/pulsar/blob/a82b4d01dd276ca5b9f479b8ec8fe1bdfd22fdbe/packages/language-typescript/grammars/tree-sitter-flow.cson#L1

### What benefits does this feature provide?

easier for new users to select the correct JavaScript langauge.

### Any alternatives?

-

**Comment by confused-Techie** [comment]
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/248d8b46-652b-40e7-af04-73af5f4792e2)

https://github.com/pulsar-edit/pulsar/blob/master/packages/language-javascript/grammars/javascript.cson#L48

The default package `language-javascript` should provide exactly this requested functionality. I'm curious why you aren't seeing it, or why it's not being used as the default language for `.js` files in your instance of Pulsar. Do you happen to have the package disabled? Or maybe some funky logic in your `init.js`?

But as always thanks a ton for contributing and getting involved!

**Comment by m1ga** [comment]
Oh wow, you are right!

Don't know why but it is listed under core but disabled:

![Screenshot_20230923_111109](https://github.com/pulsar-edit/pulsar/assets/4334997/16aee6e0-c38a-4bd0-9731-6703b1ddef40)

Maybe that happened while testing different builds :shrug: Thank you for the quick reply!

Now I can even use "Atom Beautify" in an unsaved file to indent JS. With Flow it always threw an error and I had to save the file and reopen it to make it work.

**Comment by confused-Techie** [comment]
Glad to see we got this one resolved! 

P.S.

For JavaScript I'd recommend using the new Tree-Sitter implementation, it's so much faster for me on reparses, in your settings you can enable `Use Modern Tree-Sitter Implementation` in `Core` and you'll get access to a whole host of new grammars all using the new experimental WASM version of Tree-Sitter. Obviously no need to switch (yet), but I love 'em
