### ISSUE TITLE
[Windows build] releases use older version of NSIS Installer to bundle/install Pulsar

### ISSUE THREAD

**Issue by wesinator** [pulsar-edit/pulsar#749]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The Windows build of the latest release [v1.109.0](https://github.com/pulsar-edit/pulsar/releases/tag/v1.109.0) is built using a relatively older version of the NSIS installer/bundler software. The installer executable was built with NSIS 3.04 which is from 2018. 

The latest version of NSIS is 3.09 which was released in July 2023. 

It is best to use the latest supported (i.e. non-major release change) version of NSIS on the release build machine to package and install Pulsar, to avoid introducing packaging bugs and security risks with older versions of NSIS.

### Pulsar version

v1.109.0

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Downloaded Windows installer from https://github.com/pulsar-edit/pulsar/releases/tag/v1.109.0

I can tell from the timestamp that the latest release built is built from NSIS 3.04 - https://sourceforge.net/projects/nsis/files/NSIS%203/

**Comment by confused-Techie** [comment]
While I agree it would be best to stay on the latest version of NSIS.

Unfortunately, the Pulsar project has zero control over which version is being used. Our entire build process is handled by [`electron-builder`](https://github.com/electron-userland/electron-builder/).

So if we were to use a newer version of NSIS to build our binaries it would have to be a change made upstream via this repo.

But thanks a ton for contributing!

**Comment by wesinator** [comment]
ah, I should've known it was an upstream issue.

**Comment by confused-Techie** [comment]
> ah, I should've known it was an upstream issue.

I might have to open this up over there, to see why we are using such an old version though. It always has been odd having to go to the old Control Panel uninstall menu for Pulsar.
