### ISSUE TITLE
Modern Tree-Sitter - duplicating scopes when deleting/undoing

### ISSUE THREAD

**Issue by mauricioszabo** [pulsar-edit/pulsar#756]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

![image](https://github.com/pulsar-edit/pulsar/assets/138037/afca0dab-b835-45c2-9cea-1d8d83441e7d)

### Pulsar version

1.109.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu 20.04

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Add the code to a Clojure file with modern tree-sitter:
```clojure
`(swap! ~'all-routes conj [])
```
2. Position the cursor `after all-routes`
3. Delete previous word (AKA - CTRL + Backspace
4. Hit undo.
5. Repeat 3-4 a couple times. You'll see the typing lag starts to become visible, up to the point that it'll lock the editor after a lot of tries.

**Comment by savetheclocktower** [comment]
Good repro instructions meant that this one was pretty easy to troubleshoot. Added to the [running fixes PR for October](https://github.com/pulsar-edit/pulsar/pull/783), but let me know if you'd rather it land ASAP so you can enjoy the fix in a rolling release.

**Comment by mauricioszabo** [comment]
More for a "philosophical" reason I would like these to be fixed in a rolling release - but it won't actually affect me by much because I am using a version with lots of branches merged to test multiple fixes and new features :)

**Comment by savetheclocktower** [comment]
Easy enough to make that PR a single-issue PR, so I changed its name. If you can 👍 the change, I'll get it landed ASAP.
