### ISSUE TITLE
Update language-php to escape $

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/pulsar#757]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

With the update of the ~~`less`~~ `snippets` update back in v1.107.0 `$` is marked as a variable marker.

This was noticed in [this discussion](https://github.com/orgs/pulsar-edit/discussions/203), which provides an answer to how to solve it

However, something that may have been overlooked was our inclusion of `language-php` inside Pulsar, which also contains snippets that use $

### Pulsar version

1.109.0

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

6.5.5-arch1-1

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Surfaced via [giusykurmikon in Discord](https://discord.com/channels/992103415163396136/992103415163396139/1161594695852499025)

1. Open new file
2. Set language to php
3. Paste `<? php th`
4. Toggle autocomplete (Ctrl + Space)
5. Select `$this->...` completion
6. Result: `<?php ->`
7. Expected Result: `<?php $this->`

### Additional Information:

All snippets for `language-php` need to be validated in v1.106 to get the expected output, and then updated within the repo with the proper escapement

**Comment by savetheclocktower** [comment]
This isn't about the `less` update. It's about the updates to the `snippets` package which make it so that `$` is a special character that always indicates a variable.

Anyway, this is easy enough to fix. I'll take care of it today or tomorrow.
