### ISSUE TITLE
Incorrect markup with `function...2>...function...case...--...`

### ISSUE THREAD

**Issue by danfuzz** [pulsar-edit/pulsar#769]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The following file seems to (more or less) crash the Bash source parser:

```bash
#!/bin/bash

function x {
    x 2>x
}

function x {
    case x in
        --*) : ;;
    esac
}
```

When I open a file with these contents, the file fails to get any markup whatsoever beyond `source.shell` on the whole file.

### Pulsar version

1.110.0

### Which OS does this happen on?

🍎 macOS

### OS details

13.6

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1. Create file named `test.sh`, and paste the contents noted above into it.
2. Close and reopen the file.

Result: No syntax markup in the file.

### Additional Information:

This is a follow-on to issue #736.

I tried reproducing this problem directly in the `tree-sitter-bash` project, and the example worked, both with tip-of-tree and with the specific commit that this repo is marked as using. My repro was done just by building `tree-sitter-bash` and then running `./node_modules/.bin/tree-sitter parse test.sh` — that is, I didn't try to build the exact same artifact as is present in this repo — so I can't totally discount a build-related problem with `tree-sitter-bash`. Barring that, it looks to me like the problem is somewhere in Pulsar, though I don't have a theory as to exactly what.

In case it helps, here's the `tree-sitter parse` output for the test file:

```
(program [0, 0] - [11, 0]
  (comment [0, 0] - [0, 11])
  (function_definition [2, 0] - [4, 1]
    name: (word [2, 9] - [2, 10])
    body: (compound_statement [2, 11] - [4, 1]
      (redirected_statement [3, 4] - [3, 9]
        body: (command [3, 4] - [3, 5]
          name: (command_name [3, 4] - [3, 5]
            (word [3, 4] - [3, 5])))
        redirect: (file_redirect [3, 6] - [3, 9]
          descriptor: (file_descriptor [3, 6] - [3, 7])
          destination: (word [3, 8] - [3, 9])))))
  (function_definition [6, 0] - [10, 1]
    name: (word [6, 9] - [6, 10])
    body: (compound_statement [6, 11] - [10, 1]
      (case_statement [7, 4] - [9, 8]
        value: (word [7, 9] - [7, 10])
        (case_item [8, 8] - [8, 17]
          value: (word [8, 8] - [8, 11])
          (command [8, 13] - [8, 14]
            name: (command_name [8, 13] - [8, 14]
              (word [8, 13] - [8, 14]))))))))
```

Also FWIW here is the original source file which was the basis for the test file: https://github.com/danfuzz/milky-cloud/blob/51223615217161b1f4cf1e8768e50b2ba8720320/scripts/lib/milky-cloud/instance/wait-until-responsive

**Comment by savetheclocktower** [comment]
Ah, I see the problem. In the console:

> Warning: parser wants to call function isalnum, but it is not defined. If parsing fails, this is probably the reason why. Please report this to the Pulsar team so that this parser can be supported properly.

This is yet another built-in function that we have to add to our version of web-tree-sitter. I'll be happy when we no longer have to do this.

**Comment by savetheclocktower** [comment]
OK, #770 should fix this. I've put it in its own PR so that we can get this fix out in a rolling release.

The annoying thing here is that

1. any tree-sitter parser can have an external C scanner that relies on builtin functions, and
2. you don't find out that `web-tree-sitter` has no knowledge of a certain builtin _until_ the scanner tries to call that builtin at runtime. Your previous test cases didn't reveal this problem because they didn't hit whatever code path needed the `isalnum` function.

There might be a more exhaustive way of knowing which parsers expect which builtins to be present, but I have not yet looked into it deeply enough to know. Thanks a bunch for filing these issues.

**Comment by confused-Techie** [comment]
Just wanted to pop in and add I really appreciate how thorough you were into investigating this one!
