### ISSUE TITLE
Getting a Glibc error and Pulsar won't run on Debian

### ISSUE THREAD

**Issue by nikodean1** [pulsar-edit/pulsar#773]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Pulsar Edit doesn't run on Debian 11

### Pulsar version

110

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Debian 11

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Start a terminal window with the default configuration.
Run ./Linux.Pulsar-1.110.0.AppImage
The following error occurs: 

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.org.chromium.Chromium.f8slYM)
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.org.chromium.Chromium.f8slYM)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_Linux.x1TUaN/resources/app.asar/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

### Additional Information:

libc6 and libc6-dev are already installed.

**Comment by DeeDeeG** [comment]
PR https://github.com/pulsar-edit/pulsar/pull/760 has been merged, which should resolve this issue for Debian 11 users.

We have Rolling releases out that are built on Ubuntu 20.04. I can determine that Pulsar _should_ be compatible with Debian 11 now that https://github.com/pulsar-edit/pulsar/pull/760 is merged, by noting that Debian 11 "Bullseye" (https://packages.debian.org/bullseye/glibc-source) and Ubuntu 20.04 "Focal" (https://packages.ubuntu.com/focal-updates/glibc-source) are both using the same version of glibc, version 2.31, per their respective web-based package archive browsing tools.

So, with https://github.com/pulsar-edit/pulsar/pull/760 merged, the latest Rolling release binaries should be runnable on Ubuntu 20.04 and distros based on it such as Zorin OS 16.x.

---

You can get the Rolling release binaries here (https://github.com/pulsar-edit/pulsar-rolling-releases/releases), and beyond that, the next Regular release should include the fix as well.

NOTE: For Rolling, the builds of each OS/arch aren't fully synchronized, and their version numbers may drift very slightly based on the time CI ran for each respective OS/arch. As such, not every "release" on the page has binaries for every OS/Arch. So, _if there is no `.deb` or `AppImage` for your arch in the latest Rolling release, please do scroll down to the next one that has a `.deb` or `AppImage` for your desired arch and get the binary from that version._

Or you may find it convenient to just grab the binaries from our website here (https://pulsar-edit.dev/download.html#rolling-release), which will automatically fetch the most recent binary for the OS/arch you ask for.
