### ISSUE TITLE
Incorrect highlighting on `$'...'` strings in shell scripts.

### ISSUE THREAD

**Issue by danfuzz** [pulsar-edit/pulsar#775]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

In shell scripts, C-style quoted strings don't get highlighted as strings; they just get default coloring. I believe this is because `tree-sitter-bash.cson` has a typo.

If you log the syntax markup within this quoted string:

```
echo $'hello'
```

it is:

```
source.shell
program
command
ansi_c_string
```

but `scopes` in `tree-siter-bash` instead says:

```
  'ansii_c_string': 'string'
```

### Pulsar version

1.110.0

### Which OS does this happen on?

🍎 macOS

### OS details

13.6

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1. Paste the line above into a shell script.
2. Observe the highlighting.

**Comment by confused-Techie** [comment]
Seems this didn't properly get closed after merging #776
