### ISSUE TITLE
Emacs formatting comment breaks C file syntax highlighting

### ISSUE THREAD

**Issue by Tamaranch** [pulsar-edit/pulsar#827]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When an emacs formatting comment is present at the beginning of a C source file, the highlighting switches to the text mate variant, in which many things are not recognized (custom types in particular), giving the impression of broken highlighting, even if the language is well recognized. 

Here's an example of such a file: https://gitlab.xfce.org/apps/xfce4-screensaver/-/blob/a7fd5217479ecb4d4d2897197eb9baf441c26596/src/gs-grab-x11.c

It is possible to force the use of the tree-sitter variant, but this must be done manually for each file via the grammar selector, and this choice is not saved when the file is closed.

### Pulsar version

1.111.0

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Arch Linux

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Open this file: https://gitlab.xfce.org/apps/xfce4-screensaver/-/blob/a7fd5217479ecb4d4d2897197eb9baf441c26596/src/gs-grab-x11.c
Possibly uncheck "Hide duplicate text mate grammars" in the grammar selector preferences, to see that the text mate variant is selected by default.

**Comment by savetheclocktower** [comment]
Thanks for the report! Just added the fix to #819; it'll go out with the 1.112 release in about a week.

**Comment by Tamaranch** [comment]
Great, thanks! That was fast :)
Really cool that Atom survived through Pulsar by the way :+1:
