### ISSUE TITLE
Make your own teletype servers

### ISSUE THREAD

**Issue by Xenonic** [pulsar-edit/pulsar#848]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

It would be really nice if you guys could bring back teletype, it does not work as the atom teletype servers have gone offline.

### What benefits does this feature provide?

I used to use teletype a lot, and now that it's gone its kind of annoying. If you guys could modify the plugin and add your servers it would be amazing.

### Any alternatives?

I do not know of any alternatives at this time.

**Comment by Daeraxa** [comment]
We have a discussion running on this already - this one is the most active https://github.com/pulsar-edit/pulsar/issues/536 so feel free to have a read and join in on that discussion.

**Comment by confused-Techie** [comment]
As there's been no other details added to this issue, and considering #536 is a more than complete discussion on Teletype, and addresses this issue exactly, I'll go ahead and close this one out.

Thanks a ton for contributing @Xenonic, if you have more to add to the Teletype discussion please add it on the existing issue
