### ISSUE TITLE
[Fork & Maintenance Request] double-tag, autoclose-html-plus, emmet

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/pulsar#85]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

The packages to speed up the workflow of web development and improve the convenience on completing HTML tags.

### Enter your response below:

In my opinion, a text editor which supports for web development should have some HTML tag features which are able to edit both HTML start and end tag at the same time, able to autoclose HTML tag after completing a HTML start tag like <html>, and also the emmet which very useful to speed up the workflow of web development.

### Any alternatives?

1. [double-tag](https://github.com/dsandstrom/atom-double-tag) by [dsandstrom](https://github.com/dsandstrom)

2. [autoclose-html-plus](https://github.com/binaryfunt/autoclose-html-plus) by [binaryfunt](https://github.com/binaryfunt)

3. [emmet](https://github.com/emmetio/emmet-atom) by [emmetio](https://github.com/emmetio)

**Comment by ThatXliner** [comment]
https://github.com/pulsar-edit/pulsar/discussions/73

**Comment by zhaolinlau** [comment]
> https://github.com/pulsar-edit/pulsar/discussions/73

I can't open the link

**Comment by kaosine** [comment]
@zhaolinlau, look for it in our organization discussions. It was moved there. At least that's where it should be now.

**Comment by zhaolinlau** [comment]
> @zhaolinlau, look for it in our organization discussions. It was moved there. At least that's where it should be now.

Uhm, I did check it out but I didn't see any discussion is related to my topic?

**Comment by kaosine** [comment]
It's the one about our specific languages that we're looking at supporting or that others do. I'll track down the specific thing once I'm done with dinner and try to get it to you.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by kaosine** [comment]
@zhaolinlau sorry about the delay, here's what @ThatXliner was referring to (or at least should've been since the original was replaced with a link pointing to this one):

https://github.com/pulsar-edit/.github/discussions/32

**Comment by zhaolinlau** [comment]
> @zhaolinlau sorry about the delay, here's what @ThatXliner was referring to (or at least should've been since the original was replaced with a link pointing to this one):
> 
> [pulsar-edit/.github#32](https://github.com/orgs/pulsar-edit/discussions/32)

Uhm, I still don't understand? Because my request is not about feature request, it's about to keep the packages alive.

**Comment by kaosine** [comment]
It's things we plan on supporting by expanding, by updating tree-sitter and LSP support. Once we're able to get things to work properly in electron13 and @mauricioszabo finishes their generic LSP package, we should be able to implement these in a way that I think is what XLiner was getting at.

**Comment by zhaolinlau** [comment]
> It's things we plan on supporting by expanding, by updating tree-sitter and LSP support. Once we're able to get things to work properly in electron13 and @mauricioszabo finishes their generic LSP package, we should be able to implement these in a way that I think is what XLiner was getting at.

Alright I understand now, thx btw

**Comment by mauricioszabo** [comment]
I _honestly_ don't feel that we have sufficient people (as of now) to keep _more_ packages - in fact, I wish we could keep _less_ packages instead.

So I don't feel this issue can be addressed now, if ever (I know it's a sad thing to say, but unfortunately the focus is on keeping the editor itself alive and well) - can we close it?

**Comment by zhaolinlau** [comment]
> I _honestly_ don't feel that we have sufficient people (as of now) to keep _more_ packages - in fact, I wish we could keep _less_ packages instead.
> 
> So I don't feel this issue can be addressed now, if ever (I know it's a sad thing to say, but unfortunately the focus is on keeping the editor itself alive and well) - can we close it?

Yes you can

**Comment by confused-Techie** [comment]
Closing at @mauricioszabo request, and the authors @zhaolinlau approval. This may be revisited in the future at some time. But for the time being and for the foreseeable future, it's just a feature we don't have the manpower for. Thanks for the contribution!
