### ISSUE TITLE
Packages don't run on Asahi Linux (Apple silicon, ARM64)

### ISSUE THREAD

**Issue by MarkWieczorek** [pulsar-edit/pulsar#871]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I am trying to install Pulsar on Asahi Linux, which runs on Apple silicon (ARM64). I've tried to install the flatpak version, and have also tried to download the ARM64 RPM and AppImage versions from the website, but these do not work. After clicking on the icon, nothing happens...

### Pulsar version

1.113

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Asahi Linux (running on Apple silicon)

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

Install the flatpak from the app store, or download the ARM64 binaries from the website.

**Comment by confused-Techie** [comment]
Thanks a ton for contributing!

Would you mind attempting to run Pulsar from the terminal trying some or all the following flags:

* `--no-sandbox`
* `--in-process-gpu`

Or even just trying to launch via the terminal at all, so we can see what if any error is being reported?

Thanks a ton!

**Comment by Daeraxa** [comment]
Sorry for not noticing this before but this can indeed be closed as this is most likely a duplicate of https://github.com/pulsar-edit/pulsar/issues/532. Asahi Linux needs the app built for a 16k pagesize which isn't possible with our current version of Electron - which we are obviously trying to move away from.

**Comment by confused-Techie** [comment]
Very good to know, thanks @Daeraxa

**Comment by aguegu** [comment]
![Screenshot from 2024-03-13 08-10-25](https://github.com/pulsar-edit/pulsar/assets/1559791/51e4097a-2061-4485-9775-2daa0751394b)
I also tried pulsar on a RK3588(arm64) devboard. Nothing shows up when launching Pulsar. Could be an electron problem though. But no any output feels clueless. 

Just FYI.
