### ISSUE TITLE
Open your snippets is not working

### ISSUE THREAD

**Issue by mauricioszabo** [pulsar-edit/pulsar#88]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

If you open Command Palette and asks for the command "open my snippets" it will not actually open the snippets - it'll open a blank file, and if you add something on that file, the snippet is not actually detected.

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu 20.04

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Choose "open my snippets" from command palette

**Comment by Spiker985** [comment]
_Stupid_ I was pulling my hair out trying to figure out why that was a problem, and it turns out _there's an entire js file for snippets_

Unbelievable!

Thank you for the pr @Sertonix

**Comment by Sertonix** [comment]
@mauricioszabo this is now fixed by [snippets#1](https://github.com/pulsar-edit/snippets/pull/1)
