### ISSUE TITLE
URL after a multibyte colon no longer recognized on GitHub Markdown grammar

### ISSUE THREAD

**Issue by luixxiul** [pulsar-edit/pulsar#885]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

On `1.113.0` URL after a multibyte colon is no longer recognized on GitHub Markdown grammar.

![Screenshot from 2024-01-20 14-02-20](https://github.com/pulsar-edit/pulsar/assets/3362943/dba3b941-1311-43fd-bcd4-96744c6f8808)

The issue is not reproduced on `1.109.0`.

![Screenshot_2024-01-20_05-05-37](https://github.com/pulsar-edit/pulsar/assets/3362943/ab4974a7-a581-4c18-9aef-b902942aecc0)

### Pulsar version

1.113.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Install `1.113.0`
2. Enable "GitHub Markdown" grammar
3. Paste `北宋行政区划：https://web.archive.org/web/20231221225348/https://blog.beeper.com`

**Comment by savetheclocktower** [comment]
`tree-sitter-markdown` is definitely supposed to detect all of these. But I can fix this one with a `hyperlink` injection for the ones it misses.

Thanks for the report! I'll be closing this in favor of #878, but please keep track of that issue to learn when this is fixed.
