### ISSUE TITLE
Syntax highlighting for R code

### ISSUE THREAD

**Issue by digitalwright** [pulsar-edit/pulsar#886]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

It would be great if syntax highlighting was available for R code (.R files).

### What benefits does this feature provide?

Currently .R Code is not recognized.

### Any alternatives?

I was unable to find any existing packages for Pulsar to support R syntax highlighting.

**Comment by claytonrcarter** [comment]
Hi there. 👋 

> I was unable to find any existing packages for Pulsar to support R syntax highlighting.

Maybe try this search: https://web.pulsar-edit.dev/packages/search?q=language-r

In particular, it turns up a couple hits like:
- https://web.pulsar-edit.dev/packages/language-r
- https://web.pulsar-edit.dev/packages/atom-language-r

I haven't tried either of them, but they may be worth a try.

**Comment by digitalwright** [comment]
Worked great. Thanks!

**Comment by claytonrcarter** [comment]
Great! Glad it worked. If you're all set, would you mind closing this issue? Thank you!
