### ISSUE TITLE
'toggle-line-comments' incorrect for file type

### ISSUE THREAD

**Issue by garrettboone** [pulsar-edit/pulsar#887]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I cannot reproduce this bug reliably but it has occurred regularly - I could not test in safe mode due to package needed for remote access to files in question but want to report it in case someone else experiences it as well. I admit I am not savvy enough about Pulsar to know what to try but am more than willing to try suggestions for troubleshooting.

## Issue
It regards the incorrect toggling of line comments when selecting multiple rows or a single row and using `ctrl+/`.

## Expected
In a php file, it will produce `//` in the beginning of each line. The file is identified as PHP grammar in the bottom bar. 

## What happens
It appears to be commenting with HTML syntax: `<!-- -->` and this is even in the presence of existing php comments (it comments out the comments).

## What I tried
I experienced this with tree-sitter enabled/disabled and legacy enabled/disabled. I did not add or remove any packages and did not experience this in the last pulsar version. I also tried closing/reopening the tab of the file in question but this did not change the behavior. It also behaved this way across multiple php files. Only closing Pulsar and restarting would change this behavior. It does not happen right away but after some time. It also occurs when I have about 20 tabs open. But this is normal for me as a baseline.

## Packages installed
atom-beautify
busy-signal
docblockr
fonts
intentions
language-vue
linter
linter-php
linter-ui-default
remote-ftp
linter-eslint-node (disabled)
php-cs-fixer (disabled)

## Keybindings showing for `ctrl+/`
`'atom-workspace atom-text-editor:not([mini])':
  'ctrl-/': 'editor:toggle-line-comments'`

`'.platform-win32 .github-FilePatchView atom-text-editor:not([mini])':
  'ctrl-/': 'github:toggle-patch-selection-mode'`

`'.platform-linux .github-FilePatchView atom-text-editor:not([mini])':
  'ctrl-/': 'github:toggle-patch-selection-mode'`

### Pulsar version

1.113.0

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10 Pro

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Cannot reproduce, but is "temporarily fixed" when Pulsar is restarted. There were also no errors in the Console.

**Comment by savetheclocktower** [comment]
Thanks for this report!

I've [committed a fix](https://github.com/pulsar-edit/pulsar/pull/859/commits/2a0ebacf62a4c06c34d9726f3bd78b798a80b03a) to #859. That PR's description has instructions for downloading a Pulsar build that has this fix applied; the build is usually available within an hour after a commit.

I'm closing this in favor of #876; follow that issue if you want to know when this will be available in a rolling release. It will surely be fixed in 1.114, which will be released in mid-February.
