### ISSUE TITLE
[Feature Request] Add "prefill form" setting to `symbols-view`

### ISSUE THREAD

**Issue by claytonrcarter** [pulsar-edit/pulsar#890]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

`fuzzy-finder` has a `prefillFromSelection` setting that, when enabled, has the editor copy any selected text into the select list when you toggle the file finder and buffer finder, etc. I think it would be useful for `symbols-view` to do the same thing when the symbols select list is toggled.

### What benefits does this feature provide?

- more convenient for users searching through their symbols
- more consistent with other similar fuzzy find/select list features already present in the app

### Any alternatives?

@savetheclocktower [suggested](https://github.com/pulsar-edit/pulsar/pull/861#issuecomment-1908910131) updating `symbols-view` to use buffer symbols when using `jump-to-declaration`. That would solve most of this, but I still think that prefilling the form would be helpful when you just want to browse for similar symbols w/o knowing exactly which one to jump to.

### Other examples:

`fuzzy-finder` already supports this in `toggle-file-finder` and `toggle-buffer-finder`

**Comment by savetheclocktower** [comment]
This won't take long, but I might put it off for a week or so until I can get some of the syntax highlighting stuff landed.
