### ISSUE TITLE
Modern Tree Sitter breaks auto-indentation on line break

### ISSUE THREAD

**Issue by Tamaranch** [pulsar-edit/pulsar#894]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Since 1.113 (with Modern Tree Sitter enabled by default), auto-indentation on line break is now done using tabs only, instead of spaces. Disabling Modern Tree Sitter fixes the problem.

### Pulsar version

1.113.0

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Arch Linux

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

* Set tab size to two spaces in preferences
* Paste this code:
  ```c
  f (a,
     b,
  ```
* Place the cursor after `b,` and press Enter

With Modern Tree Sitter cursor is in column 3 (one space before `b`), with Legacy Tree Sitter it is in column 4 (aligned with `b`).

**Comment by savetheclocktower** [comment]
Is this in C/C++?

**Comment by savetheclocktower** [comment]
Yep, confirmed. I'll look into this. Thanks for the report!

**Comment by Tamaranch** [comment]
> Is this in C/C++?

Yes initially it's in C/C++. I didn't specify the language because I assumed it was language-independent, but it's true that there may not be auto-indentation for such an expression in all languages.

That said, it doesn't seem to be specific to C/C++, and it may be that as soon as auto-indentation of this type can take place, the problem is reproducible, as it is for example in shell with the following code, inserting a new line after `cmd` (which is preceded by 3 spaces):
```sh
while :; do
   cmd
done
```

**Comment by savetheclocktower** [comment]
I [made this change](https://github.com/pulsar-edit/pulsar/commit/d5fb9f50077d5d3437ad10994dc2ea78971701da) a while ago and I know it was for a specific reason, but I swear I can't remember what it was now, and I'm annoyed with myself.

Considering that legacy Tree-Sitter behaves the opposite way, I'm going to revert this change, and if that breaks something it'll have to be fixed some another way.

**Comment by savetheclocktower** [comment]
[Reverted](https://github.com/pulsar-edit/pulsar/pull/859/commits/ecf4fa39174364a8985c33fa582178782377d43e).
