### ISSUE TITLE
[modern-tree-sitter] Java Syntax Highlighting

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#896]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I've noticed what feels like a bug in Java Syntax Highlighting.

Which to be clear is way better in Java, although still seems to be missing something.

In the following snippet:

```java
import java.util.Scanner;

public class balloon {
  public static void main(String[] args) {
    int initialDiameter;
    Scanner scnr = new Scanner(System.in);
    System.out.print("Input Initial Diameter: ");
    initialDiameter = scnr.nextInt();
    
    int diameter = initialDiameter;
    
    double v1 = Math.PI * initialDiameter * initialDiameter * initialDiameter / 6;

    diameter = diameter++;
    
  }
}
```

In this snippet the `diameter = diameter++;` only applies highlighting on the `=` with the rest being just basic text.

Additionally, the assignment of `initialDiameter` is blank, along with usage of `initialDiameter` later on, although thats less of an issue.

To be clear, non of this is a regression, in fact in the Legacy Tree-Sitter the situation is the same, except two things:
  * The `++` is highlighted, which is the only regression present.
  * All variable instantiating has no highlighting

So mostly things are better here, but still not perfect.

Would love if you could take a look!

### Pulsar version

1.113.0

### Which OS does this happen on?

🪟 Windows

### OS details

2H22

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Create file `anthing.java`
2. Paste above code snippet in
3. View the lack of highlighting

**Comment by savetheclocktower** [comment]
Addressed in [this commit](https://github.com/pulsar-edit/pulsar/pull/859/commits/a8215f107c43103234edd39649356a12ca5e65cd). Should now scope variables whenever they're reassigned or incremented. Also added `--` and `++` as operators.

**Comment by confused-Techie** [comment]
Amazingly speedy @savetheclocktower, absolutely unbelievable, thanks!
