### ISSUE TITLE
Option to Select Folders on Single Click, and Toggle Folding Once Selected

### ISSUE THREAD

**Issue by D-Maxwell** [pulsar-edit/pulsar#919]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

hello there ;

Having to resort to using a mouse sucks, for sure.
Yet I find myself making use of it to select a file|folder in the tree view, as I find it to be much more intuitive and (for some reason, somehow) faster than navigating the whole way with nothing my keyboard.

However.
Once I have selected an entry in the tree, it either opens the selected file, or toggles the folding of the folder ; which may not be what I want, and in fact is very rarely the case.

Simply put, in order to avoid such annoyances, as the current behaviour more often that not bugs me out, or even frustrates me, I wish there were an option so that clicking once on any entry in the tree view would simply select it at first, upon which one is free to either click once more (if they really love their mouse that much) or return to their trusty keyboard, and may choose to continue with any action that they had originally planned to execute, without the need to spend additional time fighting against the editor which decided it had to open a new tab without asking.

### What benefits does this feature provide?

Does what one would expect, instead of acting in place of the user by assuming they will only ever want to open a file, and not do any of the other actions that are listed in the related context menu for instance.

This would speed up my workflow ever so slightly, and avoid certain frustrations.

### Any alternatives?

Apart from an option in the settings, perhaps making it the default behaviour could be appreciated.

### Other examples:

I have for the most part begun switching over to VSCodium, however, when it comes to strict web development, I still make use of Pulsar. This feature is present on the former, and I wish an option to replicate this behaviour were brought to the latter editor.

**Comment by savetheclocktower** [comment]
I'm not ruling this out as a config option, but for now there are a few packages that do this. I've used [dbclick-tree-view](https://web.pulsar-edit.dev/packages/dbclick-tree-view) for a long time.

**Comment by D-Maxwell** [comment]
> I'm not ruling this out as a config option, but for now there are a few packages that do this. I've used [dbclick-tree-view](https://web.pulsar-edit.dev/packages/dbclick-tree-view) for a long time.

Well this isn't quite the behaviour I wish were present, although it is still better than the native one.

**Comment by savetheclocktower** [comment]
> I wish there were an option so that clicking once on any entry in the tree view would simply select it at first, upon which one is free to either click once more (if they really love their mouse that much) or return to their trusty keyboard

This is exactly what happens for me when I have `dbclick-tree-view` installed with the default settings. What further behavior do you need that this doesn't give you?
