### ISSUE TITLE
Light installation

### ISSUE THREAD

**Issue by Sertonix** [pulsar-edit/pulsar#93]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

I suggest having a light and a normal version of Pulsar. The light version would not include any build-in packages.

### Enter your response below:

This would allow an installation on machines with less space and ram.

### Any alternatives?

Maybe the build-in packages could only be disabled in the light version and not completely removed

**Comment by Sertonix** [comment]
I don't think the `documentation` tag is correct.

**Comment by Daeraxa** [comment]
The automatic tagging still needs to be sorted.
What sort of packages would you not want included by default? We can't say *no* built-in packages because that means you would have no package installer, no languages at all, no editor and no Pulsar - pretty much everything in Pulsar is made of packages.

**Comment by Sertonix** [comment]
I am aware of the problem with electron but I still think that deactivating all build-in packages would have an effect on the resources required to run pulsar. If you disable all build-in packages it would still be possible to use pulsar. Packages can be installed via the command line and settings can be manually edited in the files.
It would be nice if somebody could check what effect this would have on the resources required. If the effect is minimal a light version would not make sense.

**Comment by Daeraxa** [comment]
What I mean is *what* built-in packages are you talking about, practically all of Pulsar is made of packages. 
Look at this readme of the packages - this is what is included as part of core. I'm not sure what packages could be removed realistically outside of the language packages and I'm not sure they contribute much to the startup etc but you could always check using timecop... which is also a Pulsar core package.
If you disable *all* built-in packages you literally don't end up with anything realistically usable.

**Comment by Sertonix** [comment]
I see your point. Because you could also disable all build-in packages just from the config file this is redundant and I close it.

**Comment by mauricioszabo** [comment]
@Sertonix I think it's still worth a try. While you can disable built in packages, it actually doesn't make any difference in RAM, speed, or start-up time - most built-in packages are required by default.

I can check if it does make a difference later, and if so we can try to reopen this issue
