### ISSUE TITLE
Org files are detected automatically as Clojure scripts

### ISSUE THREAD

**Issue by silarri** [pulsar-edit/pulsar#934]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Organized files (.org files) are detected by Pulsar Editor as Clojure files, causing many different problems (e.g., related to highlighting and slowness). This seems to happen with any version later than 1.112.1. Files with extension .org should be detected as "Organized" files. I can change this manually by selecting the suitable option in the status bar, but when I open the file again I need to change it again every time. The problem is that if I open a large .org file (which is usually the case in my system), Pulsar freezes for quite a long time because it tries to interpret it as Clojure.

The solution to this problem seems to be extremely simple (just interpret .org files as "Organized" rather than "Clojure" files), but it made me go back to version 1.112.1 (as otherwise it is unusable for me due to the "freeze effect" mentioned).

### Pulsar version

1.114.0

### Which OS does this happen on?

🍎 macOS

### OS details

Sonoma

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Just try to open an organized file with extension .org. You will see in Pulsar's status bar that it is recognized as a Clojure file instead. You can change it manually to solve temporarily the problem, but you will have to do this every time.

**Comment by savetheclocktower** [comment]
One quick fix for this would be to disable the `language-clojure` package, assuming you don't have any need for Clojure support.

@mauricioszabo, how common is it for an `.org` file to be Clojure? Could a `contentRegex` be added here?

**Comment by mauricioszabo** [comment]
WOW, that's SO WEIRD!

I'm going to take a look at that, but no, there's no Clojure (or Clojure-flavor) that have `.org` as extension...
