### ISSUE TITLE
"Hidden" build directory gone

### ISSUE THREAD

**Issue by AchimPieters** [pulsar-edit/pulsar#947]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I updated to the latest version of Pulsar.

With the previous version, when I compiled my code I saw a greyed out 'build' directory.
Now this is gone, and don't know how to get it back?

### Pulsar version

1.114.2024030715 x64

### Which OS does this happen on?

🍎 macOS

### OS details

Sonoma 14.3.1

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Compile some code in C.

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this issue!

This sounds like somehow a setting changed in your `tree-view` package.

Can you check if in the `tree-view` package if the setting `Hide VCS Ignored Files` is enabled? If enabled this hides all the "greyed out" directories and files.

**Comment by AchimPieters** [comment]
@confused-Techie Thank you, that did the trick! There was a tick before the Hide VCS Ignored files, when removing the tick it turned back as I wanted it!
