### ISSUE TITLE
Support Window Background Transparency

### ISSUE THREAD

**Issue by D-Maxwell** [pulsar-edit/pulsar#948]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

As part of the general theme I am *trying* to make my Windows installation follow, I would quite simply love having Pulsar follow this acrylic theme.
Upon looking for related packages, to my surprise, there are none for Windows. Instead, one must (or used to need to) rely on https://github.com/transcranial/atom-transparency, which modifies a grand total of two electron settings in order for it to support transparency on Windows (haven't tested on any Linux compositors yet).
Therefore, I have come here to ask for the implementation of the changes over at [atom-transparency](https://github.com/transcranial/atom-transparency).

### What benefits does this feature provide?

This would allow for greater customisability, which I reckon is one of the main points of the editor.

### Any alternatives?

As it would seem that this is required at an application level, I doubt a package could ever be able to modify this behaviour.

### Other examples:

Plenty of other apps support this ; they either allow for plain transparency which one can blur through 3rd party software like Mica for Everyone, officially support it by baking it in, or are able to do so through packages (somehow), e.g. VSCode(ium) (vibrancy-extended).

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this issue!

We probably want to take a further look at this to ensure that making this change doesn't make things transparent by default, but at the very least I can see a very valid use case for adding support for this via a launch flag, possibly seeing if we can match the one used on Linux, that way it's straightforward to use for end users.

**Comment by oblivcheck** [comment]
Any progress on the matter? I'm eagerly anticipating this feature:D

**Comment by DeeDeeG** [comment]
Hi folks, sorry this took a while. Kinda dropped off the radar amongst more top-of-line topics.

But we have https://github.com/pulsar-edit/pulsar/pull/982 merged now, so transparency should be available via a setting now! In Rolling releases within an hour or so, and then in Regular releases planned for later this evening.
