### ISSUE TITLE
Editor hang, and throws Uncaught RuntimeError: Aborted(). Build with -sASSERTIONS for more info.

### ISSUE THREAD

**Issue by dahe5** [pulsar-edit/pulsar#955]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Pulsar package that provides the described functionality: <https://atom.io/packages>

### Description

When editing the following the file ```test.txt```, the with the following contents. Editor freeze and throws errors when placing cursor after ```...URL_``` and are unable to recover.

```
<!-- Title: Test -->


# Test

* _URL 1:_ www.ikke.no
* _URL 1:_ www.ikke.no 
```

### Steps to Reproduce

1. new file ```test.md```
2. Enter text
3. Copy line ``` * _URL 1:_ www.ikke.no
4. Paste line ``` * _URL 1:_ www.ikke.no
5. Edit copy of line ``` * _URL 1:_ www.ikke.no
6. Editor freeze, and throws error when attempting to edit.

## What you expect to happen
Continue to edit markdown file as usual

### Actual behavior
Window freeze unable to continue inn this file.

### What actually happens 
Not there yet... vim? to get the work done, then look into the problem more thoroughly.

### Versions

**Pulsar**: 1.114.0 arm64
**Electron**: 12.2.3
**OS**: macOS 14.3.1
**Thrown From**: Pulsar Core

### Stack Trace

Uncaught RuntimeError: Aborted(). Build with -sASSERTIONS for more info.

```
At /Applications/Pulsar.app/Contents/Resources/app.asar/vendor/web-tree-sitter/tree-sitter.js:268

RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (/app.asar/vendor/web-tree-sitter/tree-sitter.js:267:29)
    at _abort (/app.asar/vendor/web-tree-sitter/tree-sitter.js:1217:21)
    at null.<anonymous> (wasm://wasm/000babee:0:118869)
    at ts_tree_edit_wasm (wasm://wasm/000babee:0:147738)
    at Tree.edit (/app.asar/vendor/web-tree-sitter/tree-sitter.js:2211:27)
    at LanguageLayer.handleTextChange (/app.asar/src/wasm-tree-sitter-language-mode.js:3380:17)
    at WASMTreeSitterLanguageMode.bufferDidChange (/app.asar/src/wasm-tree-sitter-language-mode.js:285:28)
    at TextBuffer.emitDidChangeEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:956:25)
    at TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:950:10)
    at TextBuffer.revertToCheckpoint (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1387:14)
    at TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1322:12)
    at TextEditor.transact (/app.asar/src/text-editor.js:2467:24)
    at /app.asar/src/text-editor.js:1799:19
    at TextEditor.mergeSelections (/app.asar/src/text-editor.js:4050:47)
    at TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:4015:10)
    at TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1798:17)
    at TextEditor.insertText (/app.asar/src/text-editor.js:1747:25)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.didTextInput (/app.asar/src/text-editor-component.js:1845:24)
```

### Commands

```
     -8:41.1.0 core:select-down (input.hidden-input)
     -8:40.4.0 core:select-left (input.hidden-input)
     -8:36.6.0 core:cut (input.hidden-input)
     -8:09.9.0 core:copy (input.hidden-input)
     -0:43.3.0 core:move-up (input.hidden-input)
 14x -0:42.8.0 core:move-right (input.hidden-input)
 11x -0:40.6.0 core:backspace (input.hidden-input)
     -0:36.3.0 editor:consolidate-selections (input.hidden-input)
     -0:36.3.0 core:cancel (input.hidden-input)
     -0:32.6.0 core:move-up (input.hidden-input)
     -0:32.4.0 core:move-right (input.hidden-input)
     -0:31.3.0 core:select-down (input.hidden-input)
     -0:30.1.0 core:copy (input.hidden-input)
  2x -0:29.8.0 core:paste (input.hidden-input)
     -0:28.9.0 core:move-up (input.hidden-input)
 10x -0:28.6.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
autocomplete-java 1.2.7 
ide-haskell 2.7.0 
ide-java 0.9.1 
language-haskell 1.24.0 
language-kotlin 0.5.0 
language-latex 1.2.0 
latex-autocomplete 1.1.1 
pdf-view 0.73.0 
sort-lines 0.19.0 
```

### Pulsar version

1.114.0 arm64

### Which OS does this happen on?

🍎 macOS

### OS details

macOS 14.3.1

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

1. new file ```test.md```
2. Enter text
3. Copy line ``` * _URL 1:_ www.ikke.no
4. Paste line ``` * _URL 1:_ www.ikke.no
5. Edit copy of line ``` * _URL 1:_ www.ikke.no
6. Editor freeze, and throws error when attempting to edit.

### Additional Information:

Did some research into the issue, but I'm lying when i claim to have tested in safe-mode, and debugging-mode...
but I needed somewhere to store the issue until i can research further.  Sorry about that.

It would be of great help if: "create issue on pulsar-edit/pulsar" actually made a lookup of the subject. In this case ```Uncaught RuntimeError: Aborted(). Build with -sASSERTIONS for more info.``` to get a slightly better starting-point for debuging.

**Comment by savetheclocktower** [comment]
This is a known issue, so I'm closing this in favor of #898.

@dahe5, we have a replacement Markdown grammar that is set to become the default very soon! [This comment](https://github.com/pulsar-edit/pulsar/issues/878#issuecomment-1920366112) has more details. If you like, install it and let me know if you encounter any issues.

**Comment by syrsly** [comment]
Requesting this issue be reopened because the error message I'm still getting almost a year later links to this issue.
![Pulsar_ZLs69EN6Nu](https://github.com/user-attachments/assets/8eac34a0-96a9-486a-b32a-74b1558d8af0)

**Comment by savetheclocktower** [comment]
> Requesting this issue be reopened because the error message I'm still getting almost a year later links to this issue.

What language are you writing in? Can you trigger this message consistently?
